### ISSUE TITLE
Use AutoPeftModelForCausalLM to merge and save model cause crashed in the low VRAM situation

### ISSUE THREAD

**Issue by ytchen175** [huggingface/peft#1083]
### System Info

Platform
---
* Ubuntu 20 LTS

Python
---
* 3.11.5

Lib
---
* peft=0.5.0
* accelerate=0.21.0
* transformers=4.31.0

### Who can help?

 @pacman100 @younesbelkada @sayakpaul

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

I'm using 3080ti, which only has 12G vram.
I have fine-tuned an LLama2 7B adapter with qlora scripts and it can be called with AutoPeftModelForCausalLM ideally (cool!!!),
```python
model = AutoPeftModelForCausalLM.from_pretrained(
    adapter_model_path,
    local_files_only=True, 
    load_in_4bit=True, 
)
...some inference code, looks great!

```

So I'd like to merge a whole model ( base model + adapter ) and save it, I use these scripts, but I got an `ValueError: Cannot merge LORA layers when the model is loaded in 8-bit mode`.

```python
model = AutoPeftModelForCausalLM.from_pretrained(
    adapter_model_path,
    local_files_only=True, 
    load_in_4bit=True, 
)

model = model.merge_and_unload()
model.save_pretrained(merged_model_path)
```

Due to my poor vram, I can't merge them, then I tried to move the model into CPU ( [ref]( https://github.com/artidoro/qlora/issues/29#issuecomment-1737072311) )
```python
model = AutoPeftModelForCausalLM.from_pretrained(
    adapter_model_path,
    local_files_only=True, 
    load_in_4bit=True, 
    device_map={"": "cpu"}
)

model = model.merge_and_unload()
model.save_pretrained(merged_model_path)
```

Output: 
And my machine crashed, according to `nvidia-smi` monitoring, it uses just 2 MB vram, which seems weird.
```bash
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:42<00:00, 21.35s/it]
Killed
```

I'm wondering if is there any way to merge them together in the low vram situation? 
through `AutoPeftModelForCausalLM` works fine, but I prefer to call it with `transfomers.AutoModel` class, thanks!

### Expected behavior

1. Use base model + adapter by  `AutoPeftModelForCausalLM`
2. Merge a whole model ( base model + adapter )
3. Save it
4. Call it via `transfomers.AutoModel` class and its derivatives next time

**Comment by BenjaminBossan** [comment]
Hey, what PEFT version are you using? Could you check if merging works when you use the latest PEFT version?

**Comment by ytchen175** [comment]
I upgraded PEFT from 0.5.0 to 0.6.0 and I got the following error, is there any advice?

```
/home/wirl/anaconda3/lib/python3.11/site-packages/peft/tuners/lora/bnb.py:213: UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.
  warnings.warn(
Traceback (most recent call last):
  File "/home/wirl/code/try_qlora_to_merge_model.py", line 121, in <module>
    model.save_pretrained(merged_model_path)
  File "/home/wirl/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 1715, in save_pretrained
    raise NotImplementedError(
NotImplementedError: You are calling `save_pretrained` on a 4-bit converted model. This is currently not supported
```

**Comment by BenjaminBossan** [comment]
This seems to be a restriction from transformers.

In general, I would suggest to save only the adapter weights of your trained model (calling `save_pretrained` on the `PeftModel` _before_ merging). Then for inference, load the quantized transformer model as usual, load the PEFT adapter (`PeftModel.from_pretrained(...)`) and, only then, merge the adapters with `merge_and_unload`. That way, you don't need to ever save the merged model itself.

**Comment by ytchen175** [comment]
So what did `AutoPeftModelForCausalLM` do? Did it `merge_and_unload` first? 
In other words, why can it generate fine-tuned text by **calling with just adapter path**?

**Comment by BenjaminBossan** [comment]
> So what did `AutoPeftModelForCausalLM` do?

What line exactly are you referring to? In general, only the adapter weights need to be saved and loaded, as the original model can be loaded independently.

**Comment by ytchen175** [comment]
I mean I'm curious about why can I call `AutoPeftModelForCausalLM`, but `merge_and_unload` failed? 
They both load base model and adapter into GPU in my imagination.

**Comment by BenjaminBossan** [comment]
> I mean I'm curious about why can I call `AutoPeftModelForCausalLM`, but `merge_and_unload` failed?

Calling `AutoPeftModelForCausalLM.from_pretrained` loads the base model and adds the adapter on top. The error message [you posted above](https://github.com/huggingface/peft/issues/1083#issuecomment-1794725180) indicates to me that it's not the merging that fails but trying to save the model.

**Comment by ytchen175** [comment]
> Calling `AutoPeftModelForCausalLM.from_pretrained` loads the base model and adds the adapter on top. The error message [you posted above](https://github.com/huggingface/peft/issues/1083#issuecomment-1794725180) indicates to me that it's not the merging that fails but trying to save the model.

Oh, I misunderstood, I will try to use the method that you [suggested](https://github.com/huggingface/peft/issues/1083#issuecomment-1794758219), thank you!

**Comment by steveepreston** [comment]
Hey @BenjaminBossan

I'm still getting this warning on latest version while just merging it (not even saving).

peft 0.14.0 / transformers 4.48.0 / bitsandbytes 0.45.0

```python

base_model_id = "gemma-2-27b-it"

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_storage=torch.bfloat16,
)

base_model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    quantization_config=quantization_config,
    attn_implementation="sdpa",
    torch_dtype=torch.bfloat16,
    use_cache=True,
)

peft_model = PeftModel.from_pretrained(base_model, adapter_path)

--> merged_model = peft_model.merge_and_unload()
```
Warning:
```

UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.

```
