### ISSUE TITLE
out of memory because peft casts data from 16 to 32 bits

### ISSUE THREAD

**Issue by mrticker** [huggingface/peft#1149]
### Feature request

This is more of a  question than a feature request. Sorry if there's a better place to ask it. 

I'm trying to finetune an LLM in 16 bit. It should fit in GPU memory, but it runs out of memory. The issue seems to be with peft:

> Traceback (most recent call last):
>   File "/train.py", line 85, in <module>
>     model = prepare_model_for_kbit_training( model )
>   File "/usr/local/lib/python3.9/site-packages/peft/utils/other.py", line 98, in prepare_model_for_kbit_training
>     param.data = param.data.to(torch.float32)

It seems that the data get casted to 32 bits, which defeats the point of training in 16 bits.

What is going on here?

### Motivation

^

### Your contribution

^

**Comment by younesbelkada** [comment]
hi @mrticker 
For quantized models it is recommended to cast the layer norms in fp32 for training stability. You can remove the call to `prepare_model_for_kbit_training` to overcome that behaviour. But make sure to properly deal with `gradient_checkpointing` in case you use it, as described here: https://github.com/huggingface/peft/issues/1142

**Comment by mrticker** [comment]
Thank you @younesbelkada
