### ISSUE TITLE
TypeError: PeftConfig.__init__() got an unexpected keyword argument '_from_model_config'

### ISSUE THREAD

**Issue by GrayZ77** [huggingface/peft#1168]
### System Info

I was loading my own local lora model in Langchain-Chatchat, and I encountered with this error:
TypeError: PeftConfig.__init__() got an unexpected keyword argument '_from_model_config'

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
项目版本：v0.2.7
langchain版本：0.0.339. fastchat版本：0.2.32


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['DISC-LawLLM'] @ cpu
{'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/root/Langchain-Chatchat/peft_lawllm',
 'port': 20002}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================


2023-11-22 17:35:13,492 - startup.py[line:649] - INFO: 正在启动服务：
2023-11-22 17:35:13,492 - startup.py[line:650] - INFO: 如需查看 llm_api 日志，请前往 /root/Langchain-Chatchat/logs
2023-11-22 17:35:14 | ERROR | stderr | INFO:     Started server process [2218]
2023-11-22 17:35:14 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-22 17:35:14 | ERROR | stderr | INFO:     Application startup complete.
2023-11-22 17:35:14 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-11-22 17:35:16 | ERROR | stderr | Process model_worker - DISC-LawLLM:
2023-11-22 17:35:16 | ERROR | stderr | Traceback (most recent call last):
2023-11-22 17:35:16 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-22 17:35:16 | ERROR | stderr |     self.run()
2023-11-22 17:35:16 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-22 17:35:16 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-22 17:35:16 | ERROR | stderr |   File "/root/Langchain-Chatchat/startup.py", line 385, in run_model_worker
2023-11-22 17:35:16 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-22 17:35:16 | ERROR | stderr |   File "/root/Langchain-Chatchat/startup.py", line 213, in create_model_worker_app
2023-11-22 17:35:16 | ERROR | stderr |     worker = ModelWorker(
2023-11-22 17:35:16 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 63, in __init__
2023-11-22 17:35:16 | ERROR | stderr |     super().__init__(
2023-11-22 17:35:16 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/base_model_worker.py", line 47, in __init__
2023-11-22 17:35:16 | ERROR | stderr |     self.conv = self.make_conv_template(conv_template, model_path)
2023-11-22 17:35:16 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/base_model_worker.py", line 75, in make_conv_template
2023-11-22 17:35:16 | ERROR | stderr |     conv = get_conversation_template(model_path)
2023-11-22 17:35:16 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 334, in get_conversation_template
2023-11-22 17:35:16 | ERROR | stderr |     return adapter.get_default_conv_template(model_path)
2023-11-22 17:35:16 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 569, in get_default_conv_template
2023-11-22 17:35:16 | ERROR | stderr |     config = PeftConfig.from_pretrained(model_path)
2023-11-22 17:35:16 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/peft/config.py", line 134, in from_pretrained
2023-11-22 17:35:16 | ERROR | stderr |     config = config_cls(**kwargs)
2023-11-22 17:35:16 | ERROR | stderr | TypeError: PeftConfig.__init__() got an unexpected keyword argument '_from_model_config'
```

### Expected behavior

TypeError: PeftConfig.__init__() got an unexpected keyword argument '_from_model_config'

**Comment by BenjaminBossan** [comment]
Could you please show what is contained in `model_path`, i.e. the directory that should contain the adapter files? Especially, could you show all files and the content of `adapter_config.json`?

**Comment by GrayZ77** [comment]
![image](https://github.com/huggingface/peft/assets/76860116/ae55dccb-3fea-43ff-81b1-96282ae3239f)
![image](https://github.com/huggingface/peft/assets/76860116/a8ae4e00-52f2-41f5-98f8-716ffbd2497a)

> Could you please show what is contained in `model_path`, i.e. the directory that should contain the adapter files? Especially, could you show all files and the content of `adapter_config.json`?

**Comment by BenjaminBossan** [comment]
This is strange, the content of `adapter_config.json` looks wrong, maybe it's a `generation_config.json`? Do you know how it was created?

**Comment by GrayZ77** [comment]
> This is strange, the content of `adapter_config.json` looks wrong, maybe it's a `generation_config.json`? Do you know how it was created?

I'm trying to load local llm in LangChain-Chatchat, and I just literally rename the file 'config.json' to 'adapter_config.json' following the wiki.

**Comment by BenjaminBossan** [comment]
> I just literally rename the file 'config.json' to 'adapter_config.json' following the wiki.

This doesn't sound correct to me, these two configs are not the same. Could you please share a link where this is documented?

**Comment by GrayZ77** [comment]
> > I just literally rename the file 'config.json' to 'adapter_config.json' following the wiki.
> 
> This doesn't sound correct to me, these two configs are not the same. Could you please share a link where this is documented?

It's in this link: https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5#%E5%BE%AE%E8%B0%83%E6%A8%A1%E5%9E%8B%E5%8A%A0%E8%BD%BD%E5%AE%9E%E6%93%8D

![image](https://github.com/huggingface/peft/assets/76860116/13312e54-8a9c-44c0-b05f-a16412fa8676)

**Comment by BenjaminBossan** [comment]
I ran google translate on the document and if it's translated correctly, this suggestion doesn't look right, as `config.json` and `adapter_config.json` are two different things. I do not know what `Langchain-Chatchat` does with the file, so maybe it should still work, but it looks incorrect to me. When a PEFT model is trained and saved, there should always be a separate `adapter_config.json`, which is required for PEFT to load the adapters.

**Comment by ShanJianSoda** [comment]
哥，解决了吗，我也碰到一样的问题了，llama-factory微调（LoRA）后导出的chatglm3-6b-LoRA，用chatchat部署不起来
