### ISSUE TITLE
[`torch.compile()`] fails on PEFT LoRA in `diffusers`

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/peft#1199]
```bash
Unsupported: call_method ListIteratorVariable() __contains__ [ConstantVariable(str)] {}

from user code:
   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 1047, in forward
    scale_lora_layers(self, lora_scale)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/peft_utils.py", line 114, in scale_lora_layers
    module.scale_layer(weight)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/layer.py", line 165, in scale_layer
    if active_adapter not in self.lora_A.keys():

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

Code:

```python
from diffusers import DiffusionPipeline
import torch

pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(pipe_id, torch_dtype=torch.float16).to("cuda")

pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors", adapter_name="toy")

pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)

prompt = "toy_face of a hacker with a hoodie"

lora_scale= 0.9
image = pipe(
    prompt, num_inference_steps=30, cross_attention_kwargs={"scale": lora_scale}, generator=torch.manual_seed(0)
).images[0]
```

Reproduction Colab:
https://colab.research.google.com/gist/sayakpaul/986f8b0b70945a77a3ba301adc4c2969/scratchpad.ipynb

Cc: @patrickvonplaten @apolinario

**Comment by BenjaminBossan** [comment]
Indeed, PEFT currently doesn't work with `torch.compile` (maybe some methods do, but not, for instance, LoRA). We have reported back to PyTorch and are waiting for a fix. There isn't really anything on our side we could do, short of completely rewriting PEFT, so :crossed_fingers: that the PyTorch devs resolve some of the `torch.compile` limitations.

We have a [GH action](https://github.com/huggingface/peft/actions/workflows/torch_compile_tests.yml) that runs all PEFT tests with `torch.compile` enabled and allows us to see what does and doesn't work right now. It has to be triggered manually.

**Comment by patrickvonplaten** [comment]
My 2 cents here is that issue should have very low prio - why would one not just fuse the LoRA and then apply torch.compile to the whole unet? I don't see a use case where one would torch compile the unet + LoRA without merging the LoRA

**Comment by younesbelkada** [comment]
@sayakpaul does it fails on the nightlies as well?
Note we also have CI tests for it: https://github.com/huggingface/diffusers/blob/main/tests/lora/test_lora_layers_peft.py#L1098 that we currently skip

**Comment by sayakpaul** [comment]
it does.

**Comment by sayakpaul** [comment]
@patrickvonplaten w.r.t https://github.com/huggingface/peft/issues/1199#issuecomment-1836242433, it actually fails after fusion too (tested on Torch 2.2, as well):

```python
from diffusers import DiffusionPipeline
import torch

pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(pipe_id, torch_dtype=torch.float16).to("cuda")

pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors", adapter_name="toy")
pipe.fuse_lora()
pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)

prompt = "toy_face of a hacker with a hoodie"

lora_scale= 0.9
image = pipe(
    prompt, num_inference_steps=30, cross_attention_kwargs={"scale": lora_scale}, generator=torch.manual_seed(0)
).images[0]

image = pipe(
    prompt, num_inference_steps=30, cross_attention_kwargs={"scale": lora_scale}, generator=torch.manual_seed(0)
).images[0]
```

Error:

```bash
Traceback (most recent call last):
  File "/home/sayak/run_peft.py", line 14, in <module>
    image = pipe(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sayak/diffusers/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 1208, in __call__
    noise_pred = self.unet(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sayak/diffusers/src/diffusers/models/unet_2d_condition.py", line 834, in forward
    def forward(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2123, in run
    super().run()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1303, in LOAD_ATTR
    result = BuiltinVariable(getattr).call_function(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 636, in call_function
    result = handler(tx, *args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 1110, in call_getattr
    return obj.var_getattr(tx, name)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 234, in var_getattr
    unimplemented(f"class property {typestr(base)} {typestr(subobj)}")
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: class property UNet2DConditionModel getset_descriptor

from user code:
   File "/home/sayak/diffusers/src/diffusers/models/modeling_utils.py", line 212, in __getattr__
    is_in_config = "_internal_dict" in self.__dict__ and hasattr(self.__dict__["_internal_dict"], name)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

But when `peft` is uninstalled, it works. I think that is a bit of a problem.

**Comment by pacman100** [comment]
Hello, `mode="reduce-overhead", fullgraph=True` shouldn't be used with PEFT. Becuase of support for multiple adapters there is conditional logic present such as checking if an adapter is active. Because of this fullgraph is never possible and the error you are seeing is because of these options which break during the first encounter of conditional logic. Removing these options and then compiling should work as per my last checks.

**Comment by sayakpaul** [comment]
Alright. Thanks for these!

I will time the speedup (if any) with compilation then.

**Comment by sayakpaul** [comment]
@pacman100 some findings. `peft` seems to take a hit in terms of throughput when torch-compiled. 

For example, without `peft`, we get:

* 8.45it/s (just `torch.compile()`)
* 9.11it/s (`torch.compile()` with mode set to `"max-autotune"`) 

With `peft`, these numbers are:

* 7.76it/s
* 8.28it/s

(Tested on an A10G)

**Comment by pacman100** [comment]
Hello,

These numbers are expected as there are graph breaks with PEFT due to conditional logic to handle multipl adapters. This isn't the case without PEFT at the cost of multi adapters not being supported.

**Comment by sayakpaul** [comment]
Agreed. I thought documenting and being aware of it would be beneficial as we tackle questions on these from the community all the time.

**Comment by sayakpaul** [comment]
Closing the issue hence.

**Comment by andypotato** [comment]
Looking at this discussion, maybe you could reconsider your plan to deprecate `fuse_text_encoder_lora` with version 0.27?

I am aware of the limitations, but right now I feel there are a lot of drawbacks introduced with PEFT. Some background:

I'm currently doing extensive testing with SDXL Turbo and I found that using PEFT will increase the image generation time by about 50%. Fusing a Lora on the other hand has no measurable effect on performance.

As I understand from the comment by @pacman100, using PEFT will additionally have a significant impact on performance after compilation, which makes it an even less attractive option to use, at least for me.

Therefore, why not just keep the option of fusing?

**Comment by sayakpaul** [comment]
Well, for experimentation, you would likely need to swap in and swap out LoRAs until and unless you settle on the combination that works for you. You could then just fuse the LoRAs to obtain the highest amount of speed. @patrickvonplaten explains this even better here: https://github.com/huggingface/diffusers/pull/6190#issuecomment-1874014188. 

> Therefore, why not just keep the option of fusing?

The ability to fuse LoRAs is not going anywhere 😄 Sorry if the comments sounded otherwise. We have a separate code path altogether for it when you use `peft`:
https://github.com/huggingface/diffusers/blob/f3d1333e028d30f54306ae10930ea50d3cc25edb/src/diffusers/loaders/lora.py#L1052

> I'm currently doing extensive testing with SDXL Turbo and I found that using PEFT will increase the image generation time by about 50%.

Do you have any minimal reproducible snippets for us to see further? Maybe having it in a separate issue thread could be more helpful.
