### ISSUE TITLE
How to add trainable parameters? (bugs in 'modules_to_save')

### ISSUE THREAD

**Issue by shawnricecake** [huggingface/peft#1278]
### System Info

Hi,

How can I train other weights in the model rather than fix them during lora training?

### Who can help?

@BenjaminBossan Hi, I find you are active recently so I @ you here..

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```
self.model, self.peft_optimizer, _, self.peft_lr_scheduler = deepspeed.initialize(
            config=training_args.deepspeed,
            model=model,
            model_parameters=optimizers['model_parameters'] if self.training_args.do_train else None,
            optimizer=hf_optimizer,
            lr_scheduler=hf_lr_scheduler
        )
```
I add the parameters I want to train in `hf_optimizer`, but those parameters still do not change

### Expected behavior

the gradient of those parameters added to `hf_optimizer` should not be None

**Comment by shawnricecake** [comment]
I make my peft_config like following:
```
peft_config = LoraConfig(
                    r=training_args.lora_r,
                    lora_alpha=training_args.lora_alpha,
                    target_modules=["q_proj",]
                    lora_dropout=training_args.lora_dropout,
                    bias="none",
                    task_type=TaskType.CAUSAL_LM,

                    modules_to_save=["v_proj"],
                )
```
I only add  the `v` for training, but it shows the error:
```
Traceback (most recent call last):
  File "src/quant_train_lora.py", line 259, in <module>
    train()
  File "src/quant_train_lora.py", line 251, in train
    trainer.train()
  File "/data/sx/gpt-quant/gpt-finetune/src/quant_lora_trainer.py", line 188, in train
    token_prune_idx_all, lower_bit_idx_record, middle_layers_logits = self.model(
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1802, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/sx/gpt-quant/gpt-finetune/src/peft/peft_model.py", line 965, in forward
    return self.base_model(
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/sx/gpt-quant/gpt-finetune/src/peft/tuners/tuners_utils.py", line 106, in forward
    return self.model.forward(*args, **kwargs)
  File "/data/sx/gpt-quant/gpt-finetune/src/transformers/models/llama/modeling_llama.py", line 1690, in forward
    token_prune_idx_all, lower_bit_idx_record, middle_layers_outputs = self.model(
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/sx/gpt-quant/gpt-finetune/src/transformers/models/llama/modeling_llama.py", line 1490, in forward
    lower_bit_idx_current, remove_token_idx_current = decoder_layer(
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/sx/gpt-quant/gpt-finetune/src/transformers/models/llama/modeling_llama.py", line 1018, in forward
    lower_bit_idx_current, remove_token_idx_current = self.self_attn(
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/sx/gpt-quant/gpt-finetune/src/transformers/models/llama/modeling_llama.py", line 504, in forward
    value_states = self.v_proj(hidden_states)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/sx/gpt-quant/gpt-finetune/src/peft/utils/other.py", line 185, in forward
    return self.modules_to_save[self.active_adapter](*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1557, in _call_impl
    args_result = hook(self, args)
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 392, in _pre_forward_module_hook
    self.pre_sub_module_forward_function(module)
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 505, in pre_sub_module_forward_function
    param_coordinator.fetch_sub_module(sub_module, forward=prev_grad_state)
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sx/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 310, in fetch_sub_module
    assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary()
AssertionError: {'id': 325, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {27}, 'ds_tensor.shape': torch.Size([0])}

```

**Comment by pacman100** [comment]
Let me take a look this week.

**Comment by nightmaredimple** [comment]
> Let me take a look this week.

Any updates?
