### ISSUE TITLE
Lora resume training from checkpoint error

### ISSUE THREAD

**Issue by nuoma** [huggingface/peft#1304]
### System Info

torch 2.1.2+cu121
transformers 4.33.0
transformers-stream-generator 0.0.4
peft 0.7.1
accelerate 0.25.0
deepspeed 0.12.5
nvcc --version release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0
nvidia-smi  525.147.05 Driver Version: 525.147.05 CUDA Version: 12.0

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Code base I'm using 
```
https://github.com/shibing624/MedicalGPT/blob/main/supervised_finetuning.py
```

Shell for training stage1
```
CUDA_VISIBLE_DEVICES=2,3 torchrun --nproc_per_node 2 ../supervised_finetuning.py \
    --model_type baichuan \
    --model_name_or_path /data/llm/models/Pretrained/Baichuan2-7B-Base/ \
    --train_file_dir ../data/finetune/blossom_stg1/ \
    --per_device_train_batch_size 10 \
    --do_train \
    --use_peft True \
    --num_train_epochs 1 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.03 \
    --weight_decay 0. \
    --bf16 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy epoch \
    --save_total_limit 5 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 8 \
    --output_dir ../outputs/20231225_exp1_stg1 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 64 \
    --lora_alpha 128 \
    --lora_dropout 0.05 \
    --torch_dtype bfloat16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --cache_dir ./cache \
    --model_max_length 4096 \
    --deepspeed ../deepspeed_zero_stage2_config_no16.json \
    --template_name baichuan2   
```

shell for resume training stage2
```
CUDA_VISIBLE_DEVICES=5,7 torchrun --nproc_per_node 2 ../supervised_finetuning.py \
    --model_type baichuan \
    --model_name_or_path /data/llm/models/Pretrained/Baichuan2-7B-Base/ \
    --train_file_dir ../data/finetune/blossom_stg2/ \
    --peft_path ../outputs/20231225_exp1_stg1/ \
    --per_device_train_batch_size 10 \
    --do_train \
    --use_peft True \
    --max_train_samples -1 \
    --num_train_epochs 3 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.03 \
    --weight_decay 0. \
    --bf16 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 5 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 8 \
    --output_dir ../outputs/20231225_exp1_stg2 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 64 \
    --lora_alpha 128 \
    --lora_dropout 0.05 \
    --torch_dtype bfloat16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --cache_dir ./cache \
    --model_max_length 4096 \
    --deepspeed ../deepspeed_zero_stage2_config_no16.json \
    --template_name baichuan2   
```

Error info
```
{'loss': 1.1006, 'learning_rate': 1.4442364268520997e-05, 'epoch': 0.9}
{'loss': 1.0321, 'learning_rate': 1.4415619149505215e-05, 'epoch': 0.9}
30%|█████████████████▍                                        | 2326/7710 [2:16:18<4:40:30,  3.13s/it]                                                                                                               ../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [550,0,0], thread: [0,0,0]                                                                                                                Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [550,0,0], thread: [1,0,0]                                                                                                                Assertion `srcIndex < srcSelectDimSize` failed.

***multiple similar lines omitted***

Traceback (most recent call last):
  File "/data/mn/shibing624/MedicalGPT-1.6.3-231215/shell/../supervised_finetuning.py", line 1383, in <                                                                                                               module>
    main()
  File "/data/mn/shibing624/MedicalGPT-1.6.3-231215/shell/../supervised_finetuning.py", line 1344, in m                                                                                                               ain
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/transformers/trainer.py", line 1553,                                                                                                                in train
    return inner_training_loop(
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/transformers/trainer.py", line 1835,                                                                                                                in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/transformers/trainer.py", line 2679,                                                                                                                in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/transformers/trainer.py", line 2704,                                                                                                                in compute_loss
    outputs = model(**inputs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 151                                                                                                               8, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 152                                                                                                               7, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", li                                                                                                               ne 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", li                                                                                                               ne 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 151                                                                                                               8, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 152                                                                                                               7, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/accelerate/utils/operations.py", line                                                                                                                680, in forward
    return model_forward(*args, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/accelerate/utils/operations.py", line                                                                                                                668, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16,                                                                                                                in decorate_autocast
    return func(*args, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/peft/peft_model.py", line 1073, in fo                                                                                                               rward
    return self.base_model(
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 151                                                                                                               8, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 152                                                                                                               7, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 10                                                                                                               3, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/manuo/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 684, in                                                                                                                forward
    outputs = self.model(
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 151                                                                                                               8, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/mn/anaconda3/envs/manuo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 152                                                                                                               7, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/manuo/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 420, in                                                                                                                forward
    attention_mask = self._prepare_decoder_attention_mask(
  File "/home/manuo/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 349, in                                                                                                                _prepare_decoder_attention_mask
    combined_attention_mask = _make_causal_mask(
  File "/home/manuo/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 62, in                                                                                                                _make_causal_mask
    mask = torch.full((tgt_len, tgt_len), torch.tensor(torch.finfo(dtype).min, device=device), device=device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below mig                                                                                                               ht be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

### Expected behavior

Problem Description:
I intend to perform two-stage SFT training with Lora. The base model is Baichuan-2-7B-Base,  the first stage uses Lora and Alpaca to train for one epoch, then the second stage uses Sharegpt and previous Lora weight to resume training for 2 more epochs.

The problem is that, during the second stage of training, when the process reaches close to 1epoch, the training process was terminated with the exception. My guess from the error message is that it has to do with peft, have you guys seen similar things?

thanks!

**Comment by nuoma** [comment]
update:

I tried using a different dataset, and no error occurred. I then tried the original dataset (original error), only to swap the order of jsonl file for stage 1 and stage 2, and same error information occurred. 

This is even more weird, since the sharegpt format file should be processed by datasets at the very beginning of the training. Why it waited till the very end of 1 epoch for the error message to show up?

Example jsonl
```
{"conversations": [{"from": "human", "value": "Mr. and Mrs. Boyden take their 3 children to a leisure park. They buy tickets for the whole family. The cost of an adult ticket is $6 more than the cost of a child ticket. The total cost of the 5 tickets is $77. What is the cost of an adult ticket?"}, {"from": "gpt", "value": "Let's say the cost of a child ticket is x dollars.\nThe cost of an adult ticket is x+6 dollars.\nThe total number of child tickets is 3.\nThe cost of the 3 child tickets is 3x dollars.\nThe total number of adult tickets is 2 because a family has 2 parents.\nThe cost of the adult tickets is 2(x+6) dollars.\nThe total cost of all the tickets is 77 dollars.\nThe expression representing the total cost of the tickets is 3x+2(x+6)=77\nSimplifying the expression gives us 3x+2x+12=77\nCombining like terms gives us 5x+12=77\nSubtracting 12 from both sides gives us 5x=65\nDividing both sides by 5 gives us x=13\nThe cost of an adult ticket is x+6 = 13+6 = $19."}]}
{"conversations": [{"from": "human", "value": "Hannah is at a restaurant. She spends $23 in total on an entree and a dessert. If the entree costs $5 more than the dessert, how much does the entree cost, in dollars?"}, {"from": "gpt", "value": "Let E be the cost of the entree and D be the cost of the dessert. We know that E + D = $23 and E = D + $5.\nSubstituting the second equation into the first equation, we get D + $5 + D = $23\nCombining like terms, we get 2D + $5 = $23\nSubtracting $5 from both sides, we get 2D = $18\nDividing both sides by 2, we get D = $9\nSubstituting D = $9 into the equation E = D + $5, we get E = $9 + $5 = $14."}]}

```

**Comment by nuoma** [comment]
the issue seems to be my SFT data.
