### ISSUE TITLE
There is no direct support for loading those old adapters. One thing you could do which may work: Download the repo to a  local folder, edit the `adapter_config.json` and remove the line `"enable_lora": null,`, then try to load the model from your local folder instead of from HF. If that works, you can create your own HF repo and upload the "fixed" version there for the future.

### ISSUE THREAD

**Issue by Clement-Lelievre** [huggingface/peft#1337]
**Support loading older LoRAs planned?**

**System Info**
peft==0.7.0 (also tried with all versions from 0.2.0 to the current latest peft-0.7.2.dev0)
accelerate==0.25.0
transformers==4.36.1

Python 3.10.12
CUDA Version: 12.2
Ubuntu 20.04.6

_dreamsim==0.1.3_

**Who can help?**

@BenjaminBossan ?

**Information**

My own script

**Task**

My own task or dataset (give details below)

We are trying to use the [dreamsim](https://github.com/ssundaram21/dreamsim) model with the newest PEFT, but it is likely that this issue more generally arises in a variety of cases involving older LoRAs.

              There is no direct support for loading those old adapters. One thing you could do which may work: Download the repo to a  local folder, edit the `adapter_config.json` and remove the line `"enable_lora": null,`, then try to load the model from your local folder instead of from HF. If that works, you can create your own HF repo and upload the "fixed" version there for the future.

_Originally posted by @BenjaminBossan in https://github.com/huggingface/peft/issues/1087#issuecomment-1798527118_
            

**MRE**

```python
from dreamsim import dreamsim

dreamsim()
```

results in the below error:

```
/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/home/ubuntu/Developments/github.com/scenario-labs/phoenix/toto.py", line 3, in <module>
    dreamsim()
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/dreamsim/model.py", line 225, in dreamsim
    extractor.model = PeftModel.from_pretrained(extractor.model, load_dir).to(device)
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/peft/peft_model.py", line 323, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/peft/config.py", line 137, in from_pretrained
    config = config_cls(**kwargs)
TypeError: LoraConfig.__init__() got an unexpected keyword argument 'enable_lora'
```

The above proposed fix does not work for us; locating `adapter_config.json` and dropping the `enable_lora` data produces the same error, this time with the key `merge_weights `. Dropping this key leads to a shape mismatch error.

**Expected behavior**

Model weights should load.

**Comment by BenjaminBossan** [comment]
Could you please paste the full error when encountering this shape mismatch error?

**Comment by Clement-Lelievre** [comment]
(note that across PEFT releases, errors differ but they mostly seem to be variations around this mismatch problem).
Sure here you go below (models from cache but after download leads to the same error):

```
Using cached ./models
Using cache found in ./models/facebookresearch_dino_main
/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/home/ubuntu/Developments/github.com/scenario-labs/phoenix/toto.py", line 3, in <module>
    dreamsim()
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/dreamsim/model.py", line 225, in dreamsim
    extractor.model = PeftModel.from_pretrained(extractor.model, load_dir).to(device)
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/peft/peft_model.py", line 351, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/peft/peft_model.py", line 691, in load_adapter
    load_result = set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 201, in set_peft_model_state_dict
    load_result = model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/ubuntu/anaconda3/envs/train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModel:
        size mismatch for base_model.model.base_model.model.model.blocks.0.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.0.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.1.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.1.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.2.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.2.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.3.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.3.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.4.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.4.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.5.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.5.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.6.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.6.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.7.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.7.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.8.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.8.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.9.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.9.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.10.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.10.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.model.blocks.11.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.model.blocks.11.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.0.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.0.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.1.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.1.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.2.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.2.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.3.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.3.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.4.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.4.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.5.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.5.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.6.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.6.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.7.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.7.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.8.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.8.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.9.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.9.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.10.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.10.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
        size mismatch for base_model.model.base_model.model.blocks.11.attn.qkv.lora_A.default.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([16, 768]).
        size mismatch for base_model.model.base_model.model.blocks.11.attn.qkv.lora_B.default.weight: copying a param with shape torch.Size([1536, 16, 1]) from checkpoint, the shape in current model is torch.Size([2304, 16]).
```

**Comment by BenjaminBossan** [comment]
Thanks for the details, I could replicate the error. Unfortunately, I don't think this error can be fixed. This lib uses a very early implementation of PEFT that had another [LoRA layer type](https://github.com/huggingface/peft/blob/v0.1.0/src/peft/tuners/lora.py#L285) that has long since been dropped. The solution would be to either stay with PEFT v0.1 or to train a new LoRA adapter using a more modern PEFT version.

**Comment by Clement-Lelievre** [comment]
arf bad news, thanks for your quick reply!

**Comment by BenjaminBossan** [comment]
You're welcome. I agree it's not nice, hopefully we can avoid these types of breakages in the future (we are much more careful now).

Regarding dreamsim, the development seems to have stalled lately, not sure if you can entice them to update PEFT and re-train the adapters.

I'll close the issue for the time being. Fee free to re-open if something new comes up.

**Comment by stephanie-fu** [comment]
Hi there, dreamsim maintainer here - we'd be happy to update but want to check with PEFT devs about the required steps. Is the only way to support the newest version of PEFT to re-train the tuned layers with the same parameters?

**Comment by BenjaminBossan** [comment]
> Is the only way to support the newest version of PEFT to re-train the tuned layers with the same parameters?

IIUC, that's the case unfortunately. But I joined this project after those changes were made, so don't have the full context. Maybe @pacman100 or @younesbelkada can add something here.
