### ISSUE TITLE
Missing Keys when loading checkpoints using deepspeed and HuggingFace Trainer

### ISSUE THREAD

**Issue by nathan-az** [huggingface/peft#1395]
### System Info

From `transformers-cli env`
```
- `transformers` version: 4.37.0
- Platform: Linux-6.2.0-1017-aws-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.23.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.2+cu121 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes
```
Deepspeed version: 0.13.1
Peft version: 0.7.1

### Who can help?

@pacman100 @younesbelkada @sayakpaul 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Apologies if this belongs in the `transformers` or `deepspeed` repo, but this issue appears to be contained to Peft models (I have no issues with full parameter tuning).

I am using a modified version of the SFT script from the [alignment handbook](https://github.com/huggingface/alignment-handbook). Training is taking place in a multi-GPU, multi-node setup using `deepspeed` via accelerate using `pdsh`.

In short, this appears to occur when using `load_best_model_at_end` with a PEFT model during training. 

Cleaned stdout:
```
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/training/alignment-handbook/scripts/run_sft.py", line 209, in <module>
    main()
  File "/local_disk0/.ephemeral_nfs/training/alignment-handbook/scripts/run_sft.py", line 164, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/databricks/python3/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 315, in train
    output = super().train(*args, **kwargs)
  File "/databricks/python3/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/databricks/python3/lib/python3.10/site-packages/transformers/trainer.py", line 1972, in _inner_training_loop
    self._load_best_model()
  File "/databricks/python3/lib/python3.10/site-packages/transformers/trainer.py", line 2167, in _load_best_model
    deepspeed_load_checkpoint(self.model_wrapped, self.state.best_model_checkpoint)
  File "/databricks/python3/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 402, in deepspeed_load_checkpoint
    load_path, _ = deepspeed_engine.load_checkpoint(
  File "/databricks/python3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2740, in load_checkpoint
    load_path, client_states = self._load_checkpoint(load_dir,
  File "/databricks/python3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2825, in _load_checkpoint
    self.load_module_state_dict(checkpoint=checkpoint,
  File "/databricks/python3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2603, in load_module_state_dict
    self.module.load_state_dict(
  File "/databricks/python3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	Missing key(s) in state_dict: "base_model.model.model.embed_tokens.weight", "base_model.model.model.layers.0.self_attn.q_proj.base_layer.weight", 
```

For brevity I have not included all the missing keys, but the error lists every key in the model, except the PEFT ones (i.e. none of the lora keys). My guess is that when saving the checkpoints, the optimiser states and parameters are only saved for the LoRA layers, but the trainer is looking for all parameters when loading the checkpoint.

My question is mostly around whether this is intended behaviour/unsupported at this point, or whether I have done something wrong.

The model is loaded without a `device_map` passed since I believe `deepspeed` handles that. Other than that, here are (I think) the relevant config details:
```yaml
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- up_proj
- down_proj
- gate_proj

load_in_4bit: true
bnb_4bit_quant_type: nf4
use_bnb_nested_quant: true

gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

load_best_model_at_end: true
optim: paged_adamw_8bit
output_dir: /local_disk0/hf/outputs
overwrite_output_dir: true
resume_from_checkpoint: false
save_on_each_node: true
save_only_model: false
save_steps: 1
save_strategy: "epoch"
save_total_limit: 3
```
Please note that the `output_dir` is a common path used by each node, but does NOT refer to a shared filesystem/NFS (i.e. files are saved to the same path on each node, on different filesystems).

Accelerate:
```yaml
deepspeed_config:
  deepspeed_multinode_launcher: pdsh
  deepspeed_hostfile: {TRAIN_DIR}/hostfile
  deepspeed_config_file: {DS_CONFIG}
  zero3_init_flag: true
distributed_type: DEEPSPEED
```

Deepspeed: I am using zero3 for model without any offloading (parameter or optimiser), with `"stage3_gather_16bit_weights_on_model_save": True`. 

I can provide more details on any of the config items or code if needed. Note that all training is handled by the SFTTrainer, passing in model kwargs, a peft config, and trainer args.

### Expected behavior

I expect the checkpoints to be able to be loaded and attached to the base model so training can continue.

**Comment by nathan-az** [comment]
Closing, looks like this is resolved by https://github.com/huggingface/transformers/pull/28746/files!
