### ISSUE TITLE
loftq example non-functional - assert absmax is not None and out is not None

### ISSUE THREAD

**Issue by winglian** [huggingface/peft#1405]
### System Info

python 3.10

# pip list | grep -e peft -e transformers -e torch -e bitsandbytes -e accelerate
accelerate                0.26.1
bitsandbytes              0.42.0
peft                      0.7.1
torch                     2.1.2+cu118
transformers              4.37.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

following the example in https://huggingface.co/docs/peft/developer_guides/quantization#loftq-initialization (minus the syntax errors)

```
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux                                                                                                                            
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import AutoModelForCausalLM                                                           
>>> from peft import LoftQConfig, LoraConfig, get_peft_model                                                        
>>> model = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-v0.1")                   
Loading checkpoint shards: 100%|________________________________________________________________________________________________________________________________| 2/2 [00:08<00:00,  4.21s/it]
>>> loftq_config = LoftQConfig(loftq_bits=4)                                                                                  
>>> lora_config = LoraConfig(                                                                  
...     init_lora_weights="loftq",                                                                                                                                                            
...     loftq_config=loftq_config,                                                             
...     r=16,                                                                                                                                                                                 
...     lora_alpha=8,                                                                          
...     target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],                                                                                                                              
...     lora_dropout=0.05,       
...     bias="none",                                                                                                                                                                          
...      task_type="CAUSAL_LM"                                                                 
... )                                                                                                                                                                                         
>>> model = get_peft_model(model, lora_config)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/mapping.py", line 133, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/peft_model.py", line 1043, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/peft_model.py", line 125, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 90, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 247, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 202, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 322, in _create_new_module
    new_module = Linear(target, adapter_name, **kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 267, in __init__
    self.update_layer(adapter_name, r, lora_alpha, lora_dropout, init_lora_weights)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 92, in update_layer
    self.loftq_init(adapter_name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 200, in loftq_init
    qweight, lora_A, lora_B = loftq_init(weight, **kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/peft/utils/loftq_utils.py", line 213, in loftq_init
    dequantized_weight = bnb.functional.dequantize_4bit(qweight.data, qweight.quant_state)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1012, in dequantize_4bit
    assert absmax is not None and out is not None
AssertionError
```

### Expected behavior

model to load w/o errors

**Comment by Az0nik** [comment]
Maby just fuck lora?

**Comment by winglian** [comment]
works on main. sorry!

**Comment by Az0nik** [comment]
> works on main. sorry!

Im alredy in, dont wory. Soon finish.

**Comment by YingChR** [comment]
I encountered the same error when using QDoRA. How did you solve it?

**Comment by BenjaminBossan** [comment]
> I encountered the same error when using QDoRA. How did you solve it?

Could you please share what package versions you're using and the code that leads to the error?

**Comment by YingChR** [comment]
> > I encountered the same error when using QDoRA. How did you solve it?
> 
> Could you please share what package versions you're using and the code that leads to the error?

Thank you for your reminder. I have identified the problem. In the previous environment, I did not update the bitsandbyte package, which resulted in the error message "assert absmax is not None and out is not None". Now, I have updated the bitsandbyte and solved the problem.
