### ISSUE TITLE
Connection to huggingface.co timed out when merging Qwen model

### ISSUE THREAD

**Issue by AnYiz** [huggingface/peft#1478]
Why do I still need to connect to huggingface.co when all my model files are local? Is there a way to skip the connection? Even when I use a proxy, the connection still times out
peft ==0.8.2
 ```
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [03:07<00:00, 23.45s/it]
Traceback (most recent call last):
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request    
    self._validate_conn(conn)
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002BB7D9BC100>, 'Connection to huggingface.co timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /output_qwen_chat/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BB7D9BC100>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path       
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code      
    exec(code, run_globals)
  File "d:\xin\text.py", line 151, in <module>
    model = AutoPeftModelForCausalLM.from_pretrained(
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\peft\auto.py", line 115, in from_pretrained
    tokenizer_exists = file_exists(
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub\hf_api.py", line 2219, in file_exists
    get_hf_file_metadata(url, token=token)
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub\file_download.py", line 1624, in get_hf_file_metadata
    r = _request_wrapper(
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub\file_download.py", line 402, in _request_wrapper
    response = _request_wrapper(
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub\file_download.py", line 425, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "E:\Program\Anaconda\envs\pytorch-gpu\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /output_qwen_chat/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BB7D9BC100>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: e3217542-52b2-43bc-bd8d-411412c5d92e)')
```

**Comment by younesbelkada** [comment]
Hi @AnYiz 
Thanks for the issue! Can you share the full snippet you are using? 
https://github.com/huggingface/peft/pull/1454 being merged, you can use PEFT from source + call your script with `HF_HUB_OFFLINE=1 xxx.py` and there shouldn't be any HTTP call at all
