### ISSUE TITLE
Some problems arise when finetune large language models

### ISSUE THREAD

**Issue by zhengzehao123** [huggingface/peft#1513]
Hello, I have recently been trying to progressively fine-tune a large language model.

First, I attempted to use the "lora on lora" fine-tuning mode, where after fine-tuning the model with lora, I merged the generated adapter parameters with the original model using merge_and_unload(). Then, I repeated lora process on the merged model. However, I encountered an issue where the GPU memory usage increased significantly during the second fine-tuning. The first time it used 16G, but the second time, the 24G GPU reported "out of memory",but the model size has not changed much compared to before.. The merged model can still perform inference normally ,and this work is based on Qwen. Is this a normal situation? Can you provide the reason and solution?

Also, can I merge the adapter parameters generated by Qlora with the original model and then perform Qlora again on the merged model? Will I encounter the same issue as with the above lora? If merging is possible, which functions should I use for merging?

If I want to fine-tune a large language model multiple times, do you have any other methods or relevant suggestions apart from the above approach?

Looking forward to your reply

**Comment by BenjaminBossan** [comment]
> First, I attempted to use the "lora on lora" fine-tuning mode, where after fine-tuning the model with lora, I merged the generated adapter parameters with the original model using merge_and_unload(). Then, I repeated lora process on the merged model. However, I encountered an issue where the GPU memory usage increased significantly during the second fine-tuning. The first time it used 16G, but the second time, the 24G GPU reported "out of memory",but the model size has not changed much compared to before.. The merged model can still perform inference normally ,and this work is based on Qwen. Is this a normal situation? Can you provide the reason and solution?

This should indeed not happen, since, as you correctly observed, after `merge_and_unload` the model should be no different to the base model when it comes to size. Is it possible that you used different settings or different PEFT versions between the 1st and the 2nd step? Ideally, could you provide a script to reproduce the issue (training shouldn't be necessary to show this).

> Also, can I merge the adapter parameters generated by Qlora with the original model and then perform Qlora again on the merged model?

Yes, that should work.

**Comment by zhengzehao123** [comment]
> > First, I attempted to use the "lora on lora" fine-tuning mode, where after fine-tuning the model with lora, I merged the generated adapter parameters with the original model using merge_and_unload(). Then, I repeated lora process on the merged model. However, I encountered an issue where the GPU memory usage increased significantly during the second fine-tuning. The first time it used 16G, but the second time, the 24G GPU reported "out of memory",but the model size has not changed much compared to before.. The merged model can still perform inference normally ,and this work is based on Qwen. Is this a normal situation? Can you provide the reason and solution?
> 
> This should indeed not happen, since, as you correctly observed, after `merge_and_unload` the model should be no different to the base model when it comes to size. Is it possible that you used different settings or different PEFT versions between the 1st and the 2nd step? Ideally, could you provide a script to reproduce the issue (training shouldn't be necessary to show this).
> 
> > Also, can I merge the adapter parameters generated by Qlora with the original model and then perform Qlora again on the merged model?
> 
> Yes, that should work.

Thank you for your reply

I tried to fine-tune the model using the qlora on qlora method, but encountered an error when using the merge_and_unload() function to merge the models.Is it because I used the wrong method or it is impossible to merge the quantized models?

The following is the code that is run and the specific information about the error reported.
**code：**
```
model = AutoPeftModelForCausalLM.from_pretrained(
        "/root/zhengzh/Bert-TextClassification/Qwen/output_qwen", # path to the output directory
        device_map="auto",
        trust_remote_code=True
    ).eval()
    merged_model = model.merge_and_unload()
# max_shard_size and safe serialization are not necessary. 
# They respectively work for sharding checkpoint and save the model to safetensors
    merged_model.save_pretrained("/root/zhengzh/Bert-TextClassification/Qwen/merged_model", max_shard_size="2048MB", safe_serialization=True)
    tokenizer = AutoTokenizer.from_pretrained(
        "/root/zhengzh/Bert-TextClassification/Qwen/output_qwen", # path to the output directory
        trust_remote_code=True
    )
    tokenizer.save_pretrained("/root/zhengzh/Bert-TextClassification/Qwen/merged_model")
```
 **error report：**
```
 Traceback (most recent call last):
  File "/root/zhengzh/Bert-TextClassification/Qwen/dis_test.py", line 196, in <module>
    merged_model = model.merge_and_unload()
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 719, in merge_and_unload
    return self._unload_and_optionally_merge(
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 438, in _unload_and_optionally_merge
    raise ValueError("Cannot merge LORA layers when the model is gptq quantized")
ValueError: Cannot merge LORA layers when the model is gptq quantized
```

**Comment by zhengzehao123** [comment]
> > First, I attempted to use the "lora on lora" fine-tuning mode, where after fine-tuning the model with lora, I merged the generated adapter parameters with the original model using merge_and_unload(). Then, I repeated lora process on the merged model. However, I encountered an issue where the GPU memory usage increased significantly during the second fine-tuning. The first time it used 16G, but the second time, the 24G GPU reported "out of memory",but the model size has not changed much compared to before.. The merged model can still perform inference normally ,and this work is based on Qwen. Is this a normal situation? Can you provide the reason and solution?
> 
> This should indeed not happen, since, as you correctly observed, after `merge_and_unload` the model should be no different to the base model when it comes to size. Is it possible that you used different settings or different PEFT versions between the 1st and the 2nd step? Ideally, could you provide a script to reproduce the issue (training shouldn't be necessary to show this).
> 
> > Also, can I merge the adapter parameters generated by Qlora with the original model and then perform Qlora again on the merged model?
> 
> Yes, that should work.

Regarding the problem of OOM when the lora on lora method is executed for the second time, the following is the relevant script

**finetune.py**
```
# This code is based on the revised code from fastchat based on tatsu-lab/stanford_alpaca.
import os
os.environ["CUDA_DEVICE_MAX_CONNECTIONS"] = "1"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
from dataclasses import dataclass, field
import json
import math
import logging

from typing import Dict, Optional, List
import torch
from torch.utils.data import Dataset
from deepspeed import zero
from deepspeed.runtime.zero.partition_parameters import ZeroParamStatus
import transformers
from transformers import Trainer, GPTQConfig
from transformers.integrations import deepspeed
from transformers.trainer_pt_utils import LabelSmoother
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from accelerate.utils import DistributedType
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer


IGNORE_TOKEN_ID = LabelSmoother.ignore_index


@dataclass
class ModelArguments:
    model_name_or_path: Optional[str] = field(default="Qwen/Qwen-7B")


@dataclass
class DataArguments:
    data_path: str = field(
        default=None, metadata={"help": "Path to the training data."}
    )
    eval_data_path: str = field(
        default=None, metadata={"help": "Path to the evaluation data."}
    )
    lazy_preprocess: bool = False


@dataclass
class TrainingArguments(transformers.TrainingArguments):
    cache_dir: Optional[str] = field(default=None)
    optim: str = field(default="adamw_torch")
    model_max_length: int = field(
        default=8192,
        metadata={
            "help": "Maximum sequence length. Sequences will be right padded (and possibly truncated)."
        },
    )
    use_lora: bool = False


@dataclass
class LoraArguments:
    lora_r: int = 64
    lora_alpha: int = 16
    lora_dropout: float = 0.05
    lora_target_modules: List[str] = field(
        default_factory=lambda: ["c_attn", "c_proj", "w1", "w2"]
    )
    lora_weight_path: str = ""
    lora_bias: str = "none"
    q_lora: bool = False


def maybe_zero_3(param):
    if hasattr(param, "ds_id"):
        assert param.ds_status == ZeroParamStatus.NOT_AVAILABLE
        with zero.GatheredParameters([param]):
            param = param.data.detach().cpu().clone()
    else:
        param = param.detach().cpu().clone()
    return param


# Borrowed from peft.utils.get_peft_model_state_dict
def get_peft_state_maybe_zero_3(named_params, bias):
    if bias == "none":
        to_return = {k: t for k, t in named_params if "lora_" in k}
    elif bias == "all":
        to_return = {k: t for k, t in named_params if "lora_" in k or "bias" in k}
    elif bias == "lora_only":
        to_return = {}
        maybe_lora_bias = {}
        lora_bias_names = set()
        for k, t in named_params:
            if "lora_" in k:
                to_return[k] = t
                bias_name = k.split("lora_")[0] + "bias"
                lora_bias_names.add(bias_name)
            elif "bias" in k:
                maybe_lora_bias[k] = t
        for k, t in maybe_lora_bias:
            if bias_name in lora_bias_names:
                to_return[bias_name] = t
    else:
        raise NotImplementedError
    to_return = {k: maybe_zero_3(v) for k, v in to_return.items()}
    return to_return


local_rank = None

def rank0_print(*args):
    if local_rank == 0:
        print(*args)


def safe_save_model_for_hf_trainer(trainer: transformers.Trainer, output_dir: str, bias="none"):
    """Collects the state dict and dump to disk."""
    # check if zero3 mode enabled
    if deepspeed.is_deepspeed_zero3_enabled():
        state_dict = trainer.model_wrapped._zero3_consolidated_16bit_state_dict()
    else:
        if trainer.args.use_lora:
            state_dict = get_peft_state_maybe_zero_3(
                trainer.model.named_parameters(), bias
            )
        else:
            state_dict = trainer.model.state_dict()
    if trainer.args.should_save and trainer.args.local_rank == 0:
        trainer._save(output_dir, state_dict=state_dict)


def preprocess(
    sources,
    tokenizer: transformers.PreTrainedTokenizer,
    max_len: int,
    system_message: str = "You are a helpful assistant."
) -> Dict:
    roles = {"user": "<|im_start|>user", "assistant": "<|im_start|>assistant"}

    im_start = tokenizer.im_start_id
    im_end = tokenizer.im_end_id
    nl_tokens = tokenizer('\n').input_ids
    _system = tokenizer('system').input_ids + nl_tokens
    _user = tokenizer('user').input_ids + nl_tokens
    _assistant = tokenizer('assistant').input_ids + nl_tokens

    # Apply prompt templates
    input_ids, targets = [], []
    for i, source in enumerate(sources):
        if roles[source[0]["from"]] != roles["user"]:
            source = source[1:]

        input_id, target = [], []
        system = [im_start] + _system + tokenizer(system_message).input_ids + [im_end] + nl_tokens
        input_id += system
        target += [im_start] + [IGNORE_TOKEN_ID] * (len(system)-3) + [im_end] + nl_tokens
        assert len(input_id) == len(target)
        for j, sentence in enumerate(source):
            role = roles[sentence["from"]]
            _input_id = tokenizer(role).input_ids + nl_tokens + \
                tokenizer(sentence["value"]).input_ids + [im_end] + nl_tokens
            input_id += _input_id
            if role == '<|im_start|>user':
                _target = [im_start] + [IGNORE_TOKEN_ID] * (len(_input_id)-3) + [im_end] + nl_tokens
            elif role == '<|im_start|>assistant':
                _target = [im_start] + [IGNORE_TOKEN_ID] * len(tokenizer(role).input_ids) + \
                    _input_id[len(tokenizer(role).input_ids)+1:-2] + [im_end] + nl_tokens
            else:
                raise NotImplementedError
            target += _target
        assert len(input_id) == len(target)
        input_id += [tokenizer.pad_token_id] * (max_len - len(input_id))
        target += [IGNORE_TOKEN_ID] * (max_len - len(target))
        input_ids.append(input_id[:max_len])
        targets.append(target[:max_len])
    input_ids = torch.tensor(input_ids, dtype=torch.int)
    targets = torch.tensor(targets, dtype=torch.int)

    return dict(
        input_ids=input_ids,
        labels=targets,
        attention_mask=input_ids.ne(tokenizer.pad_token_id),
    )


class SupervisedDataset(Dataset):
    """Dataset for supervised fine-tuning."""

    def __init__(self, raw_data, tokenizer: transformers.PreTrainedTokenizer, max_len: int):
        super(SupervisedDataset, self).__init__()

        rank0_print("Formatting inputs...")
        sources = [example["conversations"] for example in raw_data]
        data_dict = preprocess(sources, tokenizer, max_len)

        self.input_ids = data_dict["input_ids"]
        self.labels = data_dict["labels"]
        self.attention_mask = data_dict["attention_mask"]

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, i) -> Dict[str, torch.Tensor]:
        return dict(
            input_ids=self.input_ids[i],
            labels=self.labels[i],
            attention_mask=self.attention_mask[i],
        )


class LazySupervisedDataset(Dataset):
    """Dataset for supervised fine-tuning."""

    def __init__(self, raw_data, tokenizer: transformers.PreTrainedTokenizer, max_len: int):
        super(LazySupervisedDataset, self).__init__()
        self.tokenizer = tokenizer
        self.max_len = max_len

        rank0_print("Formatting inputs...Skip in lazy mode")
        self.tokenizer = tokenizer
        self.raw_data = raw_data
        self.cached_data_dict = {}

    def __len__(self):
        return len(self.raw_data)

    def __getitem__(self, i) -> Dict[str, torch.Tensor]:
        if i in self.cached_data_dict:
            return self.cached_data_dict[i]

        ret = preprocess([self.raw_data[i]["conversations"]], self.tokenizer, self.max_len)
        ret = dict(
            input_ids=ret["input_ids"][0],
            labels=ret["labels"][0],
            attention_mask=ret["attention_mask"][0],
        )
        self.cached_data_dict[i] = ret

        return ret


def make_supervised_data_module(
    tokenizer: transformers.PreTrainedTokenizer, data_args, max_len,
) -> Dict:
    """Make dataset and collator for supervised fine-tuning."""
    dataset_cls = (
        LazySupervisedDataset if data_args.lazy_preprocess else SupervisedDataset
    )
    rank0_print("Loading data...")

    train_json = json.load(open(data_args.data_path, "r"))
    train_dataset = dataset_cls(train_json, tokenizer=tokenizer, max_len=max_len)
    #print("train_dataset")
    #n=0
    #for inputs in train_dataset:
    #        print(n)
    #        print(inputs)
    #        n=n+1
    #print("train_datasetend")

    if data_args.eval_data_path:
        eval_json = json.load(open(data_args.eval_data_path, "r"))
        eval_dataset = dataset_cls(eval_json, tokenizer=tokenizer, max_len=max_len)
    else:
        eval_dataset = None

    return dict(train_dataset=train_dataset, eval_dataset=eval_dataset)


def LLM_train(train_args,ready_loss,flag):
    global local_rank

    parser = transformers.HfArgumentParser(
        (ModelArguments, DataArguments, TrainingArguments, LoraArguments)
    )
    (
        model_args,
        data_args,
        training_args,
        lora_args,
    ) = parser.parse_args_into_dataclasses(list(train_args))

    # This serves for single-gpu qlora.
    if getattr(training_args, 'deepspeed', None) and int(os.environ.get("WORLD_SIZE", 1))==1:
        training_args.distributed_state.distributed_type = DistributedType.DEEPSPEED

    local_rank = training_args.local_rank

    device_map = None
    world_size = int(os.environ.get("WORLD_SIZE", 1))
    ddp = world_size != 1
    if lora_args.q_lora:
        device_map = {"": int(os.environ.get("LOCAL_RANK") or 0)} if ddp else "auto"
        if len(training_args.fsdp) > 0 or deepspeed.is_deepspeed_zero3_enabled():
            logging.warning(
                "FSDP or ZeRO3 are incompatible with QLoRA."
            )

    # Set RoPE scaling factor
    is_chat_model = 'chat' in model_args.model_name_or_path.lower()
    if (
            training_args.use_lora
            and not lora_args.q_lora
            and deepspeed.is_deepspeed_zero3_enabled()
            and not is_chat_model
    ):
        raise RuntimeError("ZeRO3 is incompatible with LoRA when finetuning on base model.")

    model_load_kwargs = {
        'low_cpu_mem_usage': not deepspeed.is_deepspeed_zero3_enabled(),
    }


    # Load model and tokenizer
    
    if flag==1:

        config = transformers.AutoConfig.from_pretrained(
            model_args.model_name_or_path,
            cache_dir=training_args.cache_dir,
            trust_remote_code=True,
        )
        config.use_cache = False
    
        model = transformers.AutoModelForCausalLM.from_pretrained(
            model_args.model_name_or_path,
            config=config,
            cache_dir=training_args.cache_dir,
            device_map=device_map,
            trust_remote_code=True,
            quantization_config=GPTQConfig(
                bits=4, disable_exllama=True
            )
            if training_args.use_lora and lora_args.q_lora
            else None,
        )
    else:
        #model_args.model_name_or_path=training_args.output_dir
        config = transformers.AutoConfig.from_pretrained(
            training_args.output_dir,
            cache_dir=training_args.cache_dir,
            trust_remote_code=True,
        )
        config.use_cache = False
    
        model = AutoPeftModelForCausalLM.from_pretrained(
                training_args.output_dir, # path to the output directory
                device_map=device_map,
                trust_remote_code=True
            ).eval()
    tokenizer = transformers.AutoTokenizer.from_pretrained(
        model_args.model_name_or_path,
        cache_dir=training_args.cache_dir,
        model_max_length=training_args.model_max_length,
        padding_side="right",
        use_fast=False,
        trust_remote_code=True,
    )
    tokenizer.pad_token_id = tokenizer.eod_id

    if training_args.use_lora:
        if lora_args.q_lora or 'chat' in model_args.model_name_or_path.lower():
            modules_to_save = None
        else:
            modules_to_save = ["wte", "lm_head"]
        lora_config = LoraConfig(
            r=lora_args.lora_r,
            lora_alpha=lora_args.lora_alpha,
            target_modules=lora_args.lora_target_modules,
            lora_dropout=lora_args.lora_dropout,
            bias=lora_args.lora_bias,
            task_type="CAUSAL_LM",
            modules_to_save=modules_to_save  # This argument serves for adding new tokens.
        )
        if lora_args.q_lora:
            model = prepare_model_for_kbit_training(
                model, use_gradient_checkpointing=training_args.gradient_checkpointing
            )

        model = get_peft_model(model, lora_config)

        # Print peft trainable params
        model.print_trainable_parameters()

        if training_args.gradient_checkpointing:
            model.enable_input_require_grads()

    # Load data
    data_module = make_supervised_data_module(
        tokenizer=tokenizer, data_args=data_args, max_len=training_args.model_max_length
    )

    # Start trainner
    trainer = Trainer(
        model=model, tokenizer=tokenizer, args=training_args, LLM_losses=ready_loss ,**data_module
    )

    trainer.train()
    trainer.save_state()

    safe_save_model_for_hf_trainer(trainer=trainer, output_dir=training_args.output_dir, bias=lora_args.lora_bias)
    print("training over")
    
    
    


if __name__ == "__main__":

    args = ("--model_name_or_path", "/root/zhengzh/Bert-TextClassification/Qwen/Qwen-7B-Chat","--data_path","/root/zhengzh/Bert-TextClassification/Qwen/finetune/traindata.json","--fp16","True","--output_dir","/root/zhengzh/Bert-TextClassification/Qwen/output_qwen","--num_train_epochs","5","--per_device_train_batch_size","1","--per_device_eval_batch_size","1","--gradient_accumulation_steps","1","--evaluation_strategy","no","--save_strategy","steps","--save_steps","1000","--save_total_limit","10","--learning_rate","3e-4","--weight_decay","0.1","--adam_beta2","0.95","--warmup_ratio","0.01","--lr_scheduler_type","cosine","--logging_steps","1","--report_to","none","--model_max_length","512","--lazy_preprocess","True","--gradient_checkpointing","True","--use_lora","True","--deepspeed","/root/zhengzh/Bert-TextClassification/Qwen/finetune/ds_config_zero2.json")
   
    
    testlist=[]
    testlist.append(torch.tensor(1.0, dtype=torch.float32))
    testlist.append(torch.tensor(2.0, dtype=torch.float32))
    testlist.append(torch.tensor(3.0, dtype=torch.float32))
    testlist.append(torch.tensor(4.0, dtype=torch.float32))
    testlist.append(torch.tensor(5.0, dtype=torch.float32))
    LLM_train(args,testlist,1)

```

**main script that run** 


```
import json
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer


    

def run_cmd( cmd_str='', echo_print=1):
    
    from subprocess import run
    if echo_print == 1:
        print('\n cmd="{}"'.format(cmd_str))
    run(cmd_str, shell=True)
    
if __name__ == "__main__":
    run_cmd('python /root/zhengzh/Bert-TextClassification/Qwen/finetune.py')
        
    model = AutoPeftModelForCausalLM.from_pretrained(
        "/root/zhengzh/Bert-TextClassification/Qwen/output_qwen", # path to the output directory
        device_map="auto",
        trust_remote_code=True
    ).eval()
    merged_model = model.merge_and_unload()
# max_shard_size and safe serialization are not necessary. 
# They respectively work for sharding checkpoint and save the model to safetensors
    merged_model.save_pretrained("/root/zhengzh/Bert-TextClassification/Qwen/merged_model", max_shard_size="2048MB", safe_serialization=True)
    tokenizer = AutoTokenizer.from_pretrained(
        "/root/zhengzh/Bert-TextClassification/Qwen/output_qwen", # path to the output directory
        trust_remote_code=True
    )
    tokenizer.save_pretrained("/root/zhengzh/Bert-TextClassification/Qwen/merged_model")
```
The first time I used lora to finetune the model, I ran the main script. The second time I used lora to finetune the model, I modified the model_name_or_path of the args variable in finetune.py to "/root/zhengzh/Bert-TextClassification/Qwen/merged_model ", and then an out of memory error was reported.

**Comment by BenjaminBossan** [comment]
Regarding this error:

> ValueError: Cannot merge LORA layers when the model is gptq quantized

As the message states, GPTQ does not support merging of LoRA weights. Could you please try bitsandbytes, which does support merging?

Regarding the other issue with running two fine-tuning steps in a row: This is a very big script and pinpointing where exactly the issue could be is very difficult.

I tried to condense the issue down to see if I can reproduce it. Here is the script:

```python
# issue-1513.py
import sys
import torch
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
from tqdm.auto import tqdm

def train(path):
    model = AutoModelForCausalLM.from_pretrained(
        path,
        quantization_config=BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4"),
    )
    model = prepare_model_for_kbit_training(model)

    config = LoraConfig(task_type="CAUSAL_LM", target_modules="all-linear")
    model = get_peft_model(model, config)

    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-5)
    input_ids = torch.randint(0, 10000, (1, 192)).cuda()
    attention_mask = torch.randint(1, 2, (1, 192)).cuda()
    for _ in tqdm(range(100), total=100):
        res = model(input_ids=input_ids, attention_mask=attention_mask, labels=input_ids)
        res.loss.backward()
        optimizer.step()
        optimizer.zero_grad()

    model = model.merge_and_unload()
    save_path = path.replace("/", "-") + "-lora" 
    model.save_pretrained(save_path)
    print(f"saved model in {save_path}")

if __name__ == '__main__':
    arg = sys.argv[1]
    train(arg)
```

This is a very simple training script for a small Qwen model with bnb 4 bit quantization.

The first time around, I call it using `python issue-1513.py "Qwen/Qwen1.5-0.5B"`. This performs fine-tuning on the 4bit quantized Qwen1.5-0.5B model, merges the LoRA weights, and stores the whole checkpoint in the local folder `Qwen-Qwen1.5-0.5B-lora/`. During training, I observe 2959 MiB of GPU memory being used.

After this, I call the script `python issue-1513.py Qwen-Qwen1.5-0.5B-lora/`. This loads the local model and then applies the exact training steps. Again, I observe 2959 MiB of GPU memory. This means that in principle, this works exactly as expected. Could you please try my script and see if you can replicate? It should only take a few minutes.

I'm not sure what the difference between your script and mine is that causes the difference. Did you check that after the first run, GPU memory is completely cleared?

**Comment by zhengzehao123** [comment]
> Regarding this error:
> 
> > ValueError: Cannot merge LORA layers when the model is gptq quantized
> 
> As the message states, GPTQ does not support merging of LoRA weights. Could you please try bitsandbytes, which does support merging?
> 
> Regarding the other issue with running two fine-tuning steps in a row: This is a very big script and pinpointing where exactly the issue could be is very difficult.
> 
> I tried to condense the issue down to see if I can reproduce it. Here is the script:
> 
> ```python
> # issue-1513.py
> import sys
> import torch
> from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
> from transformers import AutoModelForCausalLM, BitsAndBytesConfig
> from tqdm.auto import tqdm
> 
> def train(path):
>     model = AutoModelForCausalLM.from_pretrained(
>         path,
>         quantization_config=BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4"),
>     )
>     model = prepare_model_for_kbit_training(model)
> 
>     config = LoraConfig(task_type="CAUSAL_LM", target_modules="all-linear")
>     model = get_peft_model(model, config)
> 
>     optimizer = torch.optim.AdamW(model.parameters(), lr=1e-5)
>     input_ids = torch.randint(0, 10000, (1, 192)).cuda()
>     attention_mask = torch.randint(1, 2, (1, 192)).cuda()
>     for _ in tqdm(range(100), total=100):
>         res = model(input_ids=input_ids, attention_mask=attention_mask, labels=input_ids)
>         res.loss.backward()
>         optimizer.step()
>         optimizer.zero_grad()
> 
>     model = model.merge_and_unload()
>     save_path = path.replace("/", "-") + "-lora" 
>     model.save_pretrained(save_path)
>     print(f"saved model in {save_path}")
> 
> if __name__ == '__main__':
>     arg = sys.argv[1]
>     train(arg)
> ```
> 
> This is a very simple training script for a small Qwen model with bnb 4 bit quantization.
> 
> The first time around, I call it using `python issue-1513.py "Qwen/Qwen1.5-0.5B"`. This performs fine-tuning on the 4bit quantized Qwen1.5-0.5B model, merges the LoRA weights, and stores the whole checkpoint in the local folder `Qwen-Qwen1.5-0.5B-lora/`. During training, I observe 2959 MiB of GPU memory being used.
> 
> After this, I call the script `python issue-1513.py Qwen-Qwen1.5-0.5B-lora/`. This loads the local model and then applies the exact training steps. Again, I observe 2959 MiB of GPU memory. This means that in principle, this works exactly as expected. Could you please try my script and see if you can replicate? It should only take a few minutes.
> 
> I'm not sure what the difference between your script and mine is that causes the difference. Did you check that after the first run, GPU memory is completely cleared?

Thank you for your help. I will try according to your suggestions first. If I find any specific problems in the future, please allow me to ask further questions
