### ISSUE TITLE
cannot load int8/4 model with deepspeed zero3

### ISSUE THREAD

**Issue by mxjyst** [huggingface/peft#1566]
### System Info

--

### Who can help?

@pacman100 @younesbelkada 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Hello, when I tried to run the example scripts[run_peft_qlora_deepspeed_stage3.sh](https://github.com/huggingface/peft/blob/main/examples/sft/run_peft_qlora_deepspeed_stage3.sh), 
I met the following error:

Traceback (most recent call last):
  File "/workspace/xxx/code/train.py", line 161, in <module>
    main(model_args, data_args, training_args)
  File "/workspace/xxx/code/train.py", line 107, in main
    model, tokenizer = create_and_prepare_model(model_args, data_args, training_args)
  File "/workspace/xxx/code/utils.py", line 128, in create_and_prepare_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3926, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 805, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/modeling.py", line 348, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([32000, 4096]) in "weight" (which has shape torch.Size([0])), this look incorrect.

after I comment out the "quantization_config" flag in utils.py:
model = AutoModelForCausalLM.from_pretrained(
            args.model_name_or_path,
            torch_dtype=quant_storage_dtype or torch.float32,
            trust_remote_code=True,
            # quantization_config=bnb_config,
            attn_implementation="flash_attention_2" if args.use_flash_attn else "eager",
        )
it run correctly.

And if I run the script without deepspeed (replace the filrst line with "python train.py" in the run_peft_qlora_deepspeed_stage3.sh), it also run successfully.

It seems that int4/8 quantization didn't be supported by zero3? 
how to reproduce your example script successfully?

Thanks

### Expected behavior

please help me solve this problem.

**Comment by pacman100** [comment]
Please use the main branch of transformers and let us know if that solves the issue.

**Comment by mxjyst** [comment]
I try to use the main branch of transformers, error:
Traceback (most recent call last):
  File "/workspace/xxx/code/train.py", line 7, in <module>
    from trl import SFTTrainer
  File "/usr/local/lib/python3.10/dist-packages/trl/__init__.py", line 5, in <module>
    from .core import set_seed
  File "/usr/local/lib/python3.10/dist-packages/trl/core.py", line 25, in <module>
    from transformers import top_k_top_p_filtering
ImportError: cannot import name 'top_k_top_p_filtering' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)
how to solve this error?

**Comment by younesbelkada** [comment]
@mxjyst please use also the main branch of TRL

**Comment by younesbelkada** [comment]
You can also refer to these scripts from @pacman100 : https://github.com/huggingface/peft/blob/main/examples/sft/

**Comment by mxjyst** [comment]
I can run successfully with the main branch of transformers and trl. Thanks!
