### ISSUE TITLE
Error saving LoRaModel with Wav2vec2forCTC basemodel

### ISSUE THREAD

**Issue by geoffvdr** [huggingface/peft#1569]
Hello,

I can successfully train a LoraModel with Wav2vec2forCTC as basemodel, however the checkpoint saving fails because the basemodel does not implement `get_input_embeddings()`.

Error traceback:
```
Traceback (most recent call last):
2024-03-18T17:21:06.765068910+01:00   File "/project_antwerp/huggingface/transformers/examples/pytorch/speech-recognition/run_speech_recognition_ctc_lora.py", line 937, in <module>
2024-03-18T17:21:06.766590192+01:00     main()
2024-03-18T17:21:06.766764134+01:00   File "/project_antwerp/huggingface/transformers/examples/pytorch/speech-recognition/run_speech_recognition_ctc_lora.py", line 885, in main
2024-03-18T17:21:06.767869279+01:00     train_result = trainer.train(resume_from_checkpoint=checkpoint)
2024-03-18T17:21:06.768053248+01:00                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-18T17:21:06.768077037+01:00   File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 1638, in train
2024-03-18T17:21:06.769346968+01:00     return inner_training_loop(
2024-03-18T17:21:06.769360460+01:00            ^^^^^^^^^^^^^^^^^^^^
2024-03-18T17:21:06.769441083+01:00   File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 2067, in _inner_training_loop
2024-03-18T17:21:06.770920539+01:00     self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
2024-03-18T17:21:06.771129247+01:00   File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 2442, in _maybe_log_save_evaluate
2024-03-18T17:21:06.772635203+01:00     self._save_checkpoint(model, trial, metrics=metrics)
2024-03-18T17:21:06.772781049+01:00   File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 2510, in _save_checkpoint
2024-03-18T17:21:06.774418069+01:00     self.save_model(output_dir, _internal_call=True)
2024-03-18T17:21:06.774522140+01:00   File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 3004, in save_model
2024-03-18T17:21:06.775802263+01:00     self._save(output_dir)
2024-03-18T17:21:06.775847703+01:00   File "/opt/conda/lib/python3.11/site-packages/transformers/trainer.py", line 3079, in _save
2024-03-18T17:21:06.777196431+01:00     self.model.save_pretrained(
2024-03-18T17:21:06.777211289+01:00   File "/opt/conda/lib/python3.11/site-packages/peft/peft_model.py", line 215, in save_pretrained
2024-03-18T17:21:06.777494780+01:00     output_state_dict = get_peft_model_state_dict(
2024-03-18T17:21:06.777514325+01:00                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-18T17:21:06.777525194+01:00   File "/opt/conda/lib/python3.11/site-packages/peft/utils/save_and_load.py", line 176, in get_peft_model_state_dict
2024-03-18T17:21:06.777783613+01:00     for layer in [model.get_input_embeddings(), model.get_output_embeddings()]:
2024-03-18T17:21:06.777873539+01:00                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-18T17:21:06.777915611+01:00   File "/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py", line 1589, in get_input_embeddings
2024-03-18T17:21:06.778471430+01:00     return base_model.get_input_embeddings()
2024-03-18T17:21:06.778617012+01:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-18T17:21:06.778634252+01:00   File "/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py", line 1591, in get_input_embeddings
2024-03-18T17:21:06.779075060+01:00     raise NotImplementedError
``` 

Toy example to reproduce error:
```python
import transformers
from transformers import (
    AutoConfig,
    AutoFeatureExtractor,
    AutoModelForCTC,
    AutoProcessor,
    AutoTokenizer,
    HfArgumentParser,
    Trainer,
    TrainingArguments,
    Wav2Vec2Processor,
    set_seed,
)
from peft import LoraConfig
from peft import get_peft_model

config = AutoConfig.from_pretrained(
        "facebook/mms-1b"
    )
model = AutoModelForCTC.from_pretrained(
        "facebook/mms-1b",
        config=config,
        ignore_mismatched_sizes=True,
    )
peft_kwargs = {
            "lora_alpha": 16,
            "lora_dropout": 0.0,
            "r": 16,
            "bias": "none",
            "target_modules": ["q_proj", "v_proj"],
        }
 peft_config = LoraConfig(**peft_kwargs)
 model = get_peft_model(model, peft_config)
 model.save_pretrained("/project_antwerp/huggingface/exp/mms-1b_lora_nl_cv16/temp/temp4", state_dict=model.state_dict(),save_embedding_layers=True)
``` 

The embedding layers need to be saved since I finetune with a different vocabsize than what was used during pretraining. The default value of `save_embedding_layers` is `auto` but is set to `True` when vocabsizes are different: 
https://github.com/huggingface/peft/blob/8dd45b75d7eabe7ee94ecb6a19d552f2aa5e98c6/src/peft/utils/save_and_load.py#L162-L173
Does anybody know how I can save a Wav2Vec2forCTC + Lora checkpoint? Maybe @patrickvonplaten ?

Thank you in advance!

**Comment by HNO333333** [comment]
same issue here with Wav2Vec2BertForCTC, the `save_pretrained()` method is broken.

**Comment by geoffvdr** [comment]
I feel like the following should be added to `Wav2Vec2ForCTC`class:

```python
def get_output_embeddings(self):
        return self.lm_head

def get_input_embeddings(self):
        return self.wav2vec2.encoder.pos_conv_embed.conv
``` 

Not sure about `get_input_embeddings()` though.

**Comment by BenjaminBossan** [comment]
Yeah, so the issue is that we check `hasattr(model, "get_input_embeddings")` to determine if the method exists, but here it does exist but is not implemented. What we could do in PEFT is to wrap this with `try ... except NotImplementedError` to avoid raising an error, but this wouldn't solve the issue that we _do_ want to save the embeddings in this case. Therefore, the proper solution would be to implement the corresponding methods, as @geoffvdr suggests, but this would have to be changed in the transformers repo.

**Comment by HNO333333** [comment]
My trial was to overwrite the `_save()` method of `transformers.Trainer`. Remove the `PeftModel` from the `supported_classes` and it can work now. (avoid calling `save_pretrained`)

**Comment by geoffvdr** [comment]
My solution does not work as I am not able to use `from_pretrained()`. From the error traceback it seems to be related to `get_input_embeddings()`:
```
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/mms-1b and are newly initialized: ['lm_head.bias', 'lm_head.weight', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 model = AutoPeftModel.from_pretrained("[/project_antwerp/huggingface/exp/mms-1b_lora_nl_cv16/all_24-31_a16_r16/checkpoint-2859](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/workspaces/auto-S/tree/project_antwerp/project_antwerp/huggingface/exp/mms-1b_lora_nl_cv16/all_24-31_a16_r16/checkpoint-2859)")

File [/opt/conda/lib/python3.11/site-packages/peft/auto.py:126](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/workspaces/auto-S/tree/project_antwerp/opt/conda/lib/python3.11/site-packages/peft/auto.py#line=125), in _BaseAutoPeftModel.from_pretrained(cls, pretrained_model_name_or_path, adapter_name, is_trainable, config, **kwargs)
    122 if tokenizer_exists:
    123     tokenizer = AutoTokenizer.from_pretrained(
    124         pretrained_model_name_or_path, trust_remote_code=kwargs.get("trust_remote_code", False)
    125     )
--> 126     base_model.resize_token_embeddings(len(tokenizer))
    128 return cls._target_peft_class.from_pretrained(
    129     base_model,
    130     pretrained_model_name_or_path,
   (...)
    134     **kwargs,
    135 )

File [/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py:1786](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/workspaces/auto-S/tree/project_antwerp/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py#line=1785), in PreTrainedModel.resize_token_embeddings(self, new_num_tokens, pad_to_multiple_of)
   1761 def resize_token_embeddings(
   1762     self, new_num_tokens: Optional[int] = None, pad_to_multiple_of: Optional[int] = None
   1763 ) -> nn.Embedding:
   1764     """
   1765     Resizes input token embeddings matrix of the model if `new_num_tokens != config.vocab_size`.
   1766 
   (...)
   1784         `torch.nn.Embedding`: Pointer to the input tokens Embeddings Module of the model.
   1785     """
-> 1786     model_embeds = self._resize_token_embeddings(new_num_tokens, pad_to_multiple_of)
   1787     if new_num_tokens is None and pad_to_multiple_of is None:
   1788         return model_embeds

File [/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py:1801](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/workspaces/auto-S/tree/project_antwerp/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py#line=1800), in PreTrainedModel._resize_token_embeddings(self, new_num_tokens, pad_to_multiple_of)
   1799 def _resize_token_embeddings(self, new_num_tokens, pad_to_multiple_of=None):
   1800     old_embeddings = self.get_input_embeddings()
-> 1801     new_embeddings = self._get_resized_embeddings(old_embeddings, new_num_tokens, pad_to_multiple_of)
   1802     if hasattr(old_embeddings, "_hf_hook"):
   1803         hook = old_embeddings._hf_hook

File [/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py:1891](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/workspaces/auto-S/tree/project_antwerp/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py#line=1890), in PreTrainedModel._get_resized_embeddings(self, old_embeddings, new_num_tokens, pad_to_multiple_of)
   1889         old_num_tokens, old_embedding_dim = old_embeddings.weight.size()
   1890 else:
-> 1891     old_num_tokens, old_embedding_dim = old_embeddings.weight.size()
   1893 if old_num_tokens == new_num_tokens and not is_deepspeed_zero3_enabled():
   1894     return old_embeddings

ValueError: too many values to unpack (expected 2)
``` 

As @HNO333333 suggested, I might just avoid using `save_pretrained()` and `from_pretrained()`. However this implies saving the whole state_dict for every other adapter. I kind of liked saving only the adapters (and embedding layers) for memory footprint.

**Comment by geoffvdr** [comment]
> My trial was to overwrite the `_save()` method of `transformers.Trainer`. Remove the `PeftModel` from the `supported_classes` and it can work now. (avoid calling `save_pretrained`)

@HNO333333 How do you load (and evaluate) the peftmodel when you only save the state_dict? Did you modify something in `transformers.Trainer.evaluate()` to make it work?

**Comment by kent-rasmussen** [comment]
why is this closed? it looks like it was not resolved, then just inactive. I had this same situation today, and it would be nice to have an answer.

**Comment by githubnemo** [comment]
I'm a bit confused about the nature of this issue. What embeddings are we talking about here? AFAICS there are no input embeddings that need saving, so `save_embedding_layers` can safely be set to `False`, avoiding the issue and the (untrained) LM head can be trained by setting `modules_to_save=["lm_head"]`.

For example:
```python
from transformers import (
    AutoConfig,
    AutoModelForCTC,
)
from peft import LoraConfig
from peft import get_peft_model

config = AutoConfig.from_pretrained(
        "facebook/mms-1b"
    )
model = AutoModelForCTC.from_pretrained(
        "facebook/mms-1b",
        config=config,
        ignore_mismatched_sizes=True,
    )
peft_kwargs = {
        "lora_alpha": 16,
        "lora_dropout": 0.0,
        "r": 16,
        "bias": "none",
        "target_modules": ["q_proj", "v_proj"],
        "modules_to_save": ["lm_head"],
}
peft_config = LoraConfig(**peft_kwargs)
model = get_peft_model(model, peft_config)
model.save_pretrained("output", state_dict=model.state_dict(), save_embedding_layers=False)
```

It would be great if someone could explain to me if I'm missing something here.
