### ISSUE TITLE
TypeError: ChatGLMForConditionalGeneration.forward() got an unexpected keyword argument 'decoder_input_ids'

### ISSUE THREAD

**Issue by 12915494174** [huggingface/peft#1596]
### System Info

python 3.10.8
peft 0.7.1
transformers 4.38.1
datasets 2.18.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

code:
  ```
 tokenized_dataset = dataset.map(
        preprocess_function, batched=True, remove_columns=["content", "summary"]
    )
    print(f"Keys of tokenized dataset: {list(tokenized_dataset['train'].features)}")

    # save datasets to disk for later easy loading
    # tokenized_dataset["train"].save_to_disk("data/train")
    # tokenized_dataset["test"].save_to_disk("data/eval")

    # load model from the hub
    model = AutoModelForSeq2SeqLM.from_pretrained(model_dir)

    # Define LoRA Config
    lora_config = LoraConfig(
        r=8,
        lora_alpha=32,
        target_modules=["q", "v"],
        lora_dropout=0.1,
        bias="none",
        task_type=TaskType.SEQ_2_SEQ_LM,
    )
    # prepare int-8 model for training
    # model = prepare_model_for_int8_training(model)

    # add LoRA adaptor
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    # trainable params: 18874368 || all params: 11154206720 || trainable%: 0.16921300163961817

    # we want to ignore tokenizer pad token in the loss
    label_pad_token_id = -100
    # Data collator
    data_collator = DataCollatorForSeq2Seq(
        tokenizer,
        # model=model,
        label_pad_token_id=label_pad_token_id,
        pad_to_multiple_of=8,
        # batch_size=8,
    )

    # Define training args
    training_args = Seq2SeqTrainingArguments(
        output_dir=output_dir,
        auto_find_batch_size=True,
        learning_rate=1e-3,  # higher learning rate
        num_train_epochs=10,
        # per_device_train_batch_size=8,
        logging_dir=f"{output_dir}/logs",
        logging_strategy="steps",
        logging_steps=500,
        save_strategy="no",
        report_to="tensorboard",
        lr_scheduler_type="constant",
        # using only a portion of the dataset
        # train = 30,
        # max_eval_samples = 30,
    )

    # Create Trainer instance
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        data_collator=data_collator,
        train_dataset=tokenized_dataset["train"],
    )
    model.config.use_cache = (
        False  # silence the warnings. Please re-enable for inference!
    )
    # train model
    trainer.train()

    # Save our LoRA model & tokenizer results
    trainer.model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)

```
    error:
```
trainable params: 1,949,696 || all params: 6,245,533,696 || trainable%: 0.031217444255383614
  0%|                                                                                                                                                    | 0/530 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/test01/test01.py", line 164, in <module>
    trainer.train()
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/utils/memory.py", line 136, in decorator
    return function(batch_size, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1961, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2902, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2925, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/peft/peft_model.py", line 1249, in forward
    return self.base_model(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 103, in forward
    return self.model.forward(*args, **kwargs)
TypeError: ChatGLMForConditionalGeneration.forward() got an unexpected keyword argument 'decoder_input_ids'
  0%|          | 0/530 [00:00<?, ?it/s]           
```         

### Expected behavior

When I was using peft+lora to fine tune the chatGLM3-6B model using task type SEQ_2_SEQ-LM, I encountered a TypeError: ChatGLMForConditionalGeneration. forward() got an unexpected keyword argument 'decoded_input_ids' error. I am not sure where the problem occurred, but it was normal when I was performing CAUAL-LM and FEATURTExtraction.

**Comment by BenjaminBossan** [comment]
Is ChatGLM even a seq2seq model (i.e. encoder-decoder)? If it's a causal model (decoder only), seq2seq would not be expected to work. Why do you need seq2seq anyway when causal LM worked for you?

**Comment by 12915494174** [comment]
> Is ChatGLM even a seq2seq model (i.e. encoder-decoder)? If it's a causal model (decoder only), seq2seq would not be expected to work. Why do you need seq2seq anyway when causal LM worked for you?

That is to say, the task type is not something you can choose based on what you want, should you choose based on the task type of the model?

**Comment by BenjaminBossan** [comment]
Not quite. You can use, for instance, a causal LM for sequence classification:

```python
from transformers import AutoModelForCausalLM, AutoModelForSequenceClassification

model0 = AutoModelForCausalLM.from_pretrained("gpt2)
model1 = AutoModelForSequenceClassification.from_pretrained("gpt2")
```

But it doesn't make sense to load a decoder only model like GPT-2 as a seq2seq model, as that has a different architecture. And both causal LM and seq2seq are for text generation, so it's not like you could really do anything new if you could load a causal LM as a seq2seq LM.

**Comment by 12915494174** [comment]
> Not quite. You can use, for instance, a causal LM for sequence classification:
> 
> ```python
> from transformers import AutoModelForCausalLM, AutoModelForSequenceClassification
> 
> model0 = AutoModelForCausalLM.from_pretrained("gpt2)
> model1 = AutoModelForSequenceClassification.from_pretrained("gpt2")
> ```
> 
> But it doesn't make sense to load a decoder only model like GPT-2 as a seq2seq model, as that has a different architecture. And both causal LM and seq2seq are for text generation, so it's not like you could really do anything new if you could load a causal LM as a seq2seq LM.

@BenjaminBossan I understand, thank you for your help!
