### ISSUE TITLE
Error while merge and unload: InvalidHeaderDeserialization when open .safetensor model

### ISSUE THREAD

**Issue by dipeshpaulsystango** [huggingface/peft#1599]
### System Info

tensorflow==2.16.1
pip install git+https://github.com/huggingface/transformers
pip install git+https://github.com/huggingface/accelerate
pip install git+https://github.com/huggingface/peft
pip install git+https://github.com/huggingface/trl
pip install git+https://github.com/huggingface/datatrove.git

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I am training Openhermes 7b model using Peft LORA. Below is the code for training model and merging model-
It would be great if someone could tell me what is wrong with this.

I am facing this issue while merging the LORA adators to original model.

@pacman100 

train.py-

```python
import ast
import mlflow
from datasets import DatasetDict, load_dataset, load_from_disk
from datasets.builder import DatasetGenerationError
import torch
from datasets import load_dataset
from peft import LoraConfig
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    HfArgumentParser,
    TrainingArguments,
)
from peft.tuners.lora import LoraLayer
from trl import SFTTrainer
from dataclasses import dataclass, field
from typing import Optional
from constants import *

os.environ["MLFLOW_EXPERIMENT_NAME"] = "Trainer-mlflow-Tfonia"
os.environ["MLFLOW_FLATTEN_PARAMS"] = "1"
mlflow.set_tracking_uri(uri=f"{MLFLOW_TRACKING_URL}")
mlflow.autolog()
device = torch.device("cuda")


@dataclass
class ModelArguments:
    """
    Arguments for creating and preparing the model.
    """
    model_name: str = field(
        default="teknium/OpenHermes-2.5-Mistral-7B",
        metadata={"help": "The model name or path from the Hugging Face hub."},
    )
    use_4bit: bool = field(
        default=True,
        metadata={"help": "Activate 4bit precision base model loading"},
    )
    use_nested_quant: bool = field(
        default=False,
        metadata={"help": "Activate nested quantization for 4bit base models"},
    )
    bnb_4bit_compute_dtype: str = field(
        default="float16",
        metadata={"help": "Compute dtype for 4bit base models"},
    )
    bnb_4bit_quant_type: str = field(
        default="nf4",
        metadata={"help": "Quantization type: fp4 or nf4"},
    )
    lora_alpha: int = field(default=16)
    lora_dropout: float = field(default=0.1)
    lora_r: int = field(default=64)
    target_modules: str = field(
        default="q_proj,k_proj,v_proj,o_proj,down_proj,up_proj,gate_proj",
        metadata={"help": "LORA target modules"},
    )
    use_reentrant: Optional[bool] = field(
        default=False,
        metadata={"help": "Gradient Checkpointing param. Refer the related docs"}
    )
    use_flash_attn: Optional[bool] = field(
        default=False,
        metadata={"help": "Enables Flash attention for training."},
    )


@dataclass
class ScriptArguments:
    """
    Arguments for model training and data handling.
    """
    local_rank: int = field(default=-1, metadata={"help": "Used for multi-gpu"})
    per_device_train_batch_size: int = field(default=1)
    per_device_eval_batch_size: Optional[int] = field(default=1)
    gradient_accumulation_steps: Optional[int] = field(default=1)
    learning_rate: Optional[float] = field(default=2e-4)
    max_grad_norm: Optional[float] = field(default=0.3)
    weight_decay: Optional[int] = field(default=0.001)
    max_seq_length: Optional[int] = field(default=512)
    dataset_name: Optional[str] = field(
        default="data/selected_1000_rows.csv",  # "timdettmers/openassistant-guanaco",  # data/selected_1000_rows.csv
        metadata={"help": "The preference dataset to use."},
    )
    val_size_split: Optional[str] = field(
        default="0.1",
        metadata={"help": "Validation size of dataset"},
    )
    fp16: Optional[bool] = field(
        default=False,
        metadata={"help": "Enables fp16 training."},
    )
    bf16: Optional[bool] = field(
        default=False,
        metadata={"help": "Enables bf16 training."},
    )
    packing: Optional[bool] = field(
        default=False,
        metadata={"help": "Use packing dataset creating."},
    )
    gradient_checkpointing: Optional[bool] = field(
        default=True,
        metadata={"help": "Enables gradient checkpointing."},
    )
    optim: Optional[str] = field(
        default="paged_adamw_32bit",
        metadata={"help": "The optimizer to use."},
    )
    lr_scheduler_type: str = field(
        default="constant",
        metadata={"help": "Learning rate schedule. Constant a bit better than cosine, and has advantage for analysis"},
    )
    num_train_epochs: int = field(default=1, metadata={"help": "Number of training epochs"})
    max_steps: int = field(default=-1, metadata={"help": "How many optimizer update steps to take"})
    warmup_ratio: float = field(default=0.03, metadata={"help": "Fraction of steps to do a warmup for"})
    group_by_length: bool = field(
        default=True,
        metadata={
            "help": "Group sequences into batches with same length. Saves memory and speeds up training considerably."
        },
    )
    save_strategy: str = field(default="steps", metadata={"help": "Save model 'save_strategy at steps or epoch"})
    save_steps: int = field(default=10, metadata={"help": "Save checkpoint every X updates steps."})
    logging_strategy: str = field(default="steps", metadata={"help": "logging_strategy at steps or epoch"})
    logging_steps: int = field(default=10, metadata={"help": "Log every X updates steps."})
    eval_steps: int = field(default=10, metadata={"help": "Evaluate every X updates steps."})
    splits: Optional[str] = field(
        default="train,test",
        metadata={"help": "Comma separate list of the splits to use from the dataset."},
    )
    resume_from_checkpoint: str = field(default=None, metadata={'help': "Resume from checkpoint path"})


def get_model_peftconfig_tokenizer(args: ModelArguments):
    """
    Create the model, tokenizer, and peft_config based on provided arguments.
    """
    compute_dtype = getattr(torch, args.bnb_4bit_compute_dtype)

    # Configure BitsAndBytes for model quantization
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=args.use_4bit,
        bnb_4bit_quant_type=args.bnb_4bit_quant_type,
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=args.use_nested_quant,
        llm_int8_enable_fp32_cpu_offload=True
    )

    # Alert for bfloat16 acceleration support
    if compute_dtype == torch.float16 and args.use_4bit:
        major, _ = torch.cuda.get_device_capability()
        if major >= 8:
            print("=" * 80)
            print("Your GPU supports bfloat16, you can accelerate training with --bf16")
            print("=" * 80)

    # Load the model with quantization configuration
    device_map = (
        int(os.environ.get("LOCAL_RANK", -1))
        if torch.distributed.is_available() and torch.distributed.is_initialized()
        else "auto"
    )
    print("device_map set to: ", device_map)
    model = AutoModelForCausalLM.from_pretrained(
        args.model_name, quantization_config=bnb_config, device_map=device_map, trust_remote_code=True,
        attn_implementation="flash_attention_2"
    )

    # Define Lora Configuration
    peft_config = LoraConfig(
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        r=args.lora_r,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=args.target_modules.split(","),
    )

    # Load the tokenizer and set padding token
    tokenizer = AutoTokenizer.from_pretrained(args.model_name, trust_remote_code=True)

    # Need to do below for models like Falcon-7B, GPT-2 etc,
    # because it doesn't have an official pad token.
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = 'right'

    return model, peft_config, tokenizer


def parse_arguments():
    """
    Parse Model and Script Arguments.
    Returns:
        ModelArguments, ScriptArguments
    """
    parser = HfArgumentParser((ModelArguments, ScriptArguments))
    return parser.parse_args_into_dataclasses()


def get_training_args(script_args: ScriptArguments, model_args: ModelArguments):
    """
    Get Training Arguments from ScriptArguments.
    Args:
        script_args (ScriptArguments): Parsed ScriptArguments.
    Returns:
        TrainingArguments
    """
    return TrainingArguments(
        output_dir=f"./training_results/{model_args.model_name.replace('/', '-')}",
        per_device_train_batch_size=script_args.per_device_train_batch_size,
        gradient_accumulation_steps=script_args.gradient_accumulation_steps,
        optim=script_args.optim,
        learning_rate=script_args.learning_rate,
        fp16=script_args.fp16,
        bf16=script_args.bf16,
        max_grad_norm=script_args.max_grad_norm,
        num_train_epochs=script_args.num_train_epochs,
        max_steps=script_args.max_steps,
        save_strategy=script_args.save_strategy,
        save_steps=script_args.save_steps,
        eval_steps=script_args.eval_steps,
        logging_strategy=script_args.logging_strategy,
        logging_steps=script_args.logging_steps,
        warmup_ratio=script_args.warmup_ratio,
        group_by_length=script_args.group_by_length,
        lr_scheduler_type=script_args.lr_scheduler_type,
        report_to=["wandb", "mlflow"]
    )


def create_datasets(tokenizer, data_args, apply_chat_template = False):
    def preprocess(samples):
        batch = []
        for conversation, prompt in zip(samples["messages"], samples["prompt"]):
            if isinstance(conversation, str):
                try:
                    conversation = ast.literal_eval(conversation)
                except ValueError:
                    print("Error: Unable to convert the string to a list.")

            # TODO: If use hugging face dataset then you might not want to run below 1 line because it repeats
            #  system prompt in user first message
            conversation = [{'content': prompt, 'role': 'system'}] + conversation
            batch.append(tokenizer.apply_chat_template(conversation, tokenize=False))
        return {"content": batch}

    raw_datasets = DatasetDict()

    if data_args.dataset_name.endswith('.json') or data_args.dataset_name.endswith('.csv'):
        file_type = 'json' if data_args.dataset_name.endswith('json') else 'csv'
        print(f"You have given {file_type} file")
        ds = load_dataset(file_type, data_files=f'{data_args.dataset_name}')

        print("Creating Validation Split: ", data_args.val_size_split)
        train_test_valid = ds['train'].train_test_split(test_size=float(data_args.val_size_split))
        raw_datasets = DatasetDict({
            'train': train_test_valid['train'],
            'test': train_test_valid['test']})
    else:
        for split in data_args.splits.split(","):
            try:
                # Try first if dataset on a Hub repo
                print(f"Looking for dataset on a Hub repo and creating {split} split")
                dataset = load_dataset(data_args.dataset_name, split=split)
            except DatasetGenerationError:
                # If not, check local dataset
                dataset = load_from_disk(os.path.join(data_args.dataset_name, split))

            if "train" in split:
                raw_datasets["train"] = dataset
            elif "test" in split:
                raw_datasets["test"] = dataset
            else:
                raise ValueError(
                    f"Split type {split} not recognized as one of test or train."
                )
    if apply_chat_template:
        raw_datasets = raw_datasets.map(
            preprocess,
            batched=True,
            remove_columns=raw_datasets["train"].column_names,
        )

    train_data = raw_datasets["train"]
    valid_data = raw_datasets["test"]

    print(
        f"Size of the train set: {len(train_data)}. Size of the validation set: {len(valid_data)}"
    )
    print(f"A sample of train dataset: {train_data[0]}")

    return train_data, valid_data


def adjust_model_for_bf16(trainer, bf16: bool):
    """
    Adjust Model Layers for bf16.
    Args:
        trainer (SFTTrainer): Initialized SFTTrainer object.
        bf16 (bool): Flag to indicate usage of bf16.
    """
    for name, module in trainer.model.named_modules():
        if isinstance(module, LoraLayer) and bf16:
            module = module.to(torch.bfloat16)
        if "norm" in name:
            module = module.to(torch.float32)
        if "lm_head" in name or "embed_tokens" in name:
            if hasattr(module, "weight") and bf16 and module.weight.dtype == torch.float32:
                module = module.to(torch.bfloat16)


def start_training(model_args, script_args, training_arguments):
    model, peft_config, tokenizer = get_model_peftconfig_tokenizer(model_args)
    model.config.use_cache = False  # not training_args.gradient_checkpointing

    train_dataset, eval_dataset = create_datasets(tokenizer=tokenizer, data_args=script_args, apply_chat_template=True)

    if script_args.gradient_checkpointing:
        script_args.gradient_checkpointing_kwargs = {
            "use_reentrant": model_args.use_reentrant
        }

    trainer = SFTTrainer(
        model=model,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        peft_config=peft_config,
        dataset_text_field="content",
        max_seq_length=script_args.max_seq_length,
        tokenizer=tokenizer,
        args=training_arguments,
        packing=script_args.packing,
    )

    if model_args.bnb_4bit_compute_dtype == "bfloat16" or model_args.bnb_4bit_compute_dtype == "bf16":
        adjust_model_for_bf16(trainer, script_args.bf16)

    trainer.model.print_trainable_parameters()
    trainer.accelerator.print(f"{trainer.model}")

    # Train the Model
    if script_args.resume_from_checkpoint is not None:
        print("Resuming from checkpoint: ", script_args.resume_from_checkpoint)
        trainer.train(resume_from_checkpoint=script_args.resume_from_checkpoint)
    else:
        print("Starting new training...")
        trainer.train()
    trainer.save_model()
    mlflow.end_run()


if __name__ == "__main__":
    model_args, script_args = parse_arguments()
    training_arguments = get_training_args(script_args, model_args)
    start_training(model_args, script_args, training_arguments)
```

merge.py-

```python
import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
import argparse


def merge_lora_to_base(model_name_or_path, path_to_lora_checkpoint, _merge_model_path):
    model_name = model_name_or_path
    adapters_name = path_to_lora_checkpoint

    print(f"Starting to load the model {model_name} into memory")
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.float16,
        trust_remote_code=True,
    )
    print("Loading Tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(model_name,
                                              trust_remote_code=True,
                                              use_fast=True)
    print("Successfully loaded model and tokenizer into memory")

    print("Resizing model...")
    model.resize_token_embeddings(len(tokenizer))

    print("Loading Adaptors...")
    model = PeftModel.from_pretrained(model, adapters_name)
    
    print("Merging model...")
    model = model.merge_and_unload()

    print(f"Saving merged model to {save_merge_model_path}...")
    model.save_pretrained(save_merge_model_path)
    print(f"Saving tokenizer to {save_merge_model_path}...")
    tokenizer.save_pretrained(save_merge_model_path)
    print("Merging Done")
    return model, tokenizer


if __name__ == "__main__":
    """
    Cli usage- 
    python merger_lora_non_quantize.py --model_name_or_path teknium/OpenHermes-2.5-Mistral-7B \
    --path_to_lora_checkpoint training_results/OpenHermes/checkpoint-100 \
    --save_merge_model_path OpenHermes-2.5-Mistral-7B-merged-lora-non-quantized
    """
    parser = argparse.ArgumentParser(description='Merge LoRA adaptors to base model')
    parser.add_argument('--model_name_or_path', type=str, default='teknium/OpenHermes-2.5-Mistral-7B',
                        help='Path to the base model or model name')
    parser.add_argument('--path_to_lora_checkpoint', type=str,
                        default='training_results/OpenHermes-2.5-Mistral-7B/checkpoint-100',
                        help='Path to the LoRA checkpoint')
    parser.add_argument('--save_merge_model_path', type=str,
                        default='merged_models/OpenHermes-2.5-Mistral-7B-merged-lora-non-quantized',
                        help='Path to save the merged model')

    args = parser.parse_args()
    save_merge_model_path = args.save_merge_model_path
    if "/" in save_merge_model_path:
        pass
    else:
        save_merge_model_path = f"merged_models/{save_merge_model_path}/"
    model, tokenizer = merge_lora_to_base(args.model_name_or_path,
                                          args.path_to_lora_checkpoint,
                                          args.save_merge_model_path,
                                          )
```

Error-

```
Starting to load the model teknium/OpenHermes-2.5-Mistral-7B into memory
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
Loading Tokenizer...
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Successfully loaded model and tokenizer into memory
Resizing model...
Loading Adaptors...
Traceback (most recent call last):
  File "/home/user/deployment/chatbot/scripts/merger_lora_non_quantize.py", line 63, in <module>
    model, tokenizer = merge_lora_to_base(args.model_name_or_path,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/deployment/chatbot/scripts/merger_lora_non_quantize.py", line 27, in merge_lora_to_base
    model = PeftModel.from_pretrained(model, adapters_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/deployment/venv/lib/python3.11/site-packages/peft/peft_model.py", line 388, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/home/user/deployment/venv/lib/python3.11/site-packages/peft/peft_model.py", line 839, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/deployment/venv/lib/python3.11/site-packages/peft/utils/save_and_load.py", line 326, in load_peft_weights
    adapters_weights = safe_load_file(filename, device=device)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/deployment/venv/lib/python3.11/site-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization
```

### Expected behavior

Model should merged

**Comment by BenjaminBossan** [comment]
Looking at the error message, it doesn't seem to be directly related to merging. Instead, the error already occurs when you try to load the LoRA adapter. To me, it looks like the safetensors file is broken, which is why it fails. Could you check if the following works:

```python
from safetensors.torch import load_file
state_dict = load_file("/tmp/peft/opt-seq-cls-0/adapter_model.safetensors")
# if this works, inspect if the state_dict contains the right data
```

If this fails, could you check if the `adapter_model.safetensors` file itself looks suspicious (e.g. too small or too large)?

**Comment by dipeshpaulsystango** [comment]
> Looking at the error message, it doesn't seem to be directly related to merging. Instead, the error already occurs when you try to load the LoRA adapter. To me, it looks like the safetensors file is broken, which is why it fails. Could you check if the following works:
> 
> ```python
> from safetensors.torch import load_file
> state_dict = load_file("/tmp/peft/opt-seq-cls-0/adapter_model.safetensors")
> # if this works, inspect if the state_dict contains the right data
> ```
> 
> If this fails, could you check if the `adapter_model.safetensors` file itself looks suspicious (e.g. too small or too large)?

I tried-

```
from safetensors.torch import load_file

state_dict = load_file("training_results/teknium-OpenHermes-2.5-Mistral-7B/checkpoint-31900/adapter_model.safetensors")
# if this works, inspect if the state_dict contains the right data
print(state_dict)
```

But still same error-

```
Traceback (most recent call last):
  File "/home/parth/deployment/tfonia-chatbot/scripts/tmp.py", line 5, in <module>
    state_dict = load_file("training_results/teknium-OpenHermes-2.5-Mistral-7B/checkpoint-31900/adapter_model.safetensors")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parth/deployment/tfonia-chatbot/scripts/venv_merger/lib/python3.11/site-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization
```


Also I check size of adaptor_model.safetensors it is only 48 bytes.
![image](https://github.com/huggingface/peft/assets/154497724/094a1ee1-885a-4627-ae83-c64c1d385008)

Any idea why it is not saving correct lora adaptor? I have shared my training code also. 

Thanks

**Comment by BenjaminBossan** [comment]
Hmm, the adapter file is definitely broken, no wonder it cannot be loaded. Do you perhaps also have some intermediate checkpoints that you could try? Also, do you use something like DeepSpeed to train your model?

**Comment by dipeshpaulsystango** [comment]
> Hmm, the adapter file is definitely broken, no wonder it cannot be loaded. Do you perhaps also have some intermediate checkpoints that you could try? Also, do you use something like DeepSpeed to train your model?

All checkpoints are in bytes. I am using deepseed. But why do you think deepspeed is causing the issue?

This is how I configured it-

]```accelerate config```

I follow this in my terminal, I have 2GPUs-

```commandline
(venv) ulap64@arousr-ai3:~/tfonia-chatbot/training/manual_llm_trainer/chat_assistant/sft/training$ accelerate config
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
This machine                                                                                                                                                                                                       
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?                                                                                                                                                                               
multi-GPU                                                                                                                                                                                                          
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1                                                                                                                         
Should distributed operations be checked while running for errors? This can avoid timeout issues but will be slower. [yes/NO]: No                                                                                  
Do you wish to optimize your script with torch dynamo?[yes/NO]:NO                                                                                                                                                  
Do you want to use DeepSpeed? [yes/NO]: yes                                                                                                                                                                        
Do you want to specify a json file to a DeepSpeed config? [yes/NO]: No                                                                                                                                             
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------What should be your DeepSpeed's ZeRO optimization stage?
3                                                                                                                                                                                                                  
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Where to offload optimizer states?                                                                                                                                                                                 
none                                                                                                                                                                                                               
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Where to offload parameters?                                                                                                                                                                                       
none                                                                                                                                                                                                               
How many gradient accumulation steps you're passing in your script? [1]: 1                                                                                                                                         
Do you want to use gradient clipping? [yes/NO]: No                                                                                                                                                                 
Do you want to save 16-bit model weights when using ZeRO Stage-3? [yes/NO]: No                                                                                                                                     
Do you want to enable `deepspeed.zero.Init` when using ZeRO Stage-3 for constructing massive models? [yes/NO]: No
How many GPU(s) should be used for distributed training? [1]:4
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
bf16                                                                                                                                                                                                               
accelerate configuration saved at /home/ulap64/.cache/huggingface/accelerate/default_config.yaml        
```



Am I creating model correctly-

```
def get_model_peftconfig_tokenizer(args: ModelArguments):
    """
    Create the model, tokenizer, and peft_config based on provided arguments.
    """
    compute_dtype = getattr(torch, args.bnb_4bit_compute_dtype)

    # Configure BitsAndBytes for model quantization
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=args.use_4bit,
        bnb_4bit_quant_type=args.bnb_4bit_quant_type,
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=args.use_nested_quant,
        llm_int8_enable_fp32_cpu_offload=True
    )

    # Alert for bfloat16 acceleration support
    if compute_dtype == torch.float16 and args.use_4bit:
        major, _ = torch.cuda.get_device_capability()
        if major >= 8:
            print("=" * 80)
            print("Your GPU supports bfloat16, you can accelerate training with --bf16")
            print("=" * 80)

    # Load the model with quantization configuration
    device_map = (
        int(os.environ.get("LOCAL_RANK", -1))
        if torch.distributed.is_available() and torch.distributed.is_initialized()
        else "auto"
    )
    print("device_map set to: ", device_map)
    original_model = AutoModelForCausalLM.from_pretrained(
        args.model_name, quantization_config=bnb_config, device_map=device_map, trust_remote_code=True,
        attn_implementation="flash_attention_2"
    )

    # Define Lora Configuration
    peft_config = LoraConfig(
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        r=args.lora_r,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=args.target_modules.split(","),
    )
    original_model.gradient_checkpointing_enable()
    original_model = prepare_model_for_kbit_training(original_model)
    model = get_peft_model(original_model, peft_config)

    # Load the tokenizer and set padding token
    tokenizer = AutoTokenizer.from_pretrained(args.model_name, trust_remote_code=True)

    # Need to do below for models like Falcon-7B, GPT-2 etc,
    # because it doesn't have an official pad token.
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = 'right'

    return model, peft_config, tokenizer
```


In my original code above I didn't include these 3 lines-
```
    original_model.gradient_checkpointing_enable()
    original_model = prepare_model_for_kbit_training(original_model)
    model = get_peft_model(original_model, peft_config)
```

Is that causing this issue?

**Comment by BenjaminBossan** [comment]
> But why do you think deepspeed is causing the issue?

Just for the reason that users have reported this issue before.

I'm not knowledgeable about DeepSpeed, so I can't really help you to identify what parts of your code may be an issue. But colleagues managed to get DS+PEFT (+ bnb) to run correctly, so it should be possible. Please check [out docs](https://huggingface.co/docs/peft/accelerate/deepspeed) on this, maybe there you can find a critical difference to your script that enables you to train successfully.

**Comment by amishra-systango** [comment]
I am facing the exact same issue, does anybody have a solution to it ??

**Comment by shjunn** [comment]
> Also I check size of adaptor_model.safetensors it is only 48 bytes. ![image](https://private-user-images.githubusercontent.com/154497724/317704055-094a1ee1-885a-4627-ae83-c64c1d385008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzA5NTAsIm5iZiI6MTcxMTYzMDY1MCwicGF0aCI6Ii8xNTQ0OTc3MjQvMzE3NzA0MDU1LTA5NGExZWUxLTg4NWEtNDYyNy1hZTgzLWM2NGMxZDM4NTAwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMjU3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTQ4M2M5YjUxNjE0NDM0NTdiMTk5YjYyMWE0YzNiNjk2ZWEzZThmODQzMzk3ZGNkNjk1Y2FkNTRmNzE3MDhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nHqdYfVaoBWZXu5hvahmcZ2B7rc8ePzLbbbgTChgy30)
> 
> Any idea why it is not saving correct lora adaptor? I have shared my training code also.
> 
> Thanks

Hi! I had a similar problem with you that I trained the base model torchrun(not accelerate) + peft(lora) + deepspeed.
I also don't know why DS make that small adapter_model.safetensors, but please check the global_step28450.
If that folder had some state files with reasonable size, then you could try to convert those files to a single adapter_model.bin using zero_to_fp32.py(Check the contents of this python script for before using it. Pretty easy)
I hope my tiny solution can help you!
Thanks

**Comment by dipeshpaulsystango** [comment]
> 

I think my acclerate was not properly configured. I didn't able to find what was the exact reason, how does deepspeed works. But I reconfigured the accelerate and this works for me. Now my adaptor_model.safetensors are in MB.

```
(venv_merger) parth@arousr-ai3-new:~/deployment/tfonia-chatbot/scripts$ accelerate config
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
This machine                                                                                                                                                                                                       
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?                                                                                                                                                                               
multi-GPU                                                                                                                                                                                                          
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1                                                                                                                         
Should distributed operations be checked while running for errors? This can avoid timeout issues but will be slower. [yes/NO]: yes                                                                                 
Do you wish to optimize your script with torch dynamo?[yes/NO]:No                                                                                                                                                  
Do you want to use DeepSpeed? [yes/NO]: yes                                                                                                                                                                        
Do you want to specify a json file to a DeepSpeed config? [yes/NO]: No                                                                                                                                             
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------What should be your DeepSpeed's ZeRO optimization stage?                                                                                                                                                           
0                                                                                                                                                                                                                  
How many gradient accumulation steps you're passing in your script? [1]: 1                                                                                                                                         
Do you want to use gradient clipping? [yes/NO]: No                                                                                                                                                                 
Do you want to enable `deepspeed.zero.Init` when using ZeRO Stage-3 for constructing massive models? [yes/NO]: No                                                                                                  
How many GPU(s) should be used for distributed training? [1]:2                                                                                                                                                     
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
bf16                                                                                                                                                                                                               
accelerate configuration saved at /home/parth/.cache/huggingface/accelerate/default_config.yaml
```

**Comment by dipeshpaulsystango** [comment]
> > Also I check size of adaptor_model.safetensors it is only 48 bytes. ![image](https://private-user-images.githubusercontent.com/154497724/317704055-094a1ee1-885a-4627-ae83-c64c1d385008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzA5NTAsIm5iZiI6MTcxMTYzMDY1MCwicGF0aCI6Ii8xNTQ0OTc3MjQvMzE3NzA0MDU1LTA5NGExZWUxLTg4NWEtNDYyNy1hZTgzLWM2NGMxZDM4NTAwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMjU3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTQ4M2M5YjUxNjE0NDM0NTdiMTk5YjYyMWE0YzNiNjk2ZWEzZThmODQzMzk3ZGNkNjk1Y2FkNTRmNzE3MDhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nHqdYfVaoBWZXu5hvahmcZ2B7rc8ePzLbbbgTChgy30)
> > Any idea why it is not saving correct lora adaptor? I have shared my training code also.
> > Thanks
> 
> Hi! I had a similar problem with you that I trained the base model torchrun(not accelerate) + peft(lora) + deepspeed. I also don't know why DS make that small adapter_model.safetensors, but please check the global_step28450. If that folder had some state files with reasonable size, then you could try to convert those files to a single adapter_model.bin using zero_to_fp32.py(Check the contents of this python script for before using it. Pretty easy) I hope my tiny solution can help you! Thanks

Thanks for the solution but I didn't tried your solution. Your solution makes sense to me, `zero_to_fp32.py` might convert it to .bin file, but I need .safetensor file. BTW this works for me https://github.com/huggingface/peft/issues/1599#issuecomment-2025207388

Thanks

**Comment by BenjaminBossan** [comment]
Glad that you found a solution @dipeshpaulsystango and thanks @shjunn for providing a potential other solution. @dipeshpaulsystango what exactly did you change in your accelerate config compared to the one that didn't work? If you could share, it might help other users in the future.

**Comment by BenjaminBossan** [comment]
Thanks for sharing. I also wonder if you used a different accelerate or DeepSpeed version previously, and it might just be the newer versions that fix it, not so much the accelerate config itself.

**Comment by dipeshpaulsystango** [comment]
> Thanks for sharing. I also wonder if you used a different accelerate or DeepSpeed version previously, and it might just be the newer versions that fix it, not so much the accelerate config itself.

I used same version both the time. I crosses checked.
