### ISSUE TITLE
Prompt Tuning with Zero3 didn't work

### ISSUE THREAD

**Issue by tricktreat** [huggingface/peft#1633]
### System Info

peft==0.9.0

### Who can help?

@younesbelkada @BenjaminBossan 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

When I train the llama-2-7b-chat model using prompt tuning with the zero3 strategy, I encountered the following error message:

```
Traceback (most recent call last):
  File "sft_prompt_tuning.py", line 86, in <module>
    model = get_peft_model(model, peft_config)
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/peft/mapping.py", line 136, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/peft/peft_model.py", line 1063, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/peft/peft_model.py", line 122, in __init__
    self.add_adapter(adapter_name, peft_config)
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/peft/peft_model.py", line 621, in add_adapter
    self._setup_prompt_encoder(adapter_name)
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/peft/peft_model.py", line 392, in _setup_prompt_encoder
    prompt_encoder = PromptEmbedding(config, self.word_embeddings)
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/peft/tuners/prompt_tuning/model.py", line 83, in __init_
_
    word_embedding_weights = word_embeddings(init_token_ids).detach().clone()
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call
_impl
    return self._call_impl(*args, **kwargs)
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/shenyl/miniconda/lib/python3.8/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: 'weight' must be 2-D
```
By reading the source code, I discovered that in https://github.com/huggingface/peft/blob/e07095a654fa72835651e6e0ad846fc6f517baa9/src/peft/peft_model.py#L427, the size of the weight for `self.word_embeddings` is `torch.Size(0)`. However, when I `print(self.word_embeddings)`, the size is correctly `Embedding(32000, 4096)`. I suspect this might be due to the partitioned weights of `self.word_embeddings.weight` not being collected. But I am having difficulty resolving it.

### Expected behavior

to be able to train normally.

**Comment by BenjaminBossan** [comment]
Are you on the latest version of PEFT (v0.10.0)?

**Comment by tricktreat** [comment]
Thank you for your reply. After upgrading to peft==0.10.0, the same issue mentioned above occurred.
<img width="805" alt="image" src="https://github.com/huggingface/peft/assets/25740077/26678c19-eee3-433e-8197-150fb4531f34">

**Comment by BenjaminBossan** [comment]
> After upgrading to peft==0.10.0, the same issue mentioned above occurred.

We should have a fix for this, but it is not released yet, sorry for confusing that. If you install PEFT from source, it should work. Could you please try that?

**Comment by tricktreat** [comment]
Hi, @BenjaminBossan . It's so strange. When `print(self.word_embeddings)`, it print `Embedding(32000, 4096)`. But when I inspect its weight via `print(self.word_embeddings.weight.size())`, it print `torch.Size(0)`.

**Comment by tricktreat** [comment]
> > After upgrading to peft==0.10.0, the same issue mentioned above occurred.
> 
> We should have a fix for this, but it is not released yet, sorry for confusing that. If you install PEFT from source, it should work. Could you please try that?

OK, Thanks! I will try that.

**Comment by tricktreat** [comment]
Thanks! I've tried it and it worked well.  #1591  has fixed the bug.
