### ISSUE TITLE
`AdaLoRA` is incompatible with `gradient checkpointing` when using `torchrun`

### ISSUE THREAD

**Issue by zwhe99** [huggingface/peft#1745]
### System Info

```shell
torch==2.0.1
transformers==4.40.2
flash-attn==2.3.3
peft==0.10.0
accelerate==0.28.0
deepspeed==0.14.0
bitsandbytes==0.43.0
datasets==2.18.0
trl==0.8.6
fire
tqdm
tensorboardX
sentencepiece
``` 
python==3.10.10

### Who can help?

@BenjaminBossan

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

run.py:
```python
import os
import fire
import peft

from peft import LoraConfig, AdaLoraConfig, get_peft_model
from datasets import load_dataset, load_from_disk
from transformers import (
    Trainer,
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    DataCollatorForSeq2Seq,
)

def train(
    # model
    base_model: str,
    output_dir: str,
    use_lora: bool = False, # If True, use LoRA
    use_adalora: bool = False, # If True, use AdaLoRA

    # lora config
    lora_r: int = 8,
    lora_target_modules: list[str] = ["q_proj", "v_proj"],
    lora_alpha: int = 16,
    lora_dropout: float = 0.1,

    # data
    data_name: str = None, # Path to the data
    data_dir: str = None, # If provided, the data will loaded from `data_dir/data_name`
    train_split: str = None, # The split to use for training

    # training
    batch_size: int = 8,
    num_train_epochs: int = 1, 

    # debug
    debug: bool = False,
):
    # Sanity check
    assert data_name is not None, "Data name must be provided"

    # Load model and tokenizer
    model = AutoModelForCausalLM.from_pretrained(base_model, device_map="auto")
    model.config.use_cache = False # Gradient checkpointing requires disabling cache
    tokenizer = AutoTokenizer.from_pretrained(base_model, verbose=False)

    # Set pad_token to eos_token
    tokenizer.padding_side = "left"
    if tokenizer.pad_token_id is None:
        assert tokenizer.eos_token_id is not None
        tokenizer.pad_token = tokenizer.eos_token
        tokenizer.pad_token_id = tokenizer.eos_token_id
        try:
            model.config.pad_token_id = model.config.eos_token_id
        except AttributeError:
            model.config.pad_token_id = tokenizer.eos_token_id

    # PEFT
    peft_config = None
    if use_lora:
        peft_config = LoraConfig(
            r=lora_r,
            target_modules=lora_target_modules,
            lora_alpha=lora_alpha,
            lora_dropout=lora_dropout,
            task_type=peft.utils.peft_types.TaskType.CAUSAL_LM
        )
    elif use_adalora:
        peft_config = AdaLoraConfig(
            r=lora_r,
            target_modules=lora_target_modules,
            lora_alpha=lora_alpha,
            lora_dropout=lora_dropout,
            task_type=peft.utils.peft_types.TaskType.CAUSAL_LM
        )

    if peft_config:
        model = get_peft_model(model, peft_config)
        model.enable_input_require_grads()

    model.gradient_checkpointing_enable()
    model.print_trainable_parameters()

    # Load data
    if data_dir is None:
        all_data = load_dataset(data_name)
    else:
        all_data = load_from_disk(os.path.join(data_dir, data_name))

    # Load train data
    if train_split is not None:
        train_data = all_data[train_split]
    else:
        train_data = all_data

    # Define tokenizing function
    def tokenize(sample):
        messages = sample["messages"]
        res = tokenizer.apply_chat_template(
            conversation=messages,
            tokenize=True,
            return_dict=True
        )
        res["labels"] = res["input_ids"].copy()
        return res

    # Process data
    train_data = train_data.map(
        tokenize,
        load_from_cache_file=debug,
        num_proc=10,
    )

    # Start training
    trainer = Trainer(
        model=model,
        train_dataset=train_data,
        tokenizer=tokenizer,
        args=TrainingArguments(
            per_device_train_batch_size=batch_size,
            num_train_epochs=num_train_epochs,
            output_dir=output_dir,
        ),
        data_collator=DataCollatorForSeq2Seq(
            tokenizer, pad_to_multiple_of=8, return_tensors="pt", padding=True
        )
    )

    trainer.train()

if __name__ == "__main__":
    fire.Fire(train)
``` 

launch:
```shell
torchrun --nnodes 1 --nproc_per_node 1 run.py \
    --base_model yujiepan/llama-2-tiny-random \
    --output_dir debug \
    --use_adalora \
    --data_name HuggingFaceH4/ultrachat_200k \
    --train_split train_sft \
    --debug
``` 

error:
```
/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
trainable params: 408 || all params: 513,458 || trainable%: 0.07946122175523607
Detected kernel version 4.14.105, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
NCCL version 2.14.3+cuda11.7

  0%|          | 0/25984 [00:00<?, ?it/s]Traceback (most recent call last):
  File "run.py", line 133, in <module>
    fire.Fire(train)
  File "/root/miniconda3/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "run.py", line 130, in train
    trainer.train()
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 3147, in training_step
    self.accelerator.backward(loss)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 2001, in backward
    loss.backward(**kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 4 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

  0%|          | 0/25984 [00:02<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 170391) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-19_13:24:06
  host      : ts-ef6bfe5835244839ac0697d0b1a3b77b-launcher.ts-ef6bfe5835244839ac0697d0b1a3b77b-launcher.qingyuan-1-ailab-mt-qy-qingyuan-1.svc.cluster.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 170391)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

The following two ways work:
* Comment out `model.gradient_checkpointing_enable()` -> can not train larger model due to OOM
* Using `python3` instead of `torchrun --nnodes 1 --nproc_per_node 1` -> can not use multi-gpu

### Expected behavior

Training proceeds normally with multi-gpu and gradient checkpointing.

**Comment by BenjaminBossan** [comment]
Thanks for reporting this error. I could reproduce it and think I found a fix. For this, please call `prepare_model_for_kbit_training` on the base model. This helps with gradient checkpointing, even if the model is not quantized. Here is my full diff that ran successfully:

```diff
5c5
< from peft import LoraConfig, AdaLoraConfig, get_peft_model
---
> from peft import LoraConfig, AdaLoraConfig, get_peft_model, prepare_model_for_kbit_training
14a15
> 
78a80
>         model = prepare_model_for_kbit_training(model)
82c84
<     model.gradient_checkpointing_enable()
---
>     #model.gradient_checkpointing_enable()
95a98
>     train_data = train_data.select(range(1000))# BB
123a127
>             fp16=True, # BB
```

Here is how I called the script:

`torchrun --nnodes 1 --nproc_per_node 1 run.py --base_model "trl-internal-testing/tiny-random-LlamaForCausalLM" --output_dir /tmp/ --use_adalora --data_name HuggingFaceH4/ultrachat_200k --train_split train_sft --debug --batch_size 1`

One thing to note is that for AdaLoRA training, you have to call `model.update_and_allocate` (see e.g. this [adalora training script](https://github.com/huggingface/peft/blob/fb7f2796e5411ee86588447947d1fdd5b6395cad/examples/conditional_generation/peft_adalora_seq2seq.py#L120)), which is not done automatically if you use `Trainer`. Therefore, you either have to write your own training loop or add a custom callback to `Trainer` that calls this method.

**Comment by zwhe99** [comment]
Thanks a lot! It works.
