### ISSUE TITLE
when I use it for chatglm ，error like this 

### ISSUE THREAD

**Issue by shyoulala** [huggingface/peft#246]
Traceback (most recent call last):
  File "main_step1.py", line 310, in <module>
    main()
  File "main_step1.py", line 306, in main
    train(args)
  File "main_step1.py", line 164, in train
    model = get_peft_model(model, peft_config)
  File "/app/anaconda3/lib/python3.8/site-packages/peft/mapping.py", line 142, in get_peft_model
    peft_config = _prepare_lora_config(peft_config, model_config)
  File "/app/anaconda3/lib/python3.8/site-packages/peft/mapping.py", line 117, in _prepare_lora_config
    raise ValueError("Please specify `target_modules` in `peft_config`")
ValueError: Please specify `target_modules` in `peft_config`

**Comment by pacman100** [comment]
Hello, please refer issue #221  or https://github.com/27182812/ChatGLM-LLaMA-chinese-insturct/tree/main. They have got PEFT working with ChatGLM! Please let us know if this resolves the issue.

**Comment by shibing624** [comment]
set target_modules=["query_key_value"]
