### ISSUE TITLE
AttributeError: 'BloomForCausalLM' object has no attribute 'get_submodule'

### ISSUE THREAD

**Issue by SefaZeng** [huggingface/peft#284]
Trying to use lora finetune bloomz-1b7. And the training scripts return this error.
```
  File "/work/hf/run_clm_lora.py", line 710, in <module>
    main()
  File "/work/hf/run_clm_lora.py", line 470, in main
    model = get_peft_model(model, peft_config)
  File "/opt/anaconda3/lib/python3.8/site-packages/peft/mapping.py", line 145, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config)
  File "/opt/anaconda3/lib/python3.8/site-packages/peft/peft_model.py", line 514, in __init__
    super().__init__(model, peft_config)
  File "/opt/anaconda3/lib/python3.8/site-packages/peft/peft_model.py", line 79, in __init__
    self.base_model = LoraModel(peft_config, model)
  File "/opt/anaconda3/lib/python3.8/site-packages/peft/tuners/lora.py", line 118, in __init__
    self._find_and_replace()
  File "/opt/anaconda3/lib/python3.8/site-packages/peft/tuners/lora.py", line 146, in _find_and_replace
    parent, target, target_name = self._get_submodules(key)
  File "/opt/anaconda3/lib/python3.8/site-packages/peft/tuners/lora.py", line 187, in _get_submodules
    parent = self.model.get_submodule(".".join(key.split(".")[:-1]))
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BloomForCausalLM' object has no attribute 'get_submodule'
```
Does peft require a specific version of pytorch or transformers?

**Comment by pacman100** [comment]
Hello @SefaZeng, I'm able to reproduce the error, could you install transformers, peft and accelerate from main branch and see if that fixes the issue?
<img width="1145" alt="Screenshot 2023-04-08 at 1 27 34 PM" src="https://user-images.githubusercontent.com/13534540/230710575-f38710aa-1c6a-4226-9cad-e9bc4d8fc057.png">

**Comment by SefaZeng** [comment]
> Hello @SefaZeng, I'm able to reproduce the error, could you install transformers, peft and accelerate from main branch and see if that fixes the issue? <img alt="Screenshot 2023-04-08 at 1 27 34 PM" width="1145" src="https://user-images.githubusercontent.com/13534540/230710575-f38710aa-1c6a-4226-9cad-e9bc4d8fc057.png">

Thank you for your reply! Change torch from 1.8.1 to 1.10.0 solved my problem.

**Comment by TingchenFu** [comment]
hello @SefaZeng , have you ever encountered a similar problem that
```
Traceback (most recent call last):
  File "/apdcephfs/share_916081/shared_info/tingchenfu/work1/code/posttrain_peft.py", line 611, in <module>
    main()
  File "/apdcephfs/share_916081/shared_info/tingchenfu/work1/code/posttrain_peft.py", line 300, in main
    model = get_peft_model(model, peft_config)
  File "/usr/local/lib/python3.10/site-packages/peft/mapping.py", line 112, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config)
  File "/usr/local/lib/python3.10/site-packages/peft/peft_model.py", line 652, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/usr/local/lib/python3.10/site-packages/peft/peft_model.py", line 91, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "/usr/local/lib/python3.10/site-packages/peft/tuners/lora.py", line 132, in __init__
    self.add_adapter(adapter_name, self.peft_config[adapter_name])
  File "/usr/local/lib/python3.10/site-packages/peft/tuners/lora.py", line 139, in add_adapter
    self._find_and_replace(adapter_name)
  File "/usr/local/lib/python3.10/site-packages/peft/tuners/lora.py", line 174, in _find_and_replace
    bias = target.bias is not None
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BloomForCausalLM' object has no attribute 'bias'
```

The problem is caused by  `bias = target.bias is not None`, which just follows `parent, target, target_name = self._get_submodules(key)`
