### ISSUE TITLE
The path to saved peft model has no config.json

### ISSUE THREAD

**Issue by SefaZeng** [huggingface/peft#298]
I try to finetune Bloomz-1b7 model using lora. And the saved checkpoint path do not have config.json:
```
ll /workspace/checkpoint/bloom_1b7_ft_ja2zh_lora/checkpoint-12000

drwxr-xr-x 2 1000141 users 3.3G Apr 12 10:12 global_step12000
-rw-r--r-- 1 1000141 users   16 Apr 12 10:12 latest
-rw-r--r-- 1 1000141 users 3.3G Apr 12 10:12 pytorch_model.bin
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_0.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_10.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_11.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_12.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_13.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_14.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_15.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_16.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_17.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_18.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_19.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_1.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_20.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_21.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_22.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_23.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_24.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_25.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_26.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_27.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_28.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_29.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_2.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_30.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_31.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_3.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_4.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_5.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_6.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_7.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_8.pth
-rw-r--r-- 1 1000141 users  15K Apr 12 10:12 rng_state_9.pth
-rw-r--r-- 1 1000141 users   96 Apr 12 10:12 special_tokens_map.json
-rw-r--r-- 1 1000141 users  280 Apr 12 10:12 tokenizer_config.json
-rw-r--r-- 1 1000141 users  14M Apr 12 10:12 tokenizer.json
-rw-r--r-- 1 1000141 users 3.3K Apr 12 10:12 trainer_state.json
-rw-r--r-- 1 1000141 users 4.8K Apr 12 10:12 training_args.bin
-rwxr--r-- 1 1000141 users  19K Apr 12 10:12 zero_to_fp32.py
```
When I try to load the checkpoint to inference, this error occurred:
```
Traceback (most recent call last):
  File "/workspace/inference/test_new.py", line 132, in <module>
    config = PeftConfig.from_pretrained(modelpath)
  File "/opt/anaconda3/lib/python3.8/site-packages/peft/utils/config.py", line 101, in from_pretrained
    raise ValueError(f"Can't find config.json at '{pretrained_model_name_or_path}'")
ValueError: Can't find config.json at '/workspace/bloom_1b7_ft_ja2zh_lora/checkpoint-12000'
```

**Comment by SefaZeng** [comment]
Added an adapter_config.json manually.

**Comment by uccollab** [comment]
> Added an adapter_config.json manually.

Hello, could you elaborate on how you filled the file manually? I'm fine-tuning a model through PEFT and need to re-load several checkpoints, all without config.json.

**Comment by FinnFrotscher** [comment]
yeah, what does that file contain? maybe an example would help
