### ISSUE TITLE
cannot transfer to cpu (Cannot copy out of meta tensor; no data!)

### ISSUE THREAD

**Issue by renmengjie7** [huggingface/peft#344]
When I try to transfer the model from cuda to cpu. 
I encountered some errors.
```shell
Traceback (most recent call last):
  File "/opt/conda/envs/env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/envs/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/envs/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/envs/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/conda/envs/env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/opt/conda/envs/env/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/run/determined/workdir/src/deploy/deploy.py", line 58, in finetune
    service.finetune(exp, agent, datas)
  File "/run/determined/workdir/src/deploy/service.py", line 112, in finetune
    self._finetune(data_path=data_path, output_dir=output_dir)
  File "/run/determined/workdir/src/deploy/service.py", line 151, in _finetune
    self.base_model.to('cpu')
  File "/opt/conda/envs/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1896, in to
    return super().to(*args, **kwargs)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/opt/conda/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```
my code is 
```python
self.base_model = LlamaForCausalLM.from_pretrained(
            self.base_model_dir,
            load_in_8bit=self.load_8bit,
            torch_dtype=torch.float16,
            device_map="auto",
        )
self.model = PeftModel.from_pretrained(
            self.base_model,
            self.lora_weights_dir,
            torch_dtype=torch.float16,
        )
self.model.to('cpu')
self.base_model.to('cpu')
```
Actually, I just need to clear the cuda memory of the current model so that I can train another model. 
I tried `del self.model` and `torch.cuda.empty_cache()` but it didn't work.

**Comment by renmengjie7** [comment]
May anyone have the same problem ?

**Comment by younesbelkada** [comment]
Hi @renmengjie7 
THanks for the issue! 
Sadly you cannot transfer 8bit models on the CPU, this is not supported
To clear cache of models that are loaded with `device_map` you need to do : 

```python
import gc

gc.collect()
torch.cuda.empty_cache()
gc.collect()
```

Related: https://github.com/huggingface/transformers/issues/21094

**Comment by renmengjie7** [comment]
> 

It worked! Problem solved.
Thank you very much for your quick reply. It really helps a lot.
Thank you very much again !
