### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one

### ISSUE THREAD

**Issue by iMountTai** [huggingface/peft#393]
![image](https://user-images.githubusercontent.com/35353688/236099778-707709d6-d305-4d2b-bae1-3e2227601ef4.png)

**Comment by CharlesLiu7** [comment]
me too. I set the lora config as following to add `embed_tokens` layer into gradients update: 
```
config = LoraConfig(
        r=lora_r,
        lora_alpha=lora_alpha,
        target_modules=lora_target_modules,
        lora_dropout=lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
        modules_to_save=["embed_tokens"],
    )
```
and then when run with only one gpu, it is ok. but when `torchrun` with more than one gpu, I got the error:
```
  File "/data/py310env/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/data/py310env/lib/python3.10/site-packages/transformers/trainer.py", line 1927, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/py310env/lib/python3.10/site-packages/transformers/trainer.py", line 2699, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/py310env/lib/python3.10/site-packages/transformers/trainer.py", line 2731, in compute_loss
    outputs = model(**inputs)
  File "/data/py310env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/py310env/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameters which did not receive grad for rank 1: base_model.model.model.embed_tokens.modules_to_save.default.weight
Parameter indices which did not receive grad for rank 1: 1
```
is there anything wrong in peft-lora?

**Comment by yeyupiaoling** [comment]
@CharlesLiu7 @iMountTai 
me too. How to solve this problem?

**Comment by yeyupiaoling** [comment]
I solved this problem in the following way:

```
        def make_inputs_require_grad(module, input, output):
            output.requires_grad_(True)

        model.model.encoder.conv1.register_forward_hook(make_inputs_require_grad)
```

**Comment by yangjianxin1** [comment]
I meet the same problem, I want to train embed_tokens and lm_head of llama. But it throw the error:
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 0
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
```

But when I set modules_to_save=None, it works. 
```python
model = AutoModelForCausalLM.from_pretrained(
        args.model_name_or_path,
        device_map=device_map,
        load_in_4bit=True,
        torch_dtype=torch.float16,
        trust_remote_code=True,
        quantization_config=BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
            llm_int8_threshold=6.0,
            llm_int8_has_fp16_weight=False,
        ),
    )

config = LoraConfig(
      r=args.lora_rank,
      lora_alpha=args.lora_alpha,
      # target_modules=target_modules,
      target_modules=['q_proj'],
      lora_dropout=args.lora_dropout,
      bias="none",
      task_type="CAUSAL_LM",
      # 如果扩词表，则词表需要参与训练，否则不训练
      modules_to_save=["embed_tokens", "lm_head"] if args.train_embedding else None,
      # inference_mode=False
  )
model = get_peft_model(model, config)
```

**Comment by mahdip72** [comment]
I have similar issue here:

```python
self.model = EsmModel.from_pretrained(model_name)

config = LoraConfig(
    r=configs.prot2seq_model.encoder.lora.r,
    lora_alpha=configs.prot2seq_model.encoder.lora.lora_alpha,
    target_modules=[
        # "query",
        # "key",
        # "value",
        "dense"
                    ],
    inference_mode=False,
    lora_dropout=configs.prot2seq_model.encoder.lora.lora_dropout,
    bias="none",
 )
self.model = get_peft_model(self.model, config)
```

When I use lora on multiple GPUs using accelerate, I got the following error.
```
Steps:   0%|                                                                                                                                                                                                          | 0/28 [00:00<?, ?it/s]/home/mpngf/environments/joint_training/lib/python3.10/site-packages/torch/nn/functional.py:4999: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(
/home/mpngf/environments/joint_training/lib/python3.10/site-packages/torch/nn/functional.py:4999: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(
Steps:   4%|██████▌                                                                                                                                                                               | 1/28 [00:02<01:01,  2.29s/it, lr=1.02e-5]Traceback (most recent call last):
  File "/home/mpngf/projects/JointTraining/train.py", line 326, in <module>
    main(config_file)
  File "/home/mpngf/projects/JointTraining/train.py", line 287, in main
    train_loss, train_acc = train(epoch, accelerator, tools, global_step)
  File "/home/mpngf/projects/JointTraining/train.py", line 90, in train
    preds = tools['net'](batch)
  File "/home/mpngf/environments/joint_training/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mpngf/environments/joint_training/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 36 37
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
Traceback (most recent call last):
  File "/home/mpngf/projects/JointTraining/train.py", line 326, in <module>
    main(config_file)
  File "/home/mpngf/projects/JointTraining/train.py", line 287, in main
    train_loss, train_acc = train(epoch, accelerator, tools, global_step)
  File "/home/mpngf/projects/JointTraining/train.py", line 90, in train
    preds = tools['net'](batch)
  File "/home/mpngf/environments/joint_training/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mpngf/environments/joint_training/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 36 37
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
``` 
But on single GPU there is not a problem and it works fine!
