### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'torch_dtype'

### ISSUE THREAD

**Issue by mhupfauer** [huggingface/peft#538]
Environment:
```
git clone https://github.com/tloen/alpaca-lora.git
cd alpaca-lora
git clone https://huggingface.co/tloen/alpaca-lora-7b
```

Stacktrace:

```
(alpaca-lora) root@host:~/alpaca-lora# python generate.py  --load_8bit --base_model 'decapoda-research/llama-7b-hf' --lora_weights './alpaca-lora-7b'

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/anaconda3/envs/alpaca-lora/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
CUDA SETUP: CUDA runtime path found: /opt/anaconda3/envs/alpaca-lora/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /opt/anaconda3/envs/alpaca-lora/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'.
The class this function is called from is 'LlamaTokenizer'.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.46it/s]
Traceback (most recent call last):
  File "/root/alpaca-lora/generate.py", line 218, in <module>
    fire.Fire(main)
  File "/opt/anaconda3/envs/alpaca-lora/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/anaconda3/envs/alpaca-lora/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/anaconda3/envs/alpaca-lora/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/alpaca-lora/generate.py", line 48, in main
    model = PeftModel.from_pretrained(
  File "/opt/anaconda3/envs/alpaca-lora/lib/python3.9/site-packages/peft/peft_model.py", line 167, in from_pretrained
    PeftConfig.from_pretrained(model_id, subfolder=kwargs.get("subfolder", None), **kwargs).peft_type
  File "/opt/anaconda3/envs/alpaca-lora/lib/python3.9/site-packages/peft/utils/config.py", line 114, in from_pretrained
    config = cls(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'torch_dtype'
```

Hardware:
GRID A100D-80C

conda list:
```
# packages in environment at /opt/anaconda3/envs/alpaca-lora:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
accelerate                0.19.0                   pypi_0    pypi
aiofiles                  23.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.0.1                    pypi_0    pypi
anyio                     3.7.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bitsandbytes              0.39.0                   pypi_0    pypi
black                     23.3.0                   pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py39h27cfd23_1003
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2023.01.10           h06a4308_0
certifi                   2023.5.7         py39h06a4308_0
cffi                      1.15.1           py39h5eee18b_3
chardet                   5.1.0                    pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cmake                     3.26.3                   pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cryptography              39.0.1           py39h9ce1e76_0
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cycler                    0.11.0                   pypi_0    pypi
datasets                  2.12.0                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
exceptiongroup            1.1.1                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastapi                   0.95.2                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.9.0            py39h06a4308_0
fire                      0.5.0                    pypi_0    pypi
fonttools                 4.39.4                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.5.0                 pypi_0    pypi
giflib                    5.2.1                h5eee18b_3
gmp                       6.2.1                h295c915_3
gmpy2                     2.1.2            py39heeb90bb_0
gnutls                    3.6.15               he1e5248_0
gradio                    3.33.1                   pypi_0    pypi
gradio-client             0.2.5                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  0.17.2                   pypi_0    pypi
httpx                     0.24.1                   pypi_0    pypi
huggingface-hub           0.15.1                   pypi_0    pypi
idna                      3.4              py39h06a4308_0
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305
ipython                   8.14.0                   pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2            py39h06a4308_0
jpeg                      9e                   h5eee18b_1
jsonschema                4.17.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.6.1.9                       0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_0
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libiconv                  1.16                 h7f8727e_2
libidn2                   2.3.4                h5eee18b_0
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.39               h5eee18b_0
libstdcxx-ng              11.2.0               h1234567_1
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.0                h6a678d5_2
libunistring              0.9.10               h27cfd23_0
libwebp                   1.2.4                h11a3e52_1
libwebp-base              1.2.4                h5eee18b_1
linkify-it-py             2.0.2                    pypi_0    pypi
lit                       16.0.5.post0             pypi_0    pypi
loralib                   0.1.1                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h6d00ec8_46342
mkl-service               2.4.0            py39h5eee18b_1
mkl_fft                   1.3.6            py39h417a72b_1
mkl_random                1.2.2            py39h417a72b_1
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.2                hb69a4c5_1
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
networkx                  3.1                      pypi_0    pypi
numpy                     1.24.3           py39hf6e8229_1
numpy-base                1.24.3           py39h060ed82_1
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openssl                   1.1.1t               h7f8727e_0
orjson                    3.9.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.2                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.11.1                   pypi_0    pypi
peft                      0.4.0.dev0               pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1           py39h06a4308_0
prompt-toolkit            3.0.38                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyarrow                   12.0.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pydantic                  1.10.8                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyopenssl                 23.0.0           py39h06a4308_0
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0
python                    3.9.16               h7a1cb2a_2
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytorch                   2.0.1           py3.9_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0
regex                     2023.5.5                 pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                67.8.0           py39h06a4308_0
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
stack-data                0.6.2                    pypi_0    pypi
starlette                 0.27.0                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0
termcolor                 2.3.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tokenize-rt               5.0.0                    pypi_0    pypi
tokenizers                0.13.3                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torchaudio                2.0.2                py39_cu117    pytorch
torchtriton               2.0.0                      py39    pytorch
torchvision               0.15.2               py39_cu117    pytorch
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
transformers              4.29.2                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.6.3                    pypi_0    pypi
typing_extensions         4.5.0            py39h06a4308_0
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.2                    pypi_0    pypi
urllib3                   2.0.2                    pypi_0    pypi
uvicorn                   0.22.0                   pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
zstd                      1.5.5                hc292b87_0
```

pip freeze:
```
accelerate==0.19.0
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==5.0.1
anyio==3.7.0
appdirs==1.4.4
asttokens==2.2.1
async-timeout==4.0.2
attrs==23.1.0
backcall==0.2.0
bitsandbytes==0.39.0
black==23.3.0
brotlipy==0.7.0
certifi @ file:///croot/certifi_1683875369620/work/certifi
cffi @ file:///croot/cffi_1670423208954/work
chardet==5.1.0
charset-normalizer==3.1.0
click==8.1.3
cmake==3.26.3
contourpy==1.0.7
cryptography @ file:///croot/cryptography_1677533068310/work
cycler==0.11.0
datasets==2.12.0
decorator==5.1.1
dill==0.3.6
distlib==0.3.6
exceptiongroup==1.1.1
executing==1.2.0
fastapi==0.95.2
ffmpy==0.3.0
filelock==3.12.0
fire==0.5.0
fonttools==4.39.4
frozenlist==1.3.3
fsspec==2023.5.0
gmpy2 @ file:///tmp/build/80754af9/gmpy2_1645438755360/work
gradio==3.33.1
gradio_client==0.2.5
h11==0.14.0
httpcore==0.17.2
httpx==0.24.1
huggingface-hub==0.15.1
idna @ file:///croot/idna_1666125576474/work
importlib-resources==5.12.0
ipython==8.14.0
jedi==0.18.2
Jinja2 @ file:///croot/jinja2_1666908132255/work
jsonschema==4.17.3
kiwisolver==1.4.4
linkify-it-py==2.0.2
lit==16.0.5.post0
loralib==0.1.1
markdown-it-py==2.2.0
MarkupSafe==2.1.3
matplotlib==3.7.1
matplotlib-inline==0.1.6
mdit-py-plugins==0.3.3
mdurl==0.1.2
mkl-fft==1.3.6
mkl-random @ file:///work/mkl/mkl_random_1682950433854/work
mkl-service==2.4.0
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
mypy-extensions==1.0.0
networkx==3.1
numpy @ file:///work/mkl/numpy_and_numpy_base_1682953417311/work
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
orjson==3.9.0
packaging==23.1
pandas==2.0.2
parso==0.8.3
pathspec==0.11.1
peft @ git+https://github.com/huggingface/peft.git@fcff23f005fc7bfb816ad1f55360442c170cd5f5
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.5.1
prompt-toolkit==3.0.38
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==12.0.0
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==1.10.8
pydub==0.25.1
Pygments==2.15.1
pyOpenSSL @ file:///croot/pyopenssl_1677607685877/work
pyparsing==3.0.9
pyrsistent==0.19.3
PySocks @ file:///tmp/build/80754af9/pysocks_1605305812635/work
python-dateutil==2.8.2
python-multipart==0.0.6
pytz==2023.3
PyYAML==6.0
regex==2023.5.5
requests==2.31.0
responses==0.18.0
scipy==1.10.1
semantic-version==2.10.0
sentencepiece==0.1.99
six==1.16.0
sniffio==1.3.0
stack-data==0.6.2
starlette==0.27.0
sympy==1.12
termcolor==2.3.0
tokenize-rt==5.0.0
tokenizers==0.13.3
tomli==2.0.1
toolz==0.12.0
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.65.0
traitlets==5.9.0
transformers==4.29.2
triton==2.0.0
typing_extensions==4.6.3
tzdata==2023.3
uc-micro-py==1.0.2
urllib3==2.0.2
uvicorn==0.22.0
virtualenv==20.23.0
wcwidth==0.2.6
websockets==11.0.3
xxhash==3.2.0
yarl==1.9.2
zipp==3.15.0
```

**Comment by JustinZou1** [comment]
I met the same issue as you. How can you resove this issue? Thanks.

**Comment by mhupfauer** [comment]
> I met the same issue as you. How can you resove this issue? Thanks.

See the linked issue: https://github.com/tloen/alpaca-lora/issues/497#issuecomment-1575023239
