### ISSUE TITLE
maybe one inference error about AdaLoraModel

### ISSUE THREAD

**Issue by kiritoD** [huggingface/peft#571]
when I use peftmodel to load the pretrained AdaLoraModel, run error:

```
  File "/mnt/bn/ecom-ccr-dev/mlx/users/dongjunwei/peft/src/peft/tuners/adalora.py", line 248, in forward
    orth_reg_weight = self.peft_config[self.trainable_adapter_name].orth_reg_weight
  File "/mnt/bn/ecom-ccr-dev/mlx/users/dongjunwei/peft/src/peft/tuners/adalora.py", line 241, in __getattr__
    return getattr(self.model, name)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BloomForCausalLM' object has no attribute 'trainable_adapter_name'
```

I debug the AdaLoraModel, and find the attribute 'trainable_adapter_name' will work the first time when inference mode is False in line 125 in peft/src/peft/tuners/adalora.py, after I modify the forward function as below, the inference work, maybe, this is a bug.
![image](https://github.com/huggingface/peft/assets/13377199/dbdaa06a-b8e1-4e02-94e2-8bc33ae7960d)

**Comment by younesbelkada** [comment]
Hi @kiritoD 
Thanks for the issue, can you share a handy reproducible snippet of the problem?

**Comment by nimasteryang** [comment]
Same error occur at my side, code as below:
```
from peft import AutoPeftModelForSequenceClassification
#adapter_dir_list is a list of adapters
model = AutoPeftModelForSequenceClassification.from_pretrained(adapter_dir_list[0],is_trainable=False)
model.to('cuda:0')
model.eval()
for step, batch in enumerate(tqdm(test_dataloader)):
    print(batch)
    batch.to('cuda:0')
    with torch.no_grad():
        outputs = model(**batch)
    predictions = outputs.logits.argmax(dim=-1)
    predictions, references = predictions, batch["labels"]
```

And the error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/anaconda3/envs/peft/lib/python3.8/site-packages/peft/tuners/lora.py:382, in LoraModel.__getattr__(self, name)
    381 try:
--> 382     return super().__getattr__(name)  # defer to nn.Module's logic
    383 except AttributeError:

File ~/anaconda3/envs/peft/lib/python3.8/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'AdaLoraModel' object has no attribute 'trainable_adapter_name'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
File ~/anaconda3/envs/peft/lib/python3.8/site-packages/peft/tuners/adalora.py:222, in AdaLoraModel.__getattr__(self, name)
    221 try:
--> 222     return super().__getattr__(name)  # defer to nn.Module's logic
    223 except AttributeError:

File ~/anaconda3/envs/peft/lib/python3.8/site-packages/peft/tuners/lora.py:384, in LoraModel.__getattr__(self, name)
    383 except AttributeError:
--> 384     return getattr(self.model, name)

File ~/anaconda3/envs/peft/lib/python3.8/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'RobertaForSequenceClassification' object has no attribute 'trainable_adapter_name'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[43], line 9
      7 batch.to('cuda:0')
      8 with torch.no_grad():
----> 9     outputs = model(**batch)
     10 predictions = outputs.logits.argmax(dim=-1)
     11 predictions, references = predictions, batch["labels"]

File ~/anaconda3/envs/peft/lib/python3.8/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/anaconda3/envs/peft/lib/python3.8/site-packages/peft/peft_model.py:761, in PeftModelForSequenceClassification.forward(self, input_ids, attention_mask, inputs_embeds, labels, output_attentions, output_hidden_states, return_dict, **kwargs)
    759 peft_config = self.active_peft_config
    760 if not isinstance(peft_config, PromptLearningConfig):
--> 761     return self.base_model(
    762         input_ids=input_ids,
    763         attention_mask=attention_mask,
    764         inputs_embeds=inputs_embeds,
    765         labels=labels,
    766         output_attentions=output_attentions,
    767         output_hidden_states=output_hidden_states,
    768         return_dict=return_dict,
    769         **kwargs,
    770     )
    772 batch_size = input_ids.shape[0]
    773 if attention_mask is not None:
    774     # concat prompt attention mask

File ~/anaconda3/envs/peft/lib/python3.8/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/anaconda3/envs/peft/lib/python3.8/site-packages/peft/tuners/adalora.py:230, in AdaLoraModel.forward(self, *args, **kwargs)
    227 outputs = self.model.forward(*args, **kwargs)
    229 # Calculate the orthogonal regularization
--> 230 orth_reg_weight = self.peft_config[self.trainable_adapter_name].orth_reg_weight
    231 assert orth_reg_weight > 0
    233 if hasattr(outputs, "loss"):

File ~/anaconda3/envs/peft/lib/python3.8/site-packages/peft/tuners/adalora.py:224, in AdaLoraModel.__getattr__(self, name)
    222     return super().__getattr__(name)  # defer to nn.Module's logic
    223 except AttributeError:
--> 224     return getattr(self.model, name)

File ~/anaconda3/envs/peft/lib/python3.8/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1612     if name in modules:
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'RobertaForSequenceClassification' object has no attribute 'trainable_adapter_name'
```

**Comment by nimasteryang** [comment]
> 

FYI, a quick solve will be do a `model = model.merge_and_unload()`

**Comment by BenjaminBossan** [comment]
The issue seems to be that the `trainable_adapter_name` attribute is not set when the model is in inference mode:

https://github.com/huggingface/peft/blob/a955ef1088144a77a926554060ca01486c6cc9fb/src/peft/tuners/adalora.py#L118-L122

I _think_ the fix would be to move these two lines:

https://github.com/huggingface/peft/blob/a955ef1088144a77a926554060ca01486c6cc9fb/src/peft/tuners/adalora.py#L230-L233

down, so that they are inside the `if` clause, as I would assume that `hasattr(outputs, "loss")` is only `True` if the model is not in inference mode, but I'm not 100% sure. Ping @pacman100 @younesbelkada

**Comment by diaoenmao** [comment]
I think the fix has minor issues as it is possible to have output.loss during inference. I think a feasible approach is
```
        if self.model.training and hasattr(outputs, "loss"):
            orth_reg_weight = self.peft_config[self.trainable_adapter_name].orth_reg_weight
            if orth_reg_weight <= 0:
                raise ValueError("orth_reg_weight should be greater than 0. ")
            regu_loss = 0
            num_param = 0
```

**Comment by BenjaminBossan** [comment]
Hmm, in that case, isn't the only issue that we do some computations on the loss even though they are not strictly needed? IIUC, the fix should still work.

**Comment by diaoenmao** [comment]
In my case, I need to evaluate the model with validation data so the input would contain labels. Even if I do not care about loss, I do care about other metrics, but the model would still produce loss because the input contains labels. As a result, the error would occur if you have label in the input and the model is in evaluation mode).

**Comment by BenjaminBossan** [comment]
Interesting. I wanted to reproduce the issue so I added a line to call `trainer.evaluate` after [this line in the tests](https://github.com/huggingface/peft/blob/ec267c644a9a9f05a7340a7cb23ed5a6a6090dd0/tests/test_gpu_examples.py#L229). This did not trigger any error though. Could you help me to reproduce the issue you mentioned, ideally within the linked test?
