### ISSUE TITLE
`bitsandbytes-windows` does not have `bnb.nn.Linear4bit` while it is imported in `peft\tuners\lora.py`

### ISSUE THREAD

**Issue by ZisIsNotZis** [huggingface/peft#603]
### System Info

Versions:
```
absl-py                        1.4.0
accelerate                     0.21.0.dev0
aiofiles                       22.1.0
aiohttp                        3.8.4
aiosignal                      1.3.1
aiosqlite                      0.19.0
anyio                          3.7.0
argon2-cffi                    21.3.0
argon2-cffi-bindings           21.2.0
arrow                          1.2.3
asttokens                      2.2.1
astunparse                     1.6.3
async-lru                      2.0.2
async-timeout                  4.0.2
attrs                          23.1.0
auth0-python                   4.1.0
Babel                          2.12.1
backcall                       0.2.0
beautifulsoup4                 4.12.2
bitsandbytes                   0.39.0
bitsandbytes-windows           0.37.5
black                          23.1.0
bleach                         6.0.0
botocore                       1.29.94
cachetools                     5.3.0
certifi                        2023.5.7
cffi                           1.15.1
charset-normalizer             3.1.0
click                          8.1.3
colorama                       0.4.6
coloredlogs                    15.0.1
comm                           0.1.3
contourpy                      1.0.7
cryptography                   39.0.2
cycler                         0.11.0
Cython                         3.0.0b1
datasets                       2.12.0
debugpy                        1.6.7
decorator                      5.1.1
defusedxml                     0.7.1
dill                           0.3.6
docutils                       0.16
einops                         0.6.1
et-xmlfile                     1.1.0
executing                      1.2.0
fastjsonschema                 2.17.1
filelock                       3.12.0
flatbuffers                    23.3.3
fonttools                      4.39.3
foolnltk                       0.1.7
fqdn                           1.5.1
frozenlist                     1.3.3
fsspec                         2023.5.0
gast                           0.4.0
google-auth                    2.16.2
google-auth-oauthlib           0.4.6
google-pasta                   0.2.0
grpcio                         1.53.0rc2
h5py                           3.8.0
huggingface-hub                0.15.1
humanfriendly                  10.0
idna                           3.4
ipykernel                      6.23.2
ipython                        8.14.0
ipython-genutils               0.2.0
ipywidgets                     8.0.6
isoduration                    20.11.0
jax                            0.4.6
jedi                           0.18.2
jieba                          0.42.1
Jinja2                         3.1.2
jmespath                       1.0.1
joblib                         1.2.0
json5                          0.9.14
jsonpointer                    2.3
jsonschema                     4.18.0a10
jsonschema-specifications      2023.5.2
jupyter                        1.0.0
jupyter_client                 8.2.0
jupyter-console                6.6.3
jupyter_core                   5.3.0
jupyter-events                 0.6.3
jupyter-lsp                    2.2.0
jupyter_server                 2.6.0
jupyter_server_fileid          0.9.0
jupyter_server_terminals       0.4.4
jupyter_server_ydoc            0.8.0
jupyter-ydoc                   0.2.4
jupyterlab                     4.0.2
jupyterlab_code_formatter      2.2.1
jupyterlab-pygments            0.2.2
jupyterlab_server              2.22.1
jupyterlab-widgets             3.0.7
keras                          2.12.0rc1
kiwisolver                     1.4.4
libclang                       15.0.6.1
lora                           0.3.0
Markdown                       3.4.1
MarkupSafe                     2.1.2
matplotlib                     3.7.1
matplotlib-inline              0.1.6
mistune                        2.0.5
mpmath                         1.3.0
multidict                      6.0.4
multiprocess                   0.70.14
mypy-extensions                1.0.0
nbclassic                      0.5.5
nbclient                       0.8.0
nbconvert                      7.4.0
nbformat                       5.9.0
nest-asyncio                   1.5.6
networkx                       3.1
notebook                       6.5.4
notebook_shim                  0.2.3
numpy                          1.25.0rc1
nvidia-cublas-cu12             12.1.3.1
nvidia-cuda-cupti-cu12         12.1.105
nvidia-cuda-nvcc-cu12          12.1.105
nvidia-cuda-nvrtc-cu12         12.1.105
nvidia-cuda-runtime-cu12       12.1.105
nvidia-cuda-sanitizer-api-cu12 12.1.105
nvidia-cufft-cu12              11.0.2.54
nvidia-curand-cu12             10.3.2.106
nvidia-cusolver-cu12           11.4.5.107
nvidia-cusparse-cu12           12.1.0.106
nvidia-npp-cu12                12.1.0.40
nvidia-nvjitlink-cu12          12.1.105
nvidia-nvjpeg-cu12             12.2.0.2
nvidia-nvml-dev-cu12           12.1.105
nvidia-nvtx-cu12               12.1.105
nvidia-pyindex                 1.0.9
oauthlib                       3.2.2
openpyxl                       3.2.0b1
opt-einsum                     3.3.0
optimum                        1.8.7
overrides                      7.3.1
packaging                      23.1
pandas                         2.0.2
pandocfilters                  1.5.0
parso                          0.8.3
pathspec                       0.11.1
peft                           0.4.0.dev0
pickleshare                    0.7.5
Pillow                         9.5.0
pip                            23.1.2
platformdirs                   3.5.1
prometheus-client              0.17.0
prompt-toolkit                 3.0.38
protobuf                       3.20.2
psutil                         5.9.5
pure-eval                      0.2.2
pyarrow                        12.0.0
pyasn1                         0.4.8
pyasn1-modules                 0.2.8
pycparser                      2.21
Pygments                       2.15.1
PyJWT                          2.6.0
pyparsing                      3.1.0b1
pyreadline3                    3.4.1
pyrsistent                     0.19.3
python-dateutil                2.8.2
python-json-logger             2.0.7
pytz                           2023.3
pywin32                        306
pywinpty                       2.0.10
PyYAML                         6.0
pyzmq                          25.1.1b1
qtconsole                      5.4.2
QtPy                           2.3.1
referencing                    0.29.0
regex                          2023.5.5
requests                       2.31.0
requests-oauthlib              1.3.1
responses                      0.18.0
rfc3339-validator              0.1.4
rfc3986-validator              0.1.1
rpds-py                        0.7.1
rsa                            4.7.2
s3transfer                     0.6.0
safetensors                    0.3.1
scikit-learn                   1.2.2
scipy                          1.10.1
Send2Trash                     1.8.2
sentencepiece                  0.1.99
setuptools                     67.6.0
six                            1.16.0
sniffio                        1.3.0
soupsieve                      2.4.1
stack-data                     0.6.2
sympy                          1.12
tensorboard                    2.12.0
tensorboard-data-server        0.7.0
tensorboard-plugin-wit         1.8.1
tensorflow                     2.12.0rc1
tensorflow-estimator           2.12.0rc0
tensorflow-io-gcs-filesystem   0.31.0
termcolor                      2.2.0
terminado                      0.17.1
threadpoolctl                  3.1.0
thulac                         0.2.2
tinycss2                       1.2.1
tokenizers                     0.13.3
torch                          2.1.0.dev20230405+cu118
torchaudio                     2.1.0.dev20230405+cu118
torchdata                      0.7.0.dev20230330
torchtext                      0.15.1.dev20230330
torchvision                    0.16.0.dev20230405+cu118
tornado                        6.3.2
tqdm                           4.65.0
traitlets                      5.9.0
transformers                   4.29.2
typing_extensions              4.6.3
tzdata                         2023.3
uri-template                   1.2.0
urllib3                        2.0.3
wcwidth                        0.2.6
webcolors                      1.13
webencodings                   0.5.1
websocket-client               1.5.3
Werkzeug                       2.2.3
wheel                          0.40.0
widgetsnbextension             4.0.7
wrapt                          1.14.1
xxhash                         3.2.0
y-py                           0.5.9
yarl                           1.9.2
ypy-websocket                  0.8.2
zhconv                         1.4.3
```

Platform: windows 10

### Who can help?

@pacman100  @younesbelkada 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

For repo `https://github.com/ymcui/Chinese-LLaMA-Alpaca`

```
D:\my\qa\Chinese-LLaMA-Alpaca>python scripts/inference/inference_hf.py --base_model minlik/chinese-llama-7b-merged --with_prompt --interactive

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: D:\py\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary D:\py\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "D:\my\qa\Chinese-LLaMA-Alpaca\scripts\inference\inference_hf.py", line 19, in <module>
    from peft import  PeftModel
  File "D:\py\Lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "D:\py\Lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "D:\py\Lib\site-packages\peft\peft_model.py", line 35, in <module>
    from .tuners import (
  File "D:\py\Lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "D:\py\Lib\site-packages\peft\tuners\lora.py", line 970, in <module>
    class Linear4bit(bnb.nn.Linear4bit, LoraLayer):
                     ^^^^^^^^^^^^^^^^^
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?
```

### Expected behavior

Should use things like `Linear8bitLt` on windows

**Comment by younesbelkada** [comment]
Hi @ZisIsNotZis 
Thanks for the isssue, with https://github.com/huggingface/peft/pull/605 you should be able to use PEFT on your environment. Note however that looking at the bitsandbytes-windows library it seems that the `Linear4bit` layers are not implemented.

**Comment by jllllll** [comment]
[bitsandbytes-windows](https://github.com/Keith-Hon/bitsandbytes-windows) hasn't been updated in a while. If you need `Linear4bit` support on Windows now, you can you use [my own fork](https://github.com/jllllll/bitsandbytes/tree/cmake_windows). Pre-compiled wheel [here](https://github.com/jllllll/bitsandbytes-windows-webui):
```
python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.39.0-py3-none-any.whl
```

**Comment by ZisIsNotZis** [comment]
@younesbelkada Thanks, does that mean in future versions of `bitsandbytes` `peft` will work or it will tell you that it's unimplemented?

@jllllll Thanks for your help! I tried to install this version above, but it still says `Linear4bit` doesn't exist, like this
```python
In [1]: import bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: D:\py\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary D:\py\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...

In [2]: bitsandbytes.nn.Linear4bit
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 bitsandbytes.nn.Linear4bit

AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'

In [3]: from bitsandbytes.nn import Linear8bitLt

In [4]: from bitsandbytes.nn import Linear4bit
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], line 1
----> 1 from bitsandbytes.nn import Linear4bit

ImportError: cannot import name 'Linear4bit' from 'bitsandbytes.nn' (D:\py\Lib\site-packages\bitsandbytes\nn\__init__.py)
```
Is there any step that I forgot to do?

**Comment by jllllll** [comment]
@ZisIsNotZis It must be loading a different version of bitsandbytes. I know `Linear4bit` works in my fork as people have been using it. The 0.39.0 version is compiled for CUDA 11.1-12.1.

As for the wrong CUDA version, use `python -m bitsandbytes` to determine what CUDA Runtime it is finding and loading.
Note that, in my fork, I have not yet converted the `BUG REPORT INFORMATION` section of that command's output for Windows.

**Comment by younesbelkada** [comment]
Thanks @jllllll & @ZisIsNotZis 

> @younesbelkada Thanks, does that mean in future versions of bitsandbytes peft will work or it will tell you that it's unimplemented?

The PR mentioned above simply checks if `Linear4bit` is present on your bitsandbytes package instead of checking the version of that library. Therefore if `Linear4bit` is not present in your bnb lib it will not import `Linear4bit` from LoRa, hence you won't see that error again
