### ISSUE TITLE
t0pp's key not able to run on lora

### ISSUE THREAD

**Issue by Vincent-Li-9701** [huggingface/peft#778]
### System Info

transformer 4.31.0
peft 0.5.0.dev0
python 3.9.6

### Who can help?

@pacman100 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```python
tokenizer = AutoTokenizer.from_pretrained("bigscience/T0pp", use_fast=False, legacy=False)
model = AutoModelForSeq2SeqLM.from_pretrained("bigscience/T0pp", load_in_8bit=True, device_map={'':f'cuda:{os.environ["LOCAL_RANK"]}'})

model.config.use_cache = False
model = prepare_model_for_int8_training(model)
config = LoraConfig(
    r=64,
    lora_alpha=16,
    target_modules=['v', 'wi_1', 'q', 'wi_0', 'o', 'k'],
    lora_dropout=0.0,
    bias="none",
    task_type="SEQ_2_SEQ_LM",
)
model = get_peft_model(model, config)
print_trainable_parameters(model)
```

### Expected behavior

I was expecting the lora config to work with T5 family's key module. However, lora only works when 'k' is not included. 

Stacktrack below

```
Traceback (most recent call last):
    model = get_peft_model(model, config)
  File "/miniconda/lib/python3.9/site-packages/peft/mapping.py", line 98, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/miniconda/lib/python3.9/site-packages/peft/peft_model.py", line 1083, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/miniconda/lib/python3.9/site-packages/peft/peft_model.py", line 112, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "/miniconda/lib/python3.9/site-packages/peft/tuners/lora.py", line 181, in __init__
    self.add_adapter(adapter_name, self.peft_config[adapter_name])
  File "/miniconda/lib/python3.9/site-packages/peft/tuners/lora.py", line 195, in add_adapter
    self._find_and_replace(adapter_name)
  File "/miniconda/lib/python3.9/site-packages/peft/tuners/lora.py", line 353, in _find_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target)
  File "/miniconda/lib/python3.9/site-packages/peft/tuners/lora.py", line 306, in _create_new_module
    raise ValueError(
ValueError: Target module ModuleList(
  (0): T5Block(
    (layer): ModuleList(
      (0): T5LayerSelfAttention(
        (SelfAttention): T5Attention(
          (q): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (k): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (v): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (o): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (relative_attention_bias): Embedding(32, 64)
        )
        (layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (1): T5LayerFF(
        (DenseReluDense): T5DenseGatedActDense(
          (wi_0): Linear8bitLt(in_features=4096, out_features=10240, bias=False)
          (wi_1): Linear8bitLt(in_features=4096, out_features=10240, bias=False)
          (wo): Linear(in_features=10240, out_features=4096, bias=False)
          (dropout): Dropout(p=0.1, inplace=False)
          (act): NewGELUActivation()
        )
        (layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (1-23): 23 x T5Block(
    (layer): ModuleList(
      (0): T5LayerSelfAttention(
        (SelfAttention): T5Attention(
          (q): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (k): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (v): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (o): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
        )
        (layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (1): T5LayerFF(
        (DenseReluDense): T5DenseGatedActDense(
          (wi_0): Linear8bitLt(in_features=4096, out_features=10240, bias=False)
          (wi_1): Linear8bitLt(in_features=4096, out_features=10240, bias=False)
          (wo): Linear(in_features=10240, out_features=4096, bias=False)
          (dropout): Dropout(p=0.1, inplace=False)
          (act): NewGELUActivation()
        )
        (layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
      )
    )
  )
) is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.
```

**Comment by BenjaminBossan** [comment]
I haven't run your code snippet but it's very likely that the issue is that the name of the module/layer is matched incorrectly. E.g. if the layer (shown in your stacktrace) is called `"block"`, it will match with `"k"` because there is an `.endswith` check. To avoid this, I would recommend to print out all layer names and build a regex that matches only those you really need. Then pass the regex string to `target_modules` and you should be fine.

**Comment by Vincent-Li-9701** [comment]
I changed my target_modules=['.q', '.k', '.v', '.o', '.wi_1', '.wi_0', '.wo']. It works
