### ISSUE TITLE
RuntimeError: expected scalar type Float but found Half

### ISSUE THREAD

**Issue by ScottishFold007** [huggingface/peft#88]
This my code：
```
# 引入相应的包 Importing libraries
import os
#os.environ['CUDA_VISIBLE_DEVICES'] = '1,2,3,4,5,6,7'
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
os.environ['DISABLE_MLFLOW_INTEGRATION'] = 'true'
os.environ["TOKENIZERS_PARALLELISM"] = 'false'
import gc
import sys
import threading
import psutil
import json
import time
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

import torch
from torch import nn
import bitsandbytes as bnb
import transformers
import torch.nn.functional as F
from torch.nn import CrossEntropyLoss
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler
from peft import LoraConfig, TaskType, get_peft_model, get_peft_model_state_dict
from peft.utils.other import fsdp_auto_wrap_policy
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler

# Importing the T5 modules from huggingface/transformers
from transformers import default_data_collator, get_linear_schedule_with_warmup
from transformers import (
    AutoConfig,
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    DataCollatorForSeq2Seq,
    HfArgumentParser,
    Trainer,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    set_seed,
)
from datasets import load_dataset


class CustomizedDatasets(Dataset):
    """
    创建一个自定义的数据集，用于训练，必须包括两个字段：输入(如source_text)、输出（如target_text）
    Creating a custom dataset for reading the dataset and
    loading it into the dataloader to pass it to the
    neural network for finetuning the model

    """

    def __init__(
        self, dataframe, tokenizer, source_len, target_len, source_text, target_text
    ):
        """
        Initializes a Dataset class

        Args:
            dataframe (pandas.DataFrame): Input dataframe
            tokenizer (transformers.tokenizer): Transformers tokenizer
            source_len (int): Max length of source text
            target_len (int): Max length of target text
            source_text (str): column name of source text
            target_text (str): column name of target text
        """
        self.tokenizer = tokenizer
        self.data = dataframe
        self.source_len = source_len
        self.summ_len = target_len
        self.target_text = self.data[target_text]
        self.source_text = self.data[source_text]

    def __len__(self):
        """returns the length of dataframe"""

        return len(self.target_text)

    def __getitem__(self, index):
        """return the input ids, attention masks and target ids"""

        source_text = str(self.source_text[index])
        target_text = str(self.target_text[index])

        # cleaning data so as to ensure data is in string type
        source_text = " ".join(source_text.split())
        target_text = " ".join(target_text.split())

        source = self.tokenizer.batch_encode_plus(
            [source_text],
            max_length=self.source_len,
            pad_to_max_length=True,
            truncation=True,
            padding="max_length",
            return_tensors="pt",
        )
        target = self.tokenizer.batch_encode_plus(
            [target_text],
            max_length=self.summ_len,
            pad_to_max_length=True,
            truncation=True,
            padding="max_length",
            return_tensors="pt",
        )

        source_ids = source["input_ids"].squeeze()
        source_mask = source["attention_mask"].squeeze()
        target_ids = target["input_ids"].squeeze()
        return {
            "input_ids": source_ids.contiguous(),
            "attention_mask": source_mask.contiguous(),
            "decoder_input_ids": target_ids.contiguous(),
            "labels": target_ids.contiguous(),
        }


# 定义模型的参数 let's define model parameters specific to T5
model_params = {
        "MODEL": "/root/gaochangkuan_AI/PromptCLUE_Large",  # model_type
        "TRAIN_BATCH_SIZE": 8,  # training batch size, 12
        "VALID_BATCH_SIZE": 8,  # validation batch size,8 
        "TRAIN_EPOCHS": 2,  # number of training epochs
        "VAL_EPOCHS": 2,  # number of validation epochs
        "LEARNING_RATE": 1e-4,  # learning rate
        "MAX_SOURCE_TEXT_LENGTH": 512,  # max length of source text, 512
        "MAX_TARGET_TEXT_LENGTH": 128,  # max length of target text,64
        "GRADIENT_ACCUMULATION_STEPS": 1,
        "LOGGING_STEP": 1000,  # log step,5000
        "SAVING_STEP":2000, #save step,5000
        "MAX_GRAD_NORM":1.0,  #max_grad_norm,1.0
        "WARMUP_STEPS":0,
        "PAD_TOKEN_ID":-100,   #pad_token_id,-100
        "FP_16":False,
        "GRADIENT_CHECKPOINTING":False,
        "SEED": 2023  # set seed for reproducibility
    }
    
    
model_name_or_path = model_params["MODEL"]
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)

    # creating model
peft_config = LoraConfig(
            task_type=TaskType.SEQ_2_SEQ_LM, 
            inference_mode=False, 
            r=8, 
            bias="none",
            lora_alpha=16, 
            lora_dropout=0.1
        )
model_config= AutoConfig.from_pretrained(model_name_or_path)
model = AutoModelForSeq2SeqLM.from_pretrained(      
                                                            pretrained_model_name_or_path= model_name_or_path,
                                                            config= model_config,
                                                            #torch_dtype=torch.float16,
                                                            load_in_8bit=True, 
                                                            device_map='auto',
                                                            )   
### Post-processing on the model
#Finally, we need to apply some post-processing on the 8-bit model to enable training, let's freeze all our layers, and cast the layer-norm in float32 for #stability. We also cast the output of the last layer in float32 for the same reasons.
       
for param in model.parameters():
  param.requires_grad = False  # freeze the model - train adapters later
  if param.ndim == 1:
    param.data = param.data.to(torch.float32)

#model.gradient_checkpointing_enable()  # reduce number of stored activations
def make_inputs_require_grad(module, input, output):
  output.requires_grad_(True)

model.shared.register_forward_hook(make_inputs_require_grad)

class CastOutputToFloat(nn.Sequential):
  def forward(self, x): 
    return super().forward(x).to(torch.float32)
            
model.lm_head = CastOutputToFloat(model.lm_head)
                                                                                                                                                                      
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

train_size = 0.95
dataframe = pd.read_csv('pCLUE_train.csv')  # 数据量：1200k数据。
dataframe = dataframe.sample(frac=0.5) # TODO  取消本行代码，如果你需要更多数据训练
train_dataset = dataframe.sample(frac=train_size, random_state=model_params["SEED"])
val_dataset = dataframe.drop(train_dataset.index).reset_index(drop=True)
train_dataset = train_dataset.reset_index(drop=True)
text_column= 'input'
label_column= 'target'

# Creating the Training and Validation dataset for further creation of Dataloader
training_set = CustomizedDatasets(
        train_dataset,
        tokenizer,
        model_params["MAX_SOURCE_TEXT_LENGTH"],
        model_params["MAX_TARGET_TEXT_LENGTH"],
        text_column,
        label_column,
        )
val_set = CustomizedDatasets(
        val_dataset,
        tokenizer,
        model_params["MAX_SOURCE_TEXT_LENGTH"],
        model_params["MAX_TARGET_TEXT_LENGTH"],
        text_column,
        label_column,
    )


def train_func_main():
  label_pad_token_id = model_params["PAD_TOKEN_ID"]  
  seq2seq_data_collator = DataCollatorForSeq2Seq(
            tokenizer,
            model=model,
            label_pad_token_id=label_pad_token_id,
            pad_to_multiple_of= None,
            )
        
  #trainer = Seq2SeqTrainer(
  trainer =  Trainer(
                    model=model, 
                    train_dataset=training_set,
                    eval_dataset=val_set,
                    args= Seq2SeqTrainingArguments(
                        do_train= True,
                        do_eval= True,
                        per_device_train_batch_size=model_params["TRAIN_BATCH_SIZE"], 
                        gradient_accumulation_steps=model_params["GRADIENT_ACCUMULATION_STEPS"],
                        warmup_steps=model_params["WARMUP_STEPS"], 
                        learning_rate=model_params["LEARNING_RATE"],
                        gradient_checkpointing= model_params["GRADIENT_CHECKPOINTING"], 
                        fp16=model_params["FP_16"],
                        log_level= "info",
                        #xpu_backend= "mpi",
                        #sharded_ddp= "simple",
                        #local_rank=7,
                        logging_dir= "logging",
                        num_train_epochs=model_params["TRAIN_EPOCHS"],
                        logging_steps=model_params["LOGGING_STEP"], 
                        save_steps=model_params["SAVING_STEP"], 
                        output_dir='outputs'
                    ),
                     #data_collator= default_data_collator #DataCollatorForSeq2Seq(tokenizer, mlm=False)
                     data_collator= seq2seq_data_collator
                    )
  model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
  trainer.train()
  peft_model_id= 'int8_peft_model'
  trainer.model.save_pretrained(peft_model_id)

if __name__ == "__main__":
  train_func_main()

```
I execute the following code in the command line：
`python int8_peft_lora_PromptCLUE_Finetuning.py`
Then the following error message appears:
```
  0%|                                                 | 0/35646 [00:00<?, ?it/s]You're using a T5TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/root/anaconda3/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py:298: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Traceback (most recent call last):
  File "/root/gaochangkuan_AI/PromptCLUE_Finetuning/int8_peft_lora_PromptCLUE_Finetuning.py", line 252, in <module>
    train_func_main()
  File "/root/gaochangkuan_AI/PromptCLUE_Finetuning/int8_peft_lora_PromptCLUE_Finetuning.py", line 247, in train_func_main
    trainer.train()
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1576, in train
    return inner_training_loop(
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1843, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 2588, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 2620, in compute_loss
    outputs = model(**inputs)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/peft/peft_model.py", line 639, in forward
    return self.base_model(
  File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 1722, in forward
    lm_logits = self.lm_head(sequence_output)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/gaochangkuan_AI/PromptCLUE_Finetuning/int8_peft_lora_PromptCLUE_Finetuning.py", line 175, in forward
    return super().forward(x).to(torch.float32)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Half
[31m╭───────────────────── [39m[1mTraceback (most recent call last)[31m[22m ──────────────────────╮
[31m│[39m /root/gaochangkuan_AI/PromptCLUE_Finetuning/[1mint8_peft_lora_PromptCLUE_Finetu[22m [31m│
[31m│[39m [1mning.py[22m:[94m252[39m in [92m<module>[39m                                                      [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   249   trainer.model.save_pretrained(peft_model_id)                         [31m│
[31m│[39m   250                                                                        [31m│
[31m│[39m   251 [94mif[39m [91m__name__[39m == [33m"__main__"[39m:                                             [31m│
[31m│[39m [31m❱ [39m252   train_func_main()                                                    [31m│
[31m│[39m   253                                                                        [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/gaochangkuan_AI/PromptCLUE_Finetuning/[1mint8_peft_lora_PromptCLUE_Finetu[22m [31m│
[31m│[39m [1mning.py[22m:[94m247[39m in [92mtrain_func_main[39m                                               [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   244 │   │   │   │   │    data_collator= seq2seq_data_collator              [31m│
[31m│[39m   245 │   │   │   │   │   )                                                  [31m│
[31m│[39m   246   model.config.use_cache = [94mFalse[39m  # silence the warnings. Please re-en [31m│
[31m│[39m [31m❱ [39m247   trainer.train()                                                      [31m│
[31m│[39m   248   peft_model_id= [33m'int8_peft_model'[39m                                     [31m│
[31m│[39m   249   trainer.model.save_pretrained(peft_model_id)                         [31m│
[31m│[39m   250                                                                        [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/transformers/[1mtrainer.py[22m:[94m1576[39m in  [31m│
[31m│[39m [92mtrain[39m                                                                        [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   1573 │   │   inner_training_loop = find_executable_batch_size(             [31m│
[31m│[39m   1574 │   │   │   [96mself[39m._inner_training_loop, [96mself[39m._train_batch_size, args.a [31m│
[31m│[39m   1575 │   │   )                                                             [31m│
[31m│[39m [31m❱ [39m1576 │   │   [94mreturn[39m inner_training_loop(                                   [31m│
[31m│[39m   1577 │   │   │   args=args,                                                [31m│
[31m│[39m   1578 │   │   │   resume_from_checkpoint=resume_from_checkpoint,            [31m│
[31m│[39m   1579 │   │   │   trial=trial,                                              [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/transformers/[1mtrainer.py[22m:[94m1843[39m in  [31m│
[31m│[39m [92m_inner_training_loop[39m                                                         [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   1840 │   │   │   │   │   [94mwith[39m model.no_sync():                             [31m│
[31m│[39m   1841 │   │   │   │   │   │   tr_loss_step = [96mself[39m.training_step(model, inpu [31m│
[31m│[39m   1842 │   │   │   │   [94melse[39m:                                                 [31m│
[31m│[39m [31m❱ [39m1843 │   │   │   │   │   tr_loss_step = [96mself[39m.training_step(model, inputs)  [31m│
[31m│[39m   1844 │   │   │   │                                                         [31m│
[31m│[39m   1845 │   │   │   │   [94mif[39m (                                                  [31m│
[31m│[39m   1846 │   │   │   │   │   args.logging_nan_inf_filter                       [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/transformers/[1mtrainer.py[22m:[94m2588[39m in  [31m│
[31m│[39m [92mtraining_step[39m                                                                [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   2585 │   │   │   [94mreturn[39m loss_mb.reduce_mean().detach().to([96mself[39m.args.device [31m│
[31m│[39m   2586 │   │                                                                 [31m│
[31m│[39m   2587 │   │   [94mwith[39m [96mself[39m.compute_loss_context_manager():                     [31m│
[31m│[39m [31m❱ [39m2588 │   │   │   loss = [96mself[39m.compute_loss(model, inputs)                   [31m│
[31m│[39m   2589 │   │                                                                 [31m│
[31m│[39m   2590 │   │   [94mif[39m [96mself[39m.args.n_gpu > [94m1[39m:                                       [31m│
[31m│[39m   2591 │   │   │   loss = loss.mean()  # mean() to average on multi-gpu para [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/transformers/[1mtrainer.py[22m:[94m2620[39m in  [31m│
[31m│[39m [92mcompute_loss[39m                                                                 [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   2617 │   │   │   labels = inputs.pop([33m"labels"[39m)                             [31m│
[31m│[39m   2618 │   │   [94melse[39m:                                                         [31m│
[31m│[39m   2619 │   │   │   labels = [94mNone[39m                                             [31m│
[31m│[39m [31m❱ [39m2620 │   │   outputs = model(**inputs)                                     [31m│
[31m│[39m   2621 │   │   # Save past state if it exists                                [31m│
[31m│[39m   2622 │   │   # TODO: this needs to be fixed and made cleaner later.        [31m│
[31m│[39m   2623 │   │   [94mif[39m [96mself[39m.args.past_index >= [94m0[39m:                                 [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/[1mmodule.py[22m:[94m1194[39m  [31m│
[31m│[39m in [92m_call_impl[39m                                                                [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   1191 │   │   # this function, and just call forward.                       [31m│
[31m│[39m   1192 │   │   [94mif[39m [95mnot[39m ([96mself[39m._backward_hooks [95mor[39m [96mself[39m._forward_hooks [95mor[39m [96mself[39m._ [31m│
[31m│[39m   1193 │   │   │   │   [95mor[39m _global_forward_hooks [95mor[39m _global_forward_pre_hooks [31m│
[31m│[39m [31m❱ [39m1194 │   │   │   [94mreturn[39m forward_call(*[96minput[39m, **kwargs)                     [31m│
[31m│[39m   1195 │   │   # Do not call functions when jit is used                      [31m│
[31m│[39m   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []         [31m│
[31m│[39m   1197 │   │   [94mif[39m [96mself[39m._backward_hooks [95mor[39m _global_backward_hooks:            [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/peft/[1mpeft_model.py[22m:[94m639[39m in        [31m│
[31m│[39m [92mforward[39m                                                                      [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   636 │   │   **kwargs,                                                      [31m│
[31m│[39m   637 │   ):                                                                 [31m│
[31m│[39m   638 │   │   [94mif[39m [95mnot[39m [96misinstance[39m([96mself[39m.peft_config, PromptLearningConfig):     [31m│
[31m│[39m [31m❱ [39m639 │   │   │   [94mreturn[39m [96mself[39m.base_model(                                    [31m│
[31m│[39m   640 │   │   │   │   input_ids=input_ids,                                   [31m│
[31m│[39m   641 │   │   │   │   attention_mask=attention_mask,                         [31m│
[31m│[39m   642 │   │   │   │   inputs_embeds=inputs_embeds,                           [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/[1mmodule.py[22m:[94m1194[39m  [31m│
[31m│[39m in [92m_call_impl[39m                                                                [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   1191 │   │   # this function, and just call forward.                       [31m│
[31m│[39m   1192 │   │   [94mif[39m [95mnot[39m ([96mself[39m._backward_hooks [95mor[39m [96mself[39m._forward_hooks [95mor[39m [96mself[39m._ [31m│
[31m│[39m   1193 │   │   │   │   [95mor[39m _global_forward_hooks [95mor[39m _global_forward_pre_hooks [31m│
[31m│[39m [31m❱ [39m1194 │   │   │   [94mreturn[39m forward_call(*[96minput[39m, **kwargs)                     [31m│
[31m│[39m   1195 │   │   # Do not call functions when jit is used                      [31m│
[31m│[39m   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []         [31m│
[31m│[39m   1197 │   │   [94mif[39m [96mself[39m._backward_hooks [95mor[39m _global_backward_hooks:            [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/accelerate/[1mhooks.py[22m:[94m156[39m in       [31m│
[31m│[39m [92mnew_forward[39m                                                                  [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   153 │   │   │   [94mwith[39m torch.no_grad():                                      [31m│
[31m│[39m   154 │   │   │   │   output = old_forward(*args, **kwargs)                  [31m│
[31m│[39m   155 │   │   [94melse[39m:                                                          [31m│
[31m│[39m [31m❱ [39m156 │   │   │   output = old_forward(*args, **kwargs)                      [31m│
[31m│[39m   157 │   │   [94mreturn[39m module._hf_hook.post_forward(module, output)            [31m│
[31m│[39m   158 │                                                                      [31m│
[31m│[39m   159 │   module.forward = new_forward                                       [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/transformers/models/t5/[1mmodeling_[22m [31m│
[31m│[39m [1mt5.py[22m:[94m1722[39m in [92mforward[39m                                                        [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   1719 │   │   │   # See https://github.com/tensorflow/mesh/blob/fa19d69eafc [31m│
[31m│[39m   1720 │   │   │   sequence_output = sequence_output * ([96mself[39m.model_dim**-[94m0.5[39m [31m│
[31m│[39m   1721 │   │                                                                 [31m│
[31m│[39m [31m❱ [39m1722 │   │   lm_logits = [96mself[39m.lm_head(sequence_output)                     [31m│
[31m│[39m   1723 │   │                                                                 [31m│
[31m│[39m   1724 │   │   loss = [94mNone[39m                                                   [31m│
[31m│[39m   1725 │   │   [94mif[39m labels [95mis[39m [95mnot[39m [94mNone[39m:                                        [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/[1mmodule.py[22m:[94m1194[39m  [31m│
[31m│[39m in [92m_call_impl[39m                                                                [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   1191 │   │   # this function, and just call forward.                       [31m│
[31m│[39m   1192 │   │   [94mif[39m [95mnot[39m ([96mself[39m._backward_hooks [95mor[39m [96mself[39m._forward_hooks [95mor[39m [96mself[39m._ [31m│
[31m│[39m   1193 │   │   │   │   [95mor[39m _global_forward_hooks [95mor[39m _global_forward_pre_hooks [31m│
[31m│[39m [31m❱ [39m1194 │   │   │   [94mreturn[39m forward_call(*[96minput[39m, **kwargs)                     [31m│
[31m│[39m   1195 │   │   # Do not call functions when jit is used                      [31m│
[31m│[39m   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []         [31m│
[31m│[39m   1197 │   │   [94mif[39m [96mself[39m._backward_hooks [95mor[39m _global_backward_hooks:            [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/gaochangkuan_AI/PromptCLUE_Finetuning/[1mint8_peft_lora_PromptCLUE_Finetu[22m [31m│
[31m│[39m [1mning.py[22m:[94m175[39m in [92mforward[39m                                                       [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   172                                                                        [31m│
[31m│[39m   173 [94mclass[39m [4mCastOutputToFloat[24m(nn.Sequential):                                [31m│
[31m│[39m   174   [94mdef[39m [92mforward[39m([96mself[39m, x):                                                [31m│
[31m│[39m [31m❱ [39m175 │   [94mreturn[39m [96msuper[39m().forward(x).to(torch.float32)                        [31m│
[31m│[39m   176                                                                        [31m│
[31m│[39m   177 model.lm_head = CastOutputToFloat(model.lm_head)                       [31m│
[31m│[39m   178                                                                        [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/[1mcontainer.py[22m:[94m20[39m [31m│
[31m│[39m [94m4[39m in [92mforward[39m                                                                 [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   201 │   # with Any as TorchScript expects a more precise type              [31m│
[31m│[39m   202 │   [94mdef[39m [92mforward[39m([96mself[39m, [96minput[39m):                                          [31m│
[31m│[39m   203 │   │   [94mfor[39m module [95min[39m [96mself[39m:                                            [31m│
[31m│[39m [31m❱ [39m204 │   │   │   [96minput[39m = module([96minput[39m)                                      [31m│
[31m│[39m   205 │   │   [94mreturn[39m [96minput[39m                                                   [31m│
[31m│[39m   206 │                                                                      [31m│
[31m│[39m   207 │   [94mdef[39m [92mappend[39m([96mself[39m, module: Module) -> [33m'Sequential'[39m:                  [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/[1mmodule.py[22m:[94m1194[39m  [31m│
[31m│[39m in [92m_call_impl[39m                                                                [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   1191 │   │   # this function, and just call forward.                       [31m│
[31m│[39m   1192 │   │   [94mif[39m [95mnot[39m ([96mself[39m._backward_hooks [95mor[39m [96mself[39m._forward_hooks [95mor[39m [96mself[39m._ [31m│
[31m│[39m   1193 │   │   │   │   [95mor[39m _global_forward_hooks [95mor[39m _global_forward_pre_hooks [31m│
[31m│[39m [31m❱ [39m1194 │   │   │   [94mreturn[39m forward_call(*[96minput[39m, **kwargs)                     [31m│
[31m│[39m   1195 │   │   # Do not call functions when jit is used                      [31m│
[31m│[39m   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []         [31m│
[31m│[39m   1197 │   │   [94mif[39m [96mself[39m._backward_hooks [95mor[39m _global_backward_hooks:            [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/accelerate/[1mhooks.py[22m:[94m156[39m in       [31m│
[31m│[39m [92mnew_forward[39m                                                                  [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   153 │   │   │   [94mwith[39m torch.no_grad():                                      [31m│
[31m│[39m   154 │   │   │   │   output = old_forward(*args, **kwargs)                  [31m│
[31m│[39m   155 │   │   [94melse[39m:                                                          [31m│
[31m│[39m [31m❱ [39m156 │   │   │   output = old_forward(*args, **kwargs)                      [31m│
[31m│[39m   157 │   │   [94mreturn[39m module._hf_hook.post_forward(module, output)            [31m│
[31m│[39m   158 │                                                                      [31m│
[31m│[39m   159 │   module.forward = new_forward                                       [31m│
[31m│[39m                                                                              [31m│
[31m│[39m /root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/[1mlinear.py[22m:[94m114[39m   [31m│
[31m│[39m in [92mforward[39m                                                                   [31m│
[31m│[39m                                                                              [31m│
[31m│[39m   111 │   │   │   init.uniform_([96mself[39m.bias, -bound, bound)                    [31m│
[31m│[39m   112 │                                                                      [31m│
[31m│[39m   113 │   [94mdef[39m [92mforward[39m([96mself[39m, [96minput[39m: Tensor) -> Tensor:                        [31m│
[31m│[39m [31m❱ [39m114 │   │   [94mreturn[39m F.linear([96minput[39m, [96mself[39m.weight, [96mself[39m.bias)                 [31m│
[31m│[39m   115 │                                                                      [31m│
[31m│[39m   116 │   [94mdef[39m [92mextra_repr[39m([96mself[39m) -> [96mstr[39m:                                       [31m│
[31m│[39m   117 │   │   [94mreturn[39m [33m'in_features={}, out_features={}, bias={}'[39m.format(      [31m│
[31m╰──────────────────────────────────────────────────────────────────────────────╯
[1mRuntimeError: [22mexpected scalar type Float but found Half
```
What is the reason for this, please?
Also, I am trying to enable the operations fp16, gradient_checkpointing, gradient_accumulation_steps at the same time, is there any conflict with this?

**Comment by oushu1zhangxiangxuan1** [comment]
Hey, How did you solve this problem? Thank you.

**Comment by Yclock** [comment]
> Hey, How did you solve this problem? Thank you.

你好，你解决这个问题了吗？
