### ISSUE TITLE
Modules_to_save can't be used with DDP and gradient checkpointing 

### ISSUE THREAD

**Issue by passaglia** [huggingface/peft#899]
### System Info

To train a model with gradient checkpointing and DDP, the model should have no unused parameters and the HF trainer's ddp_find_unused_parameters argument should be set to False.

However, peft's modules_to_save functionality creates unused parameters: the ModulesToSaveWrapper's original_module.

Gradient_checkpointing and DDP are really powerful in peft runs since large models can be made to fit on a single GPU, so it would be great to fix this functionality.

I attach a minimal example of a PEFT training script that fails with ddp.

### Who can help?

@pacman100 @younesbelkada @BenjaminBossan 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer
from peft import (
    TaskType,
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training
)
from transformers import DataCollatorForSeq2Seq, TrainingArguments
from datasets import load_dataset

model = AutoModelForCausalLM.from_pretrained('EleutherAI/pythia-70m',device_map='auto',torch_dtype='auto')
tokenizer = AutoTokenizer.from_pretrained('EleutherAI/pythia-70m')
tokenizer.pad_token_id = 0

model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)

model = get_peft_model(model, LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    bias="none",
    target_modules=['dense'],
    modules_to_save=['embed_out'],
)

dataset = load_dataset('tatsu-lab/alpaca', split="train[:100]")

train_data = dataset.map(lambda x: tokenizer(x['text'], return_tensors=None, padding='max_length', truncation=True, max_length=128))
train_data = train_data.map(lambda x: {'labels': x['input_ids']})

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,  pad_to_multiple_of=8, return_tensors="pt", padding=True
)

trainer = Trainer(
    model=model,
    train_dataset=train_data,
    args=TrainingArguments(output_dir='dummy', 	 
          per_device_train_batch_size=1,
          save_strategy='epoch',
          save_steps=1,
          ddp_find_unused_parameters=False),
    data_collator=data_collator)

trainer.train()
```

DDP launch command:
```bash
torchrun \
--nproc_per_node=1 \
--nnodes=1 \
--rdzv-backend=c10d \
--rdzv-endpoint=localhost:0 \
test.py
```

### Expected behavior

The training run should launch

**Comment by BenjaminBossan** [comment]
Yes, thanks a lot for reporting the error and providing the code. I ran into that error last week as well. The error message was:

```
$ TORCH_DISTRIBUTED_DEBUG=DETAIL accelerate launch peft-train-with-accel.py 
Traceback (most recent call last):
  File "/.../peft-train-with-accel.py", line 54, in <module>
    logits = model(xb)
  File "/opt/conda/envs/skorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/skorch/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

Parameters which did not receive grad for rank 0: base_model.model.score.original_module.bias, base_model.model.score.original_module.weight

Parameter indices which did not receive grad for rank 0: 10 11
Traceback (most recent call last):
  File "/.../peft-train-with-accel.py", line 54, in <module>
    logits = model(xb)
  File "/opt/conda/envs/skorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/skorch/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameters which did not receive grad for rank 1: base_model.model.score.original_module.bias, base_model.model.score.original_module.weight
Parameter indices which did not receive grad for rank 1: 10 11
```

**Comment by passaglia** [comment]
Great, thanks for reproducing it! One can get around the issue by simply setting self.original_modules = None at the end of the [update method](https://github.com/huggingface/peft/blob/0c9354bda98eb7f5348699e23ab752e8dca1e60e/src/peft/utils/other.py#L160), but that's quite hacky.

**Comment by BenjaminBossan** [comment]
Indeed, this workaround can help but is not optimal. There might be situations where the original module is needed later (which is why we store it in the first place).

Could you please try something: On the `model`, add an attrbitute `_ddp_params_and_buffers_to_ignore` with the name of corresponding module(s), e.g.:

```python
model._ddp_params_and_buffers_to_ignore = ["base_model.model.score.original_module.bias", "base_model.model.score.original_module.weight"]
```

Does that fix the error for you?

**Comment by BenjaminBossan** [comment]
Thanks for confirming. Let's leave this issue open for now, because I think we can add a mechanism in PEFT to automate this for `modules_to_save`.

**Comment by passaglia** [comment]
I think the spot to do it is probably in [_set_trainable](https://github.com/huggingface/peft/blob/0c9354bda98eb7f5348699e23ab752e8dca1e60e/src/peft/utils/other.py#L202).
We could make a new list ddp_params_and_buffers_to_ignore and add the relevant modules to it during the loop with:
```python
if target_module_found:
     ddp_params_and_buffers_to_ignore.append(f'{key}.original_module.weight')
     ddp_params_and_buffers_to_ignore.append(f'{key}.original_module.bias')
```
and then at the end of the loop set
```
model._ddp_params_and_buffers_to_ignore = ddp_params_and_buffers_to_ignore
```

**Comment by BenjaminBossan** [comment]
I think it won't be as easy as that. We need a more general mechanism that allows each adapter layer to define their own `ddp_params_and_buffers_to_ignore`, and then a way to collect all of those on the `PeftModel` and expose it to PyTorch DDP.

To give an example, if I have a PEFT model with two different LoRA adapters, only one of which can be active at a time, we get the same error, because the other adapter's parameter don't participate in the loss calculation. I checked it just now and there is the same type of error. I'm working on a solution that should hopefully fix that, but it's going to be a bit more complicated.

What I'm not sure about is why this is an issue in the first place. The unused parameters should not be part of the loss computation, so why can DDP not just ignore them?

**Comment by passaglia** [comment]
Ah I see this can get complicated. I also don't know why DDP cares about this in the first place, but there's some discussion in the [PR which originally implemented ddp_params_and_buffers_to_ignore](https://github.com/pytorch/pytorch/issues/43690) .

**Comment by BenjaminBossan** [comment]
Thanks for the link. IMHO, it still doesn't really explain why this cannot be solved by directly ignoring the corresponding params, but there is probably some deep technical reason for it. Anyway, I created a draft PR in #900 that should hopefully fix the issue.

**Comment by passaglia** [comment]
While working a bit more on a related model I found that the original_module has requires_grad = True. Setting requires_grad = False for these parameters also avoids the DDP error, without needing to use ddp_params_and_buffers_to_ignore.

```python
for key, _ in model.named_modules():
    target_module_found = any(key.endswith(target_key) for target_key in modules_to_save])
    if target_module_found:
        model.get_submodule(key+'.original_module').requires_grad_(False)
```

I'm not sure if this has any performance benefits but it does ensure that the HF trainer's `Number of trainable parameters` output is corrrect.

**Comment by BenjaminBossan** [comment]
Oh I see, that's really helpful. So another approach would be to set `requires_grad` correctly for all inactive parts of the layers. I'll check if that would be a better solution.
