### ISSUE TITLE
add_adapter raises KeyError after merge_and_unload of a LoRA model

### ISSUE THREAD

**Issue by hiyouga** [huggingface/peft#923]
### System Info

Ubuntu 22.04
Python 3.10.12
transformers==4.32.1
peft==0.5.0

### Who can help?

@pacman100 @younesbelkada 

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

To reproduce:

```python
import torch
from transformers import AutoModelForCausalLM
from peft import PeftModel, LoraConfig, TaskType, get_peft_model

if __name__ == "__main__":
    model = AutoModelForCausalLM.from_pretrained(
        "meta-llama/Llama-2-7b-hf",
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True
    )
    model = PeftModel.from_pretrained(model, "my_checkpoint")
    print(id(model.peft_config))
    print(id(model.base_model.peft_config))

    model = model.merge_and_unload()
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        inference_mode=False,
        r=8,
        lora_alpha=32,
        lora_dropout=0.1,
        target_modules=["q_proj"]
    )
    model = get_peft_model(model, lora_config)
    print(id(model.peft_config))
    print(id(model.base_model.peft_config))

    new_config = LoraConfig.from_pretrained("another_checkpoint")
    model.add_adapter("new_adapter", new_config) # raises KeyError
```

Output:

```
140201722488320
140201722488320
140201722487104
140201722488320
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    model.add_adapter("new_adapter", new_config)
  File "/home/anaconda3/envs/lib/python3.10/site-packages/peft/peft_model.py", line 502, in add_adapter
    self.base_model.inject_adapter(self, adapter_name)
  File "/home/anaconda3/envs/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 192, in inject_adapter
    peft_config = self.peft_config[adapter_name]
KeyError: 'new_adapter'
```

### Expected behavior

The PeftModel and LoraModel objects initially share the same **peft_config** variable, so the add_adapter method can work normally. 

However, the PeftModel and LoraModel have different **peft_config** variables after calling the merge_and_unload method, resulting in a KeyError when adding a new adapter to the model.

**Comment by BenjaminBossan** [comment]
Thanks for reporting. This should be solved by #921.
