### ISSUE TITLE
save_pretrained() creates incorrect adapter_model.bin file, when training LoRA model with multi-card zero-3

### ISSUE THREAD

**Issue by Imagium719** [huggingface/peft#939]
### System Info

peft=0.5.0
accelerate=0.23.0
transformers=4.33.2
torch=2.0.1
python=3.8.18

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

# main.py:
```python
import torch

from torch.utils.data.dataloader import DataLoader
from torch.utils.data.dataset import Dataset

from datasets import load_dataset

import transformers
from accelerate import Accelerator
from tqdm import tqdm

import peft

class myset(Dataset):
    ...

def main():
    accelerator = Accelerator()
    model = transformers.LlamaForCausalLM.from_pretrained("******/zh-llama/7b")
    loraconfig = peft.LoraConfig(
        r=64,
        lora_alpha=128,
        lora_dropout=0.05,
        target_modules=[
            "q_proj",
            "v_proj",
            "k_proj",
#            "o_proj",
#            "gate_proj",
#            "down_proj",
#            "up_proj",
        ],
        task_type=peft.TaskType.CAUSAL_LM,
    )
    model = peft.PeftModel(model, loraconfig)
    model.print_trainable_parameters()
    tokenizer = transformers.LlamaTokenizer.from_pretrained("******/zh-llama/tokenizer")
    optimizer = torch.optim.AdamW(model.parameters(), lr = 1e-5, weight_decay = 1e-5)
    #optimizer = DummyOptim(model.parameters(), fp32_optimizer_states=False)
    #scheduler = DummyScheduler(optimizer, 5850 * 3, 5850 * 3 / 10)
    trainset = myset(
        load_dataset(
            "/home/hos/workspace/datasets/madao33/new-title-chinese",
            split="train",
        ),
        tokenizer,
    )
    trainloader = DataLoader(
        trainset,
        batch_size=1,
        shuffle=True,
        num_workers=1,
        collate_fn=transformers.default_data_collator,
    )
    # testloader = DataLoader(testset, batch_size=2, shuffle=False, num_workers=4)
    model, optimizer, trainloader = accelerator.prepare(
        model, optimizer, trainloader
    )
    print(model)
    model.train()
    #deepspeed.DeepSpeedEngine
    accelerator.wait_for_everyone()
    for epoch in range(3):
        totalloss = 0.0
        for step, batch in enumerate(tqdm(trainloader)):
            if step > 10:
                break
            for key in batch.keys():
                batch[key] = batch[key].cuda()
            loss:torch.Tensor = model(
                input_ids=batch["input_ids"],
                attention_mask=batch["attention_mask"],
                labels=batch["labels"],
            ).loss
            totalloss += loss.mean().item()
            accelerator.backward(loss)
            optimizer.step()
            #scheduler.step()
            optimizer.zero_grad()
            accelerator.wait_for_everyone()

        print("Epoch ", epoch, " avg loss: ", totalloss/len(trainloader))
        #unwrapped_model:peft.PeftModel = accelerator.unwrap_model(model)
        accelerator.wait_for_everyone()
        model.save_pretrained(
            f"./checkpoints/epoch-{epoch}",
            is_main_process=accelerator.is_main_process,
            save_function=accelerator.save,
            state_dict=accelerator.get_state_dict(model),
        )
        accelerator.wait_for_everyone()
    
if __name__ == "__main__":
    main()
```

# ds.yaml:
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: 'cpu'
  offload_param_device: 'cpu'
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
  contiguous_gradients: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
```

# train.sh:
```sh
#!/bin/sh
export OMP_NUM_THREADS=8
accelerate launch --config_file ds.yaml main.py
```

I tried every method of saving models, including using unwrap_model(model) and adjusting parameters of save_pretrained() function, etc, but none of them works.

### Expected behavior

It seemed OK when the training script ends, but when I tryed to load the model, it says "PytorchStreamReader failed reading file data/0":
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hos/miniconda3/envs/pyend/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3260, in from_pretrained
    model.load_adapter(
  File "/home/hos/miniconda3/envs/pyend/lib/python3.8/site-packages/transformers/integrations/peft.py", line 151, in load_adapter
    adapter_state_dict = load_peft_weights(peft_model_id, revision=revision, use_auth_token=token)
  File "/home/hos/miniconda3/envs/pyend/lib/python3.8/site-packages/peft/utils/save_and_load.py", line 198, in load_peft_weights
    adapters_weights = torch.load(filename, map_location=torch.device(device))
  File "/home/hos/miniconda3/envs/pyend/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/hos/miniconda3/envs/pyend/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/hos/miniconda3/envs/pyend/lib/python3.8/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/hos/miniconda3/envs/pyend/lib/python3.8/site-packages/torch/serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: PytorchStreamReader failed reading file data/0: invalid header or archive is corrupted
```

I tried `unzip adapter_model.bin`, discovering that the first few packages were missing or broken.
```
(base) ***@*****:*/checkpoints/epoch-1$ unzip adapter_model.bin
Archive:  adapter_model.bin
 extracting: adapter_model/data.pkl   bad CRC 7d367a1c  (should be 3b14ea4d)
file #2:  bad zipfile offset (local header sig):  28738
file #3:  bad zipfile offset (local header sig):  1077392
file #4:  bad zipfile offset (local header sig):  2126096
file #5:  bad zipfile offset (local header sig):  3174800
 extracting: adapter_model/data/101  
 extracting: adapter_model/data/102  
 extracting: adapter_model/data/103  
 extracting: adapter_model/data/104  
 extracting: adapter_model/data/105  
 extracting: adapter_model/data/106  
 extracting: adapter_model/data/107  
 extracting: adapter_model/data/108  
 extracting: adapter_model/data/109  
 extracting: adapter_model/data/11   
 extracting: adapter_model/data/110  
 extracting: adapter_model/data/111
...
```

Sometimes this bug doesn't appear when tested with tiny models. Generally the larger the model is, the more likely it will appear.

**Comment by Imagium719** [comment]
@pacman100 @younesbelkada
Please see this issue, thank you!

**Comment by BenjaminBossan** [comment]
This seems to be the same issue as in https://github.com/huggingface/accelerate/issues/1922.

I wonder [this PR](https://github.com/huggingface/accelerate/pull/1953) might fix the problem, would it be possible for you to test again using that accelerate branch?

**Comment by BenjaminBossan** [comment]
Do you mean that we should add a `save_function` argument to `save_pretrained`, so as to be able to pass `accelerator.save`? Yes, I think that would make sense.
